export const barList = [
    {
      "Bar": "Taft's Ale House",
      "Description": "Artisanal beers, steaks & salads served in a classic brewpub named after Cincinnati’s favorite son.",
      "Neighborhood": "Over-the-Rhine",
      "Address": "1429 Race St, Cincinnati, OH 45202",
      "Phone": "(513) 334-1393",
      "Website": "http://taftsalehouse.com/",
      "Hours - Monday": "11:30AM–10PM",
      "Hours - Tuesday": "11:30AM–10PM",
      "Hours - Wednesday": "11:30AM–11PM",
      "Hours - Thursday": "11:30AM–12AM",
      "Hours - Friday": "11:30AM–12AM",
      "Hours - Saturday": "11:30AM–12AM",
      "Hours - Sunday": "11:30AM–9PM",
      "Specials - Monday": "",
      "Specials - Tuesday": "Taft Tuesdays - Enjoy Half-Price Pints & Growler Fills ALL DAY by wearing any Brewery or Beer Apparel. Don’t have any threads? Stop-n-shop in Nellie’s Tap Room to pick up your gear!",
      "Specials - Wednesday": "",
      "Specials - Thursday": "",
      "Specials - Friday": "",
      "Specials - Saturday": "",
      "Specials - Sunday": "",
      "Note": ""
    },
    {
      "Bar": "Sundry and Vice",
      "Description": "Striking, well-appointed cocktail spot with a tin ceiling & vintage feel offering inventive drinks.",
      "Neighborhood": "Over-the-Rhine",
      "Address": "18 W 13th St, Cincinnati, OH 45202",
      "Phone": "(513) 721-8423",
      "Website": "http://sundryandvice.com/",
      "Hours - Monday": "Closed",
      "Hours - Tuesday": "4PM–2AM",
      "Hours - Wednesday": "4PM–2AM",
      "Hours - Thursday": "4PM–2AM",
      "Hours - Friday": "4PM–2AM",
      "Hours - Saturday": "12PM–2AM",
      "Hours - Sunday": "12PM–12AM",
      "Specials - Monday": "",
      "Specials - Tuesday": "",
      "Specials - Wednesday": "",
      "Specials - Thursday": "",
      "Specials - Friday": "",
      "Specials - Saturday": "",
      "Specials - Sunday": "",
      "Note": ""
    },
    {
      "Bar": "The Rook OTR",
      "Description": "",
      "Neighborhood": "Over-the-Rhine",
      "Address": "1115 Vine St, Cincinnati, OH 45202",
      "Phone": "(513) 954-8191",
      "Website": "https://www.facebook.com/therookotr/",
      "Hours - Monday": "4PM–12AM",
      "Hours - Tuesday": "4PM–12AM",
      "Hours - Wednesday": "4PM–12AM",
      "Hours - Thursday": "4PM–12AM",
      "Hours - Friday": "4PM–2AM",
      "Hours - Saturday": "11AM–2AM",
      "Hours - Sunday": "11AM–12AM",
      "Specials - Monday": "",
      "Specials - Tuesday": "",
      "Specials - Wednesday": "",
      "Specials - Thursday": "",
      "Specials - Friday": "",
      "Specials - Saturday": "",
      "Specials - Sunday": "",
      "Note": "Lots of different events. "
    },
    {
      "Bar": "The Lackman",
      "Description": "Luxe lounge in a turn-of-the-century building offering craft beers & eclectic wines, plus a jukebox.",
      "Neighborhood": "Over-the-Rhine",
      "Address": "1237 Vine Street, Cincinnati, OH 45202",
      "Phone": "(513) 381-0741",
      "Website": "http://www.lackmanbar.com/",
      "Hours - Monday": "4PM–2AM",
      "Hours - Tuesday": "4PM–2AM",
      "Hours - Wednesday": "4PM–2AM",
      "Hours - Thursday": "4PM–2AM",
      "Hours - Friday": "3PM–2AM",
      "Hours - Saturday": "12PM–2AM",
      "Hours - Sunday": "12PM–12AM",
      "Specials - Monday": "HAPPY HOUR\nHappy Hour | 4-8PM\n$2 Off Drafts\n$3.25 Domestics\n$4.50 Calls\n$5 Dark Horse Wines",
      "Specials - Tuesday": "HAPPY HOUR\nHappy Hour | 4-8PM\n$2 Off Drafts\n$3.25 Domestics\n$4.50 Calls\n$5 Dark Horse Wines",
      "Specials - Wednesday": "HAPPY HOUR\nHappy Hour | 4-8PM\n$2 Off Drafts\n$3.25 Domestics\n$4.50 Calls\n$5 Dark Horse Wines",
      "Specials - Thursday": "HAPPY HOUR\nHappy Hour | 4-8PM\n$2 Off Drafts\n$3.25 Domestics\n$4.50 Calls\n$5 Dark Horse Wines",
      "Specials - Friday": "HAPPY HOUR\nHappy Hour | 4-8PM\n$2 Off Drafts\n$3.25 Domestics\n$4.50 Calls\n$5 Dark Horse Wines",
      "Specials - Saturday": "HAPPY HOUR\nHappy Hour | 4-8PM\n$2 Off Drafts\n$3.25 Domestics\n$4.50 Calls\n$5 Dark Horse Wines",
      "Specials - Sunday": "HAPPY HOUR\nHappy Hour | 4-8PM\n$2 Off Drafts\n$3.25 Domestics\n$4.50 Calls\n$5 Dark Horse Wines",
      "Note": ""
    },
    {
      "Bar": "Japp's - Since 1879",
      "Description": "Bustling spot for classic & creative cocktails served in casual environs in a storied building.",
      "Neighborhood": "Over-the-Rhine",
      "Address": "1136 Main St, Cincinnati, OH 45202",
      "Phone": "(513) 381-1524",
      "Website": "http://japps1879.com/",
      "Hours - Monday": "Closed",
      "Hours - Tuesday": "4PM–1AM",
      "Hours - Wednesday": "4PM–1AM",
      "Hours - Thursday": "4PM–1AM",
      "Hours - Friday": "4PM–2AM",
      "Hours - Saturday": "5PM–2AM",
      "Hours - Sunday": "Closed",
      "Specials - Monday": "",
      "Specials - Tuesday": "",
      "Specials - Wednesday": "",
      "Specials - Thursday": "Live Music from Jess Lamb and Friends\n9:00 PM – 11:30 PM\nLive music from Cincinnati native, Jess Lamb, and special guests, every week!",
      "Specials - Friday": "The Burning Caravan at Japp's\n 5:30 PM – 8:30 PM\nLive Music from The Burning Caravan from 530-830pm EVERY Friday!\nRotating Local DJ's in the Lounge\n9:00 PM – 11:30 PM\nEvery Friday night we host a DJ for a late night set in the lounge! Check us out on Facebook for info on this week's DJ! \n9pm-close every Friday!",
      "Specials - Saturday": "Live Happy Hour Music\n6:00 PM – 9:00 PM\nLive Happy Hour Music Every Saturday.",
      "Specials - Sunday": "",
      "Note": ""
    },
    {
      "Bar": "rhinehaus",
      "Description": "Laid-back hangout with sports on TV & craft beers offered in a contemporary, exposed-brick space.",
      "Neighborhood": "Over-the-Rhine",
      "Address": "119 E 12th St, Cincinnati, OH 45202",
      "Phone": "(513) 381-2277",
      "Website": "http://www.rhinehausbar.com/",
      "Hours - Monday": "4PM–2AM",
      "Hours - Tuesday": "4PM–2AM",
      "Hours - Wednesday": "4PM–2AM",
      "Hours - Thursday": "4PM–2AM",
      "Hours - Friday": "4PM–2AM",
      "Hours - Saturday": "7AM–2AM",
      "Hours - Sunday": "7AM–12AM",
      "Specials - Monday": "",
      "Specials - Tuesday": "",
      "Specials - Wednesday": "",
      "Specials - Thursday": "",
      "Specials - Friday": "",
      "Specials - Saturday": "",
      "Specials - Sunday": "",
      "Note": ""
    },
    {
      "Bar": "Motr Pub",
      "Description": "Easygoing hangout with local art on the walls, featuring live rock bands & hearty comfort fare.",
      "Neighborhood": "Over-the-Rhine",
      "Address": "1345 Main St, Cincinnati, OH 45202",
      "Phone": "(513) 381-6687",
      "Website": "http://www.pubcincinnati.com/",
      "Hours - Monday": "11AM–2:30AM",
      "Hours - Tuesday": "11AM–2:30AM",
      "Hours - Wednesday": "11AM–2:30AM",
      "Hours - Thursday": "11AM–2:30AM",
      "Hours - Friday": "11AM–2:30AM",
      "Hours - Saturday": "10AM–2:30AM",
      "Hours - Sunday": "10AM–2:30AM",
      "Specials - Monday": "",
      "Specials - Tuesday": "",
      "Specials - Wednesday": "",
      "Specials - Thursday": "",
      "Specials - Friday": "",
      "Specials - Saturday": "",
      "Specials - Sunday": "",
      "Note": ""
    },
    {
      "Bar": "Bakersfield OTR",
      "Description": "Tacos & a few other Mexican dishes are delivered in a chic, upbeat, margarita-fueled atmosphere.",
      "Neighborhood": "Over-the-Rhine",
      "Address": "1213 Vine St, Cincinnati, OH 45202",
      "Phone": "(513) 579-0446",
      "Website": "http://www.bakersfieldtacos.com/",
      "Hours - Monday": "11AM–12AM",
      "Hours - Tuesday": "11AM–12AM",
      "Hours - Wednesday": "11AM–12AM",
      "Hours - Thursday": "11AM–12AM",
      "Hours - Friday": "11AM–2AM",
      "Hours - Saturday": "11AM–2AM",
      "Hours - Sunday": "11AM–12AM",
      "Specials - Monday": "",
      "Specials - Tuesday": "",
      "Specials - Wednesday": "",
      "Specials - Thursday": "",
      "Specials - Friday": "",
      "Specials - Saturday": "",
      "Specials - Sunday": "",
      "Note": ""
    },
    {
      "Bar": "Below Zero Lounge",
      "Description": "Trendy spot with upbeat music serving over 100 vodkas, with featured vodkas served at 6° F.",
      "Neighborhood": "Over-the-Rhine",
      "Address": "1120 Walnut St, Cincinnati, OH 45202",
      "Phone": "(513) 421-9376",
      "Website": "http://www.belowzerolounge.com/",
      "Hours - Monday": "Closed",
      "Hours - Tuesday": "Closed",
      "Hours - Wednesday": "4PM–12AM",
      "Hours - Thursday": "4PM–2AM",
      "Hours - Friday": "4PM–2AM",
      "Hours - Saturday": "4PM–2AM",
      "Hours - Sunday": "4PM–12AM",
      "Specials - Monday": "Happy Hour, 4-8pm",
      "Specials - Tuesday": "Happy Hour, 4-8pm",
      "Specials - Wednesday": "Happy Hour, 4-8pm",
      "Specials - Thursday": "Happy Hour, 4-8pm",
      "Specials - Friday": "Happy Hour, 4-8pm",
      "Specials - Saturday": "Happy Hour, 4-8pm",
      "Specials - Sunday": "Happy Hour, 4-8pm",
      "Note": ""
    },
    {
      "Bar": "1215 Wine Bar & Coffee Lab",
      "Description": "Homey, brick-walled cafe & bar offering breakfast, baked goods, small plates & wine tastings.",
      "Neighborhood": "Over-the-Rhine",
      "Address": "1215 Vine St, Cincinnati, OH 45202",
      "Phone": "(513) 429-5745",
      "Website": "http://www.1215vine.com/",
      "Hours - Monday": "8AM–10PM",
      "Hours - Tuesday": "8AM–10PM",
      "Hours - Wednesday": "8AM–11PM",
      "Hours - Thursday": "8AM–12AM",
      "Hours - Friday": "8AM–12AM",
      "Hours - Saturday": "9AM–12AM",
      "Hours - Sunday": "9AM–7PM",
      "Specials - Monday": "",
      "Specials - Tuesday": "",
      "Specials - Wednesday": "",
      "Specials - Thursday": "",
      "Specials - Friday": "",
      "Specials - Saturday": "",
      "Specials - Sunday": "",
      "Note": ""
    },
    {
      "Bar": "Revolution Rotisserie & Bar",
      "Description": "American dishes centered around rotisserie chicken & cocktails are the draw at this modern outpost.",
      "Neighborhood": "Over-the-Rhine",
      "Address": "1106 Race St, Cincinnati, OH 45202",
      "Phone": "(513) 381-0009",
      "Website": "http://revolutionrotisserie.com/",
      "Hours - Monday": "11AM–9PM",
      "Hours - Tuesday": "11AM–9PM",
      "Hours - Wednesday": "11AM–9PM",
      "Hours - Thursday": "11AM–9PM",
      "Hours - Friday": "11AM–10PM",
      "Hours - Saturday": "11AM–10PM",
      "Hours - Sunday": "10AM–9PM",
      "Specials - Monday": "Six Dollar Mules\nHappy Hour 3-6PM",
      "Specials - Tuesday": "Six Dollar Sangrias\nHappy Hour 3-6PM",
      "Specials - Wednesday": "Four Dollar Drafts\nHappy Hour 3-6PM",
      "Specials - Thursday": "Six Dollar Wines by the Glass\nHappy Hour 3-6PM",
      "Specials - Friday": "Three Dollar Craft Beer Cans\nHappy Hour 3-6PM",
      "Specials - Saturday": "Four Dollar Infusion Shots",
      "Specials - Sunday": "Bottomless Mimosas & Brunch Cocktails",
      "Note": "Happy Hour:\nFour Dollar Drafts\nSix Dollar Wines By the Glass\nSix Dollar Mules/Sangrias\nComplimentary Bottomless Tater Tots during Happy Hour with purchase of alcoholic beverage."
    },
    {
      "Bar": "Low Spark",
      "Description": "",
      "Neighborhood": "Over-the-Rhine",
      "Address": "15 W 14th St, Cincinnati, OH 45202",
      "Phone": "(513) 371-5722",
      "Website": "http://www.lowsparkbar.com/",
      "Hours - Monday": "4PM–2:30AM",
      "Hours - Tuesday": "4PM–2:30AM",
      "Hours - Wednesday": "4PM–2:30AM",
      "Hours - Thursday": "4PM–2:30AM",
      "Hours - Friday": "4PM–2:30AM",
      "Hours - Saturday": "12PM–2:30AM",
      "Hours - Sunday": "Closed",
      "Specials - Monday": "SHOT & BEER SPECIAL\nMON – THU | 8pm – Close\n$5 Shot & Beer Pairing\nHAPPY HOUR\nMON – FRI | 4pm – 7pm\n$2 off signature cocktails\n$2 off select drafts\n$2 off calls\n$1 off domestic beers\n$1 off wine\nEVERY DAY\n$3 Budweiser drafts all day, every day",
      "Specials - Tuesday": "SHOT & BEER SPECIAL\nMON – THU | 8pm – Close\n$5 Shot & Beer Pairing\nHAPPY HOUR\nMON – FRI | 4pm – 7pm\n$2 off signature cocktails\n$2 off select drafts\n$2 off calls\n$1 off domestic beers\n$1 off wine\nEVERY DAY\n$3 Budweiser drafts all day, every day",
      "Specials - Wednesday": "SHOT & BEER SPECIAL\nMON – THU | 8pm – Close\n$5 Shot & Beer Pairing\nHAPPY HOUR\nMON – FRI | 4pm – 7pm\n$2 off signature cocktails\n$2 off select drafts\n$2 off calls\n$1 off domestic beers\n$1 off wine\nEVERY DAY\n$3 Budweiser drafts all day, every day",
      "Specials - Thursday": "SHOT & BEER SPECIAL\nMON – THU | 8pm – Close\n$5 Shot & Beer Pairing\nHAPPY HOUR\nMON – FRI | 4pm – 7pm\n$2 off signature cocktails\n$2 off select drafts\n$2 off calls\n$1 off domestic beers\n$1 off wine\nEVERY DAY\n$3 Budweiser drafts all day, every day",
      "Specials - Friday": "HAPPY HOUR\nMON – FRI | 4pm – 7pm\n$2 off signature cocktails\n$2 off select drafts\n$2 off calls\n$1 off domestic beers\n$1 off wine\nEVERY DAY\n$3 Budweiser drafts all day, every day",
      "Specials - Saturday": "EVERY DAY\n$3 Budweiser drafts all day, every day",
      "Specials - Sunday": "EVERY DAY\n$3 Budweiser drafts all day, every day",
      "Note": "MUSIC HALL SPECIALS\nShow your Cincinnati Music Hall tickets or program to receive $1 off drafts, $1 off domestics, and $1 off Tito’s vodka"
    },
    {
      "Bar": "Longfellow",
      "Description": "",
      "Neighborhood": "Over-the-Rhine",
      "Address": "1233 Clay St, Cincinnati, OH 45202",
      "Phone": "(513) 549-0744",
      "Website": "https://longfellowbar.com/",
      "Hours - Monday": "Closed",
      "Hours - Tuesday": "4PM–2AM",
      "Hours - Wednesday": "4PM–2AM",
      "Hours - Thursday": "4PM–2AM",
      "Hours - Friday": "4PM–2AM",
      "Hours - Saturday": "2PM–2AM",
      "Hours - Sunday": "2PM–12AM",
      "Specials - Monday": "",
      "Specials - Tuesday": "Happy Hour Blue Plate Special $7\n16 oz tall boy beer, scrap sandwich OR liverwurst W/potato chips 4-7PM\nLate Night Pierogies One $2 - Three $5 - Five $8 \n11PM-2AM",
      "Specials - Wednesday": "Happy Hour Blue Plate Special $7\n16 oz tall boy beer, scrap sandwich OR liverwurst W/potato chips 4-7PM\nLate Night Pierogies One $2 - Three $5 - Five $8 \n11PM-2AM\nHot Plate Curry & Rice $8",
      "Specials - Thursday": "Happy Hour Blue Plate Special $7\n16 oz tall boy beer, scrap sandwich OR liverwurst W/potato chips 4-7PM\nLate Night Pierogies One $2 - Three $5 - Five $8 \n11PM-2AM\nHot Plate Curry & Rice $8",
      "Specials - Friday": "Happy Hour Blue Plate Special $7\n16 oz tall boy beer, scrap sandwich OR liverwurst W/potato chips 4-7PM\nLate Night Pierogies One $2 - Three $5 - Five $8 \n11PM-2AM",
      "Specials - Saturday": "Late Night Pierogies One $2 - Three $5 - Five $8 \n11PM-2AM",
      "Specials - Sunday": "Late Night Pierogies One $2 - Three $5 - Five $8 \nAll Day",
      "Note": ""
    },
    {
      "Bar": "Queen City Radio",
      "Description": "Spacious bar in a buzzy, industrial indoor/outdoor space offering food-truck eats, DJs & live music.",
      "Neighborhood": "Over-the-Rhine",
      "Address": "222 W 12th St, Cincinnati, OH 45202",
      "Phone": "(513) 381-0918",
      "Website": "http://qcrbar.com/",
      "Hours - Monday": "4PM–2:30AM",
      "Hours - Tuesday": "4PM–2:30AM",
      "Hours - Wednesday": "4PM–2:30AM",
      "Hours - Thursday": "4PM–2:30AM",
      "Hours - Friday": "4PM–2:30AM",
      "Hours - Saturday": "12PM–2:30AM",
      "Hours - Sunday": "12PM–2:30AM",
      "Specials - Monday": "",
      "Specials - Tuesday": "",
      "Specials - Wednesday": "",
      "Specials - Thursday": "",
      "Specials - Friday": "",
      "Specials - Saturday": "",
      "Specials - Sunday": "",
      "Note": ""
    },
    {
      "Bar": "HalfCut",
      "Description": "Rotating taps of craft brews are the focus of this rustic bar that also sells growlers & wine.",
      "Neighborhood": "Over-the-Rhine",
      "Address": "1126 Walnut St, Cincinnati, OH 45202",
      "Phone": "(513) 381-1952",
      "Website": "http://www.halfcut.com/",
      "Hours - Monday": "Closed",
      "Hours - Tuesday": "4–10PM",
      "Hours - Wednesday": "4–10PM",
      "Hours - Thursday": "11AM–12AM",
      "Hours - Friday": "11AM–2:30AM",
      "Hours - Saturday": "11AM–2:30AM",
      "Hours - Sunday": "Closed",
      "Specials - Monday": "",
      "Specials - Tuesday": "",
      "Specials - Wednesday": "",
      "Specials - Thursday": "",
      "Specials - Friday": "",
      "Specials - Saturday": "",
      "Specials - Sunday": "",
      "Note": ""
    },
    {
      "Bar": "Krueger's Tavern",
      "Description": "Stylish, seasonal New American kitchen with a menu of small & large plates & a rooftop patio.",
      "Neighborhood": "Over-the-Rhine",
      "Address": "1211 Vine St, Cincinnati, OH 45202",
      "Phone": "(513) 834-8670",
      "Website": "http://www.kruegerstavern.com/",
      "Hours - Monday": "11AM–12AM",
      "Hours - Tuesday": "11AM–12AM",
      "Hours - Wednesday": "11AM–12AM",
      "Hours - Thursday": "11AM–12AM",
      "Hours - Friday": "11AM–12AM",
      "Hours - Saturday": "11AM–12AM",
      "Hours - Sunday": "11AM–10PM",
      "Specials - Monday": "",
      "Specials - Tuesday": "",
      "Specials - Wednesday": "",
      "Specials - Thursday": "",
      "Specials - Friday": "",
      "Specials - Saturday": "",
      "Specials - Sunday": "",
      "Note": ""
    },
    {
      "Bar": "Treehouse Patio Bar",
      "Description": "",
      "Neighborhood": "Over-the-Rhine",
      "Address": "1133 Sycamore St, Cincinnati, OH 45202",
      "Phone": "(513) 273-1972",
      "Website": "http://treehousepatiobar.berlindoener.info/",
      "Hours - Monday": "Closed",
      "Hours - Tuesday": "4PM–2AM",
      "Hours - Wednesday": "4PM–2AM",
      "Hours - Thursday": "4PM–2AM",
      "Hours - Friday": "4PM–2AM",
      "Hours - Saturday": "2PM–2AM",
      "Hours - Sunday": "2PM–2AM",
      "Specials - Monday": "",
      "Specials - Tuesday": "",
      "Specials - Wednesday": "",
      "Specials - Thursday": "",
      "Specials - Friday": "",
      "Specials - Saturday": "",
      "Specials - Sunday": "",
      "Note": ""
    },
    {
      "Bar": "Zula Restaurant & Wine Bar",
      "Description": "New American dishes, wine, craft beer & cocktails offered in a warm, industrial-style atmosphere",
      "Neighborhood": "Over-the-Rhine",
      "Address": "7010, 1400 Race St, Cincinnati, OH 45202",
      "Phone": "(513) 744-9852",
      "Website": "http://www.zulabistro.com/",
      "Hours - Monday": "Closed",
      "Hours - Tuesday": "5PM–12AM",
      "Hours - Wednesday": "5PM–12AM",
      "Hours - Thursday": "5PM–12AM",
      "Hours - Friday": "4PM–1AM",
      "Hours - Saturday": "4PM–1AM",
      "Hours - Sunday": "Closed",
      "Specials - Monday": "",
      "Specials - Tuesday": "",
      "Specials - Wednesday": "",
      "Specials - Thursday": "",
      "Specials - Friday": "",
      "Specials - Saturday": "",
      "Specials - Sunday": "",
      "Note": ""
    },
    {
      "Bar": "Anchor OTR",
      "Description": "Charming seafood eatery with a patio for seasonal outdoor dining & a bar with signature cocktails.",
      "Neighborhood": "Over-the-Rhine",
      "Address": "1401 Race St, Cincinnati, OH 45202",
      "Phone": "(513) 421-8111",
      "Website": "http://www.theanchor-otr.com/",
      "Hours - Monday": "Closed",
      "Hours - Tuesday": "5–10PM",
      "Hours - Wednesday": "5–10PM",
      "Hours - Thursday": "5–10PM",
      "Hours - Friday": "11:30AM–2:30PM,4:30–11PM",
      "Hours - Saturday": "11:30AM–2:30PM,4:30–11PM",
      "Hours - Sunday": "Closed",
      "Specials - Monday": "HAPPY HOUR\nweeknights from 5 – 7 p.m.\n$1.50 OYSTERS – SHUCKER’S CHOICE\n$1 OFF ALL BEERS + $7 RED, WHITE AND ROSÉ WINESHAPPY HOUR\nweeknights from 5 – 7 p.m.\n$1.50 OYSTERS – SHUCKER’S CHOICE\n$1 OFF ALL BEERS + $7 RED, WHITE AND ROSÉ WINES",
      "Specials - Tuesday": "HAPPY HOUR\nweeknights from 5 – 7 p.m.\n$1.50 OYSTERS – SHUCKER’S CHOICE\n$1 OFF ALL BEERS + $7 RED, WHITE AND ROSÉ WINESHAPPY HOUR\nweeknights from 5 – 7 p.m.\n$1.50 OYSTERS – SHUCKER’S CHOICE\n$1 OFF ALL BEERS + $7 RED, WHITE AND ROSÉ WINES",
      "Specials - Wednesday": "HAPPY HOUR\nweeknights from 5 – 7 p.m.\n$1.50 OYSTERS – SHUCKER’S CHOICE\n$1 OFF ALL BEERS + $7 RED, WHITE AND ROSÉ WINESHAPPY HOUR\nweeknights from 5 – 7 p.m.\n$1.50 OYSTERS – SHUCKER’S CHOICE\n$1 OFF ALL BEERS + $7 RED, WHITE AND ROSÉ WINES",
      "Specials - Thursday": "HAPPY HOUR\nweeknights from 5 – 7 p.m.\n$1.50 OYSTERS – SHUCKER’S CHOICE\n$1 OFF ALL BEERS + $7 RED, WHITE AND ROSÉ WINESHAPPY HOUR\nweeknights from 5 – 7 p.m.\n$1.50 OYSTERS – SHUCKER’S CHOICE\n$1 OFF ALL BEERS + $7 RED, WHITE AND ROSÉ WINES",
      "Specials - Friday": "HAPPY HOUR\nweeknights from 5 – 7 p.m.\n$1.50 OYSTERS – SHUCKER’S CHOICE\n$1 OFF ALL BEERS + $7 RED, WHITE AND ROSÉ WINES\nFish Fry Fridays!! 4:30 -9:00\n2 for 1 Draft Beer\n$2 Oysters Raw or Oven Roasted\n$6  Rum Daiquiris\n$12 baskets of Fish & ChiosHAPPY HOUR\nweeknights from 5 – 7 p.m.\n$1.50 OYSTERS – SHUCKER’S CHOICE\n$1 OFF ALL BEERS + $7 RED, WHITE AND ROSÉ WINES\nFish Fry Fridays!! 4:30 -9:00\n2 for 1 Draft Beer\n$2 Oysters Raw or Oven Roasted\n$6  Rum Daiquiris\n$12 baskets of Fish & Chios",
      "Specials - Saturday": "",
      "Specials - Sunday": "",
      "Note": ""
    },
    {
      "Bar": "A Tavola Bar + Trattoria",
      "Description": "Neapolitan pies are wood-fired & served with antipasti & craft cocktails in an industrial-chic room.",
      "Neighborhood": "Over-the-Rhine",
      "Address": "1220 Vine St, Cincinnati, OH 45202",
      "Phone": "(513) 246-0192",
      "Website": "http://www.atavolapizza.com/",
      "Hours - Monday": "11AM–10PM",
      "Hours - Tuesday": "11AM–10PM",
      "Hours - Wednesday": "11AM–10PM",
      "Hours - Thursday": "11AM–10PM",
      "Hours - Friday": "11AM–12AM",
      "Hours - Saturday": "11AM–12AM",
      "Hours - Sunday": "12–10PM",
      "Specials - Monday": "",
      "Specials - Tuesday": "",
      "Specials - Wednesday": "",
      "Specials - Thursday": "",
      "Specials - Friday": "",
      "Specials - Saturday": "",
      "Specials - Sunday": "",
      "Note": ""
    },
    {
      "Bar": "Nation Kitchen and Bar",
      "Description": "Rustic-chic place with a large beer menu, craft cocktails, gourmet burgers & creative potato sides.",
      "Neighborhood": "Over-the-Rhine",
      "Address": "1200 Broadway St, Cincinnati, OH 45202",
      "Phone": "(513) 381-3794",
      "Website": "http://nationkitchenandbar.com/",
      "Hours - Monday": "11AM–12AM",
      "Hours - Tuesday": "11AM–12AM",
      "Hours - Wednesday": "11AM–12AM",
      "Hours - Thursday": "11AM–12AM",
      "Hours - Friday": "11AM–2AM",
      "Hours - Saturday": "10AM–2AM",
      "Hours - Sunday": "10AM–12AM",
      "Specials - Monday": "",
      "Specials - Tuesday": "",
      "Specials - Wednesday": "",
      "Specials - Thursday": "",
      "Specials - Friday": "",
      "Specials - Saturday": "",
      "Specials - Sunday": "",
      "Note": ""
    },
    {
      "Bar": "The Drinkery",
      "Description": "Unpretentious, brick-lined bar & club featuring a patio, local bands, DJs & craft beers.",
      "Neighborhood": "Over-the-Rhine",
      "Address": "1150 Main St, Cincinnati, OH 45202",
      "Phone": "(513) 509-2574",
      "Website": "http://www.drinkotr.com/",
      "Hours - Monday": "4PM–2AM",
      "Hours - Tuesday": "4PM–2AM",
      "Hours - Wednesday": "4PM–2AM",
      "Hours - Thursday": "4PM–2AM",
      "Hours - Friday": "4PM–2AM",
      "Hours - Saturday": "12PM–2AM",
      "Hours - Sunday": "12PM–2AM",
      "Specials - Monday": "",
      "Specials - Tuesday": "",
      "Specials - Wednesday": "",
      "Specials - Thursday": "",
      "Specials - Friday": "",
      "Specials - Saturday": "",
      "Specials - Sunday": "",
      "Note": ""
    },
    {
      "Bar": "Senate",
      "Description": "Trendy pub serving gourmet hot dogs with creative toppings, plus local brews & retro cocktails.",
      "Neighborhood": "Over-the-Rhine",
      "Address": "1212 Vine St, Cincinnati, OH 45202",
      "Phone": "(513) 421-2020",
      "Website": "http://www.senatepub.com/",
      "Hours - Monday": "Closed",
      "Hours - Tuesday": "11:30AM–10PM",
      "Hours - Wednesday": "11:30AM–10PM",
      "Hours - Thursday": "11:30AM–10PM",
      "Hours - Friday": "11:30AM–11PM",
      "Hours - Saturday": "11:30AM–11PM",
      "Hours - Sunday": "Closed",
      "Specials - Monday": "",
      "Specials - Tuesday": "",
      "Specials - Wednesday": "",
      "Specials - Thursday": "",
      "Specials - Friday": "",
      "Specials - Saturday": "",
      "Specials - Sunday": "",
      "Note": ""
    },
    {
      "Bar": "Mr Pitiful's",
      "Description": "Cozy neighborhood bar with diverse entertainment, including sports on TV, live music & DJs.",
      "Neighborhood": "Over-the-Rhine",
      "Address": "1323 Main St, Cincinnati, OH 45202",
      "Phone": "(513) 369-0202",
      "Website": "http://mrpitifulsotr.com/",
      "Hours - Monday": "6PM–12AM",
      "Hours - Tuesday": "5PM–12AM",
      "Hours - Wednesday": "5PM–1AM",
      "Hours - Thursday": "5PM–2AM",
      "Hours - Friday": "4PM–2AM",
      "Hours - Saturday": "5PM–12AM",
      "Hours - Sunday": "12–8PM",
      "Specials - Monday": "",
      "Specials - Tuesday": "",
      "Specials - Wednesday": "",
      "Specials - Thursday": "",
      "Specials - Friday": "",
      "Specials - Saturday": "",
      "Specials - Sunday": "",
      "Note": ""
    },
    {
      "Bar": "Vestry at the Transept",
      "Description": "",
      "Neighborhood": "Over-the-Rhine",
      "Address": "1205 Elm St, Cincinnati, OH 45202",
      "Phone": "(513) 841-9999",
      "Website": "http://vestryotr.com/",
      "Hours - Monday": "Closed",
      "Hours - Tuesday": "Closed",
      "Hours - Wednesday": "4PM–12AM",
      "Hours - Thursday": "4PM–12AM",
      "Hours - Friday": "4PM–2AM",
      "Hours - Saturday": "4PM–2AM",
      "Hours - Sunday": "Closed",
      "Specials - Monday": "HAPPY HOUR 4P-8P\n$4 CALLS, $3 DOMESTICS, $2 OFF DRAFTS, $5 GLASSES OF SPANISH WINE\nMonday: “Manhattan Mondays”\n$5 Bulleit Manhattans*HAPPY HOUR 4P-8P\n$4 CALLS, $3 DOMESTICS, $2 OFF DRAFTS, $5 GLASSES OF SPANISH WINE\nMonday: “Manhattan Mondays”\n$5 Bulleit Manhattans*",
      "Specials - Tuesday": "HAPPY HOUR 4P-8P\n$4 CALLS, $3 DOMESTICS, $2 OFF DRAFTS, $5 GLASSES OF SPANISH WINEHAPPY HOUR 4P-8P\n$4 CALLS, $3 DOMESTICS, $2 OFF DRAFTS, $5 GLASSES OF SPANISH WINE",
      "Specials - Wednesday": "HAPPY HOUR 4P-8P\n$4 CALLS, $3 DOMESTICS, $2 OFF DRAFTS, $5 GLASSES OF SPANISH WINE\nWednesday: “Wine Down Wednesdays”\n$15 Polus & Maques De Reinosa BottlesHAPPY HOUR 4P-8P\n$4 CALLS, $3 DOMESTICS, $2 OFF DRAFTS, $5 GLASSES OF SPANISH WINE\nWednesday: “Wine Down Wednesdays”\n$15 Polus & Maques De Reinosa Bottles",
      "Specials - Thursday": "HAPPY HOUR 4P-8P\n$4 CALLS, $3 DOMESTICS, $2 OFF DRAFTS, $5 GLASSES OF SPANISH WINE\nThursday: “Thirsty Thursdays”\n$4 Craft Cans\n$4 Jameson*HAPPY HOUR 4P-8P\n$4 CALLS, $3 DOMESTICS, $2 OFF DRAFTS, $5 GLASSES OF SPANISH WINE\nThursday: “Thirsty Thursdays”\n$4 Craft Cans\n$4 Jameson*",
      "Specials - Friday": "HAPPY HOUR 4P-8P\n$4 CALLS, $3 DOMESTICS, $2 OFF DRAFTS, $5 GLASSES OF SPANISH WINEHAPPY HOUR 4P-8P\n$4 CALLS, $3 DOMESTICS, $2 OFF DRAFTS, $5 GLASSES OF SPANISH WINE",
      "Specials - Saturday": "HAPPY HOUR 4P-8P\n$4 CALLS, $3 DOMESTICS, $2 OFF DRAFTS, $5 GLASSES OF SPANISH WINEHAPPY HOUR 4P-8P\n$4 CALLS, $3 DOMESTICS, $2 OFF DRAFTS, $5 GLASSES OF SPANISH WINE",
      "Specials - Sunday": "",
      "Note": ""
    },
    {
      "Bar": "Wiseguy Lounge ",
      "Description": "",
      "Neighborhood": "Over-the-Rhine",
      "Address": "1211 Main St, Cincinnati, OH 45202",
      "Phone": "(513) 381-3625",
      "Website": "http://www.goodfellaspizzeria.com/wiseguy-option-2/",
      "Hours - Monday": "11AM–1AM",
      "Hours - Tuesday": "11AM–1AM",
      "Hours - Wednesday": "11AM–1AM",
      "Hours - Thursday": "11AM–2:30AM",
      "Hours - Friday": "11AM–2:30AM",
      "Hours - Saturday": "11AM–2:30AM",
      "Hours - Sunday": "11AM–1AM",
      "Specials - Monday": "",
      "Specials - Tuesday": "",
      "Specials - Wednesday": "",
      "Specials - Thursday": "",
      "Specials - Friday": "",
      "Specials - Saturday": "",
      "Specials - Sunday": "",
      "Note": ""
    },
    {
      "Bar": "Revel OTR Urban Winery",
      "Description": "Cozy winery with live music, handcrafted wines & light snacks in rustic-chic digs with live music.",
      "Neighborhood": "Over-the-Rhine",
      "Address": "111 E 12th St, Cincinnati, OH 45202",
      "Phone": "(513) 579-9463",
      "Website": "http://www.revelotr.com/",
      "Hours - Monday": "Closed",
      "Hours - Tuesday": "4PM–12AM",
      "Hours - Wednesday": "4PM–12AM",
      "Hours - Thursday": "4PM–12AM",
      "Hours - Friday": "4PM–2AM",
      "Hours - Saturday": "12PM–2AM",
      "Hours - Sunday": "Closed",
      "Specials - Monday": "",
      "Specials - Tuesday": "",
      "Specials - Wednesday": "Happy Hour 4-7 PM\n$5 - Wine, Beer, Wine Cocktails, Olives and Cheese, Bread & OilHappy Hour 4-7 PM\n$5 - Wine, Beer, Wine Cocktails, Olives and Cheese, Bread & Oil",
      "Specials - Thursday": "Happy Hour 4-7 PM\n$5 - Wine, Beer, Wine Cocktails, Olives and Cheese, Bread & OilHappy Hour 4-7 PM\n$5 - Wine, Beer, Wine Cocktails, Olives and Cheese, Bread & Oil",
      "Specials - Friday": "Happy Hour 4-7 PM\n$5 - Wine, Beer, Wine Cocktails, Olives and Cheese, Bread & OilHappy Hour 4-7 PM\n$5 - Wine, Beer, Wine Cocktails, Olives and Cheese, Bread & Oil",
      "Specials - Saturday": "",
      "Specials - Sunday": "Sangria Sunday 12-10PM\n$7 Red & White Wine Sangrias, Traditional Mimosas, Draft Beers, $5 Limoncello Crema, $4 Limoncello ClassicSangria Sunday 12-10PM\n$7 Red & White Wine Sangrias, Traditional Mimosas, Draft Beers, $5 Limoncello Crema, $4 Limoncello Classic",
      "Note": ""
    },
    {
      "Bar": "Kaze",
      "Description": "Gastropub serving sushi & creative Japanese fare in a stylish space, with a lounge & beer garden.",
      "Neighborhood": "Over-the-Rhine",
      "Address": "1400 Vine St, Cincinnati, OH 45202",
      "Phone": "(513) 898-7991",
      "Website": "http://www.kazeotr.com/",
      "Hours - Monday": "Closed",
      "Hours - Tuesday": "4–10PM",
      "Hours - Wednesday": "4–10PM",
      "Hours - Thursday": "4–10PM",
      "Hours - Friday": "4–11PM",
      "Hours - Saturday": "12–11PM",
      "Hours - Sunday": "12–9PM",
      "Specials - Monday": "HAPPY HOUR  DAILY - 4-7PM\n   • Specialty cocktails are $5\n   • Discounted select sushi rolls\n   • Ramen is only $4.5HAPPY HOUR  DAILY - 4-7PM\n   • Specialty cocktails are $5\n   • Discounted select sushi rolls\n   • Ramen is only $4.5",
      "Specials - Tuesday": "HAPPY HOUR  DAILY - 4-7PM\n   • Specialty cocktails are $5\n   • Discounted select sushi rolls\n   • Ramen is only $4.5HAPPY HOUR  DAILY - 4-7PM\n   • Specialty cocktails are $5\n   • Discounted select sushi rolls\n   • Ramen is only $4.5",
      "Specials - Wednesday": "HAPPY HOUR  DAILY - 4-7PM\n   • Specialty cocktails are $5\n   • Discounted select sushi rolls\n   • Ramen is only $4.5HAPPY HOUR  DAILY - 4-7PM\n   • Specialty cocktails are $5\n   • Discounted select sushi rolls\n   • Ramen is only $4.5",
      "Specials - Thursday": "HAPPY HOUR  DAILY - 4-7PM\n   • Specialty cocktails are $5\n   • Discounted select sushi rolls\n   • Ramen is only $4.5HAPPY HOUR  DAILY - 4-7PM\n   • Specialty cocktails are $5\n   • Discounted select sushi rolls\n   • Ramen is only $4.5",
      "Specials - Friday": "HAPPY HOUR  DAILY - 4-7PM\n   • Specialty cocktails are $5\n   • Discounted select sushi rolls\n   • Ramen is only $4.5HAPPY HOUR  DAILY - 4-7PM\n   • Specialty cocktails are $5\n   • Discounted select sushi rolls\n   • Ramen is only $4.5",
      "Specials - Saturday": "HAPPY HOUR  DAILY - 4-6PM\n   • Specialty cocktails are $5\n   • Discounted select sushi rolls\n   • Ramen is only $4.5HAPPY HOUR  DAILY - 4-6PM\n   • Specialty cocktails are $5\n   • Discounted select sushi rolls\n   • Ramen is only $4.5",
      "Specials - Sunday": "HAPPY HOUR  DAILY - 4-6PM\n   • Specialty cocktails are $5\n   • Discounted select sushi rolls\n   • Ramen is only $4.5HAPPY HOUR  DAILY - 4-6PM\n   • Specialty cocktails are $5\n   • Discounted select sushi rolls\n   • Ramen is only $4.5",
      "Note": ""
    },
    {
      "Bar": "Ché",
      "Description": "Artisanal Argentine cuisine & empanadas, plus drinks, offered in a rustic, dimly lit dining room.",
      "Neighborhood": "Over-the-Rhine",
      "Address": "1342 Walnut St, Cincinnati, OH 45202",
      "Phone": "(513) 345-8838",
      "Website": "http://www.checincinnati.com/",
      "Hours - Monday": "4PM–12AM",
      "Hours - Tuesday": "11AM–2:30AM",
      "Hours - Wednesday": "11AM–2:30AM",
      "Hours - Thursday": "11AM–2:30AM",
      "Hours - Friday": "11AM–2:30AM",
      "Hours - Saturday": "11AM–2:30AM",
      "Hours - Sunday": "11AM–12AM",
      "Specials - Monday": "Malbec Mondays\nCome enjoy any of our Malbecs by the glass for only $5 all day long.Malbec Mondays\nCome enjoy any of our Malbecs by the glass for only $5 all day long.",
      "Specials - Tuesday": "Service Industry Night\nOur friends in the Service Industry enjoy 30% off drinks all night long!\n$3 Jack Daniels\nWhen:\nEvery Tuesday from 7pm - Close.\nService Industry Night\nOur friends in the Service Industry enjoy 30% off drinks all night long!\n$3 Jack Daniels\nWhen:\nEvery Tuesday from 7pm - Close.",
      "Specials - Wednesday": "Whiskey Wednesday $3\nGet over Hump Day by joining us for $3 shots of Jameson all evening long.Whiskey Wednesday $3\nGet over Hump Day by joining us for $3 shots of Jameson all evening long.",
      "Specials - Thursday": "Thirsty Thursday$4 Drafts\nBeer aficionados unite! Thursday at Ché means it's time for $4 drafts on any of our 20 beers on tap!Thirsty Thursday$4 Drafts\nBeer aficionados unite! Thursday at Ché means it's time for $4 drafts on any of our 20 beers on tap!",
      "Specials - Friday": "Fireball Friday\nReady to start your weekends with a bang? Pop by and joinus for $3 shots of Fireball 'till the wheels fall off!Fireball Friday\nReady to start your weekends with a bang? Pop by and joinus for $3 shots of Fireball 'till the wheels fall off!",
      "Specials - Saturday": "Weekend Brunch\n Come check in OTR's best kept secret! 10 exclusive menu items,\n\n$4 Mimosas, and $5 Bloody Marys.\nWhen:\nSaturdays and Sundays from  11am to 3pm.Weekend Brunch\n Come check in OTR's best kept secret! 10 exclusive menu items,\n\n$4 Mimosas, and $5 Bloody Marys.\nWhen:\nSaturdays and Sundays from  11am to 3pm.",
      "Specials - Sunday": "Weekend Brunch\n Come check in OTR's best kept secret! 10 exclusive menu items,\n\n$4 Mimosas, and $5 Bloody Marys.\nWhen:\nSaturdays and Sundays from  11am to 3pm.Weekend Brunch\n Come check in OTR's best kept secret! 10 exclusive menu items,\n\n$4 Mimosas, and $5 Bloody Marys.\nWhen:\nSaturdays and Sundays from  11am to 3pm.",
      "Note": ""
    },
    {
      "Bar": "The Hub",
      "Description": "",
      "Neighborhood": "Over-the-Rhine",
      "Address": "1209 Main St, Cincinnati, OH 45202",
      "Phone": "(513) 746-6572",
      "Website": "http://thehubotr.com/",
      "Hours - Monday": "4PM–2AM",
      "Hours - Tuesday": "2PM–2AM",
      "Hours - Wednesday": "2PM–2AM",
      "Hours - Thursday": "2PM–2AM",
      "Hours - Friday": "2PM–2AM",
      "Hours - Saturday": "2PM–2AM",
      "Hours - Sunday": "4PM–2AM",
      "Specials - Monday": "",
      "Specials - Tuesday": "",
      "Specials - Wednesday": "",
      "Specials - Thursday": "",
      "Specials - Friday": "",
      "Specials - Saturday": "",
      "Specials - Sunday": "",
      "Note": ""
    },
    {
      "Bar": "Four Entertainment Group",
      "Description": "",
      "Neighborhood": "Over-the-Rhine",
      "Address": "1404 Vine St, Cincinnati, OH 45202",
      "Phone": "(513) 721-0083",
      "Website": "http://www.foureg.com/",
      "Hours - Monday": "10AM–6PM",
      "Hours - Tuesday": "10AM–6PM",
      "Hours - Wednesday": "10AM–6PM",
      "Hours - Thursday": "10AM–6PM",
      "Hours - Friday": "10AM–6PM",
      "Hours - Saturday": "Closed",
      "Hours - Sunday": "Closed",
      "Specials - Monday": "",
      "Specials - Tuesday": "",
      "Specials - Wednesday": "",
      "Specials - Thursday": "",
      "Specials - Friday": "",
      "Specials - Saturday": "",
      "Specials - Sunday": "",
      "Note": ""
    },
    {
      "Bar": "The Mercer OTR",
      "Description": "Varied European-influenced dishes are served in a stylish venue at this modern restaurant.",
      "Neighborhood": "Over-the-Rhine",
      "Address": "1324 Vine St, Cincinnati, OH 45202",
      "Phone": "(513) 421-5111",
      "Website": "http://www.themercerotr.com/",
      "Hours - Monday": "Closed",
      "Hours - Tuesday": "5–10PM",
      "Hours - Wednesday": "5–10PM",
      "Hours - Thursday": "5–10PM",
      "Hours - Friday": "5–11PM",
      "Hours - Saturday": "5–11PM",
      "Hours - Sunday": "4:30–8:30PM",
      "Specials - Monday": "",
      "Specials - Tuesday": "Tuesday-Half Price Wine\nBottles of wine up through $74 are 50% off. Wines $75 and up\nand wines in half bottles are 25% off.",
      "Specials - Wednesday": "Tuesday-Half Price Wine\nBottles of wine up through $74 are 50% off. Wines $75 and up\nand wines in half bottles are 25% off.",
      "Specials - Thursday": "Thursday Bar Burger Night\n$10 Burger & Fries, $2 High Life cans, and $2 Coors drafts.\n**This promotion is only available in the bar, lounge, and patio**",
      "Specials - Friday": "Friday-Half Price Wine\nBottles of wine up through $74 are 50% off. Wines $75 and up\nand wines in half bottles are 25% off.",
      "Specials - Saturday": "",
      "Specials - Sunday": "Sunday Funday $5 All Night Happy Hour\nAll night in the bar, lounge, and patio you can enjoy $5 select\ncocktails, wines by the glass, and beer specials.",
      "Note": ""
    },
    {
      "Bar": "Pontiac BBQ",
      "Description": "Rustic-chic spot with a vintage vibe offering eclectic BBQ & classic sides, plus creative cocktails.",
      "Neighborhood": "Over-the-Rhine",
      "Address": "1403 Vine St, Cincinnati, OH 45202",
      "Phone": "(513) 579-8500",
      "Website": "http://www.pontiacbbq.com/",
      "Hours - Monday": "Closed",
      "Hours - Tuesday": "11AM–10PM",
      "Hours - Wednesday": "11AM–10PM",
      "Hours - Thursday": "11AM–10PM",
      "Hours - Friday": "11AM–11PM",
      "Hours - Saturday": "11AM–11PM",
      "Hours - Sunday": "11AM–9PM",
      "Specials - Monday": "",
      "Specials - Tuesday": "",
      "Specials - Wednesday": "",
      "Specials - Thursday": "",
      "Specials - Friday": "",
      "Specials - Saturday": "",
      "Specials - Sunday": "",
      "Note": ""
    },
    {
      "Bar": "THE FUEL LOUNGE OTR",
      "Description": "",
      "Neighborhood": "Over-the-Rhine",
      "Address": "1424 Main St, Cincinnati, OH 45202",
      "Phone": "(513) 344-6274",
      "Website": "",
      "Hours - Monday": "Closed",
      "Hours - Tuesday": "Closed",
      "Hours - Wednesday": "Closed",
      "Hours - Thursday": "9PM–1AM",
      "Hours - Friday": "9PM–1AM",
      "Hours - Saturday": "9PM–1AM",
      "Hours - Sunday": "Close",
      "Specials - Monday": "",
      "Specials - Tuesday": "",
      "Specials - Wednesday": "",
      "Specials - Thursday": "",
      "Specials - Friday": "",
      "Specials - Saturday": "",
      "Specials - Sunday": "",
      "Note": ""
    },
    {
      "Bar": "Please",
      "Description": "Upscale New American kitchen with a rotating, inventive tasting menu, plus a few à la carte options.",
      "Neighborhood": "Over-the-Rhine",
      "Address": "1405 Clay St, Cincinnati, OH 45202",
      "Phone": "(513) 405-8859",
      "Website": "http://www.pleasecincinnati.com/",
      "Hours - Monday": "Closed",
      "Hours - Tuesday": "5:30–10PM",
      "Hours - Wednesday": "5:30PM–12AM",
      "Hours - Thursday": "5:30PM–12AM",
      "Hours - Friday": "5:30PM–12AM",
      "Hours - Saturday": "5:30PM–12AM",
      "Hours - Sunday": "Closed",
      "Specials - Monday": "",
      "Specials - Tuesday": "",
      "Specials - Wednesday": "Happy Hour runs Wednesday through Friday 5:30-7:30 with cocktail, wine glass & bottle specials.",
      "Specials - Thursday": "Happy Hour runs Wednesday through Friday 5:30-7:30 with cocktail, wine glass & bottle specials.",
      "Specials - Friday": "Happy Hour runs Wednesday through Friday 5:30-7:30 with cocktail, wine glass & bottle specials.",
      "Specials - Saturday": "",
      "Specials - Sunday": "",
      "Note": ""
    },
    {
      "Bar": "The Pony",
      "Description": "",
      "Neighborhood": "Over-the-Rhine",
      "Address": "1346 Main St, Cincinnati, OH 45202",
      "Phone": "(513) 954-8415",
      "Website": "",
      "Hours - Monday": "4PM–2AM",
      "Hours - Tuesday": "4PM–2AM",
      "Hours - Wednesday": "4PM–2AM",
      "Hours - Thursday": "4PM–2AM",
      "Hours - Friday": "4PM–2AM",
      "Hours - Saturday": "12PM–2AM",
      "Hours - Sunday": "12PM–2AM",
      "Specials - Monday": "",
      "Specials - Tuesday": "",
      "Specials - Wednesday": "",
      "Specials - Thursday": "",
      "Specials - Friday": "",
      "Specials - Saturday": "",
      "Specials - Sunday": "",
      "Note": ""
    },
    {
      "Bar": "The Righteous Room",
      "Description": "Arty nightspot offering beer, wine & cocktails, VIP tables & an open-air lounge with DJ music.",
      "Neighborhood": "Over-the-Rhine",
      "Address": "641 Walnut St, Cincinnati, OH 45202",
      "Phone": "(513) 381-4408",
      "Website": "http://www.therighteousroom.com/",
      "Hours - Monday": "4PM–2:30AM",
      "Hours - Tuesday": "4PM–2:30AM",
      "Hours - Wednesday": "4PM–2:30AM",
      "Hours - Thursday": "4PM–2:30AM",
      "Hours - Friday": "4PM–2:30AM",
      "Hours - Saturday": "4PM–2:30AM",
      "Hours - Sunday": "8PM–2:30AM",
      "Specials - Monday": "EVERY DAY\nOpen – Close\n$5 Rosé (Apothic or Bellarouche)\n$5 Shots of our Infused Liquor of Month\nHAPPY HOUR\nMonday – Saturday | 4-8pm\n1/2 Off All Drinks\nMONDAY\n8pm – Close\n$5 Moscow Mules\n$5 Paris to Moscows",
      "Specials - Tuesday": "EVERY DAY\nOpen – Close\n$5 Rosé (Apothic or Bellarouche)\n$5 Shots of our Infused Liquor of Month\nHAPPY HOUR\nMonday – Saturday | 4-8pm\n1/2 Off All Drinks\nTUESDAY\n8pm – Close\n$3 Local Canned Beers\n$3 Shots of Jameson",
      "Specials - Wednesday": "EVERY DAY\nOpen – Close\n$5 Rosé (Apothic or Bellarouche)\n$5 Shots of our Infused Liquor of Month\nHAPPY HOUR\nMonday – Saturday | 4-8pm\n1/2 Off All Drinks\nWEDNESDAY\n8pm – Close\nHalf-price glasses of wine\nHalf-price bottles of wine",
      "Specials - Thursday": "EVERY DAY\nOpen – Close\n$5 Rosé (Apothic or Bellarouche)\n$5 Shots of our Infused Liquor of Month\nHAPPY HOUR\nMonday – Saturday | 4-8pm\n1/2 Off All Drinks\nTHURSDAY\n8pm – Close\n$6 Don Julio Blanco\n$7 Don Julio Reposado\n$8 Don Julio Añejo\n$15 Don Julio 1942",
      "Specials - Friday": "EVERY DAY\nOpen – Close\n$5 Rosé (Apothic or Bellarouche)\n$5 Shots of our Infused Liquor of Month\nHAPPY HOUR\nMonday – Saturday | 4-8pm\n1/2 Off All Drinks",
      "Specials - Saturday": "EVERY DAY\nOpen – Close\n$5 Rosé (Apothic or Bellarouche)\n$5 Shots of our Infused Liquor of Month\nHAPPY HOUR\nMonday – Saturday | 4-8pm\n1/2 Off All Drinks",
      "Specials - Sunday": "EVERY DAY\nOpen – Close\n$5 Rosé (Apothic or Bellarouche)\n$5 Shots of our Infused Liquor of Month\nSUNDAY\n8pm – Close\nReverse Happy Hour\nHalf-price drinks",
      "Note": ""
    },
    {
      "Bar": "Rosedale",
      "Description": "",
      "Neighborhood": "Over-the-Rhine",
      "Address": "208 E 12th St, Cincinnati, OH 45202",
      "Phone": "(513) 864-5400",
      "Website": "http://www.rosedaleotr.com/",
      "Hours - Monday": "4PM–12:30AM",
      "Hours - Tuesday": "4PM–2AM",
      "Hours - Wednesday": "4PM–2AM",
      "Hours - Thursday": "4PM–2AM",
      "Hours - Friday": "4PM–2AM",
      "Hours - Saturday": "4PM–2AM",
      "Hours - Sunday": "4PM–12:30AM",
      "Specials - Monday": "Monday – Friday: 4pm – 7pm\nHalf Price Drinks (excluding house cocktails and bottles of wine)",
      "Specials - Tuesday": "Monday – Friday: 4pm – 7pm\nHalf Price Drinks (excluding house cocktails and bottles of wine)",
      "Specials - Wednesday": "Monday – Friday: 4pm – 7pm\nHalf Price Drinks (excluding house cocktails and bottles of wine)",
      "Specials - Thursday": "Monday – Friday: 4pm – 7pm\nHalf Price Drinks (excluding house cocktails and bottles of wine)",
      "Specials - Friday": "Monday – Friday: 4pm – 7pm\nHalf Price Drinks (excluding house cocktails and bottles of wine)",
      "Specials - Saturday": "",
      "Specials - Sunday": "",
      "Note": ""
    },
    {
      "Bar": "Miltons The Prospect Hill Tavern",
      "Description": "",
      "Neighborhood": "Over-the-Rhine",
      "Address": "301 Milton St, Cincinnati, OH 45202",
      "Phone": "(513) 784-9938",
      "Website": "",
      "Hours - Monday": "4PM–2:30AM",
      "Hours - Tuesday": "4PM–2:30AM",
      "Hours - Wednesday": "4PM–2:30AM",
      "Hours - Thursday": "4PM–2:30AM",
      "Hours - Friday": "4PM–2:30AM",
      "Hours - Saturday": "4PM–2:30AM",
      "Hours - Sunday": "4PM–2:30AM",
      "Specials - Monday": "",
      "Specials - Tuesday": "",
      "Specials - Wednesday": "",
      "Specials - Thursday": "",
      "Specials - Friday": "",
      "Specials - Saturday": "",
      "Specials - Sunday": "",
      "Note": ""
    },
    {
      "Bar": "Queen City Exchange",
      "Description": "",
      "Neighborhood": "Over-the-Rhine",
      "Address": "32 W Court St, Cincinnati, OH 45202",
      "Phone": "(513) 954-0395",
      "Website": "http://www.queencityexchange.com/",
      "Hours - Monday": "4–10PM",
      "Hours - Tuesday": "4–11PM",
      "Hours - Wednesday": "4–11PM",
      "Hours - Thursday": "4PM–12AM",
      "Hours - Friday": "3PM–2AM",
      "Hours - Saturday": "12PM–2AM",
      "Hours - Sunday": "12–10PM",
      "Specials - Monday": "",
      "Specials - Tuesday": "",
      "Specials - Wednesday": "",
      "Specials - Thursday": "",
      "Specials - Friday": "",
      "Specials - Saturday": "",
      "Specials - Sunday": "",
      "Note": ""
    },
    {
      "Bar": "Race Inn",
      "Description": "",
      "Neighborhood": "Over-the-Rhine",
      "Address": "1606 Race St, Cincinnati, OH 45202",
      "Phone": "(513) 421-2722",
      "Website": "",
      "Hours - Monday": "1–8PM",
      "Hours - Tuesday": "1–8PM",
      "Hours - Wednesday": "1–8PM",
      "Hours - Thursday": "1–8PM",
      "Hours - Friday": "1–8PM",
      "Hours - Saturday": "1–8PM",
      "Hours - Sunday": "1–8PM",
      "Specials - Monday": "",
      "Specials - Tuesday": "",
      "Specials - Wednesday": "",
      "Specials - Thursday": "",
      "Specials - Friday": "",
      "Specials - Saturday": "",
      "Specials - Sunday": "",
      "Note": ""
    },
    {
      "Bar": "Mt. Adams Pavilion",
      "Description": "Live bands & DJs perform at this hip dance club in a historic house with 4 decks & city views.",
      "Neighborhood": "Over-the-Rhine",
      "Address": "949 Pavilion St, Cincinnati, OH 45202",
      "Phone": "(513) 744-9200",
      "Website": "http://www.mountadamspavilion.com/",
      "Hours - Monday": "Closed",
      "Hours - Tuesday": "Closed",
      "Hours - Wednesday": "6PM–2:30AM",
      "Hours - Thursday": "6PM–2:30AM",
      "Hours - Friday": "6PM–2:30AM",
      "Hours - Saturday": "6PM–2:30AM",
      "Hours - Sunday": "Closed",
      "Specials - Monday": "",
      "Specials - Tuesday": "",
      "Specials - Wednesday": "HAPPY HOUR\nWed – Fri, 6pm – 8pm\n$2.50 Domestics*\n$3 Imports*\n$5 Margaritas (frozen or rocks)\nWEDNESDAY\n6pm – 9pm\nExtended Happy Hour\n\n10pm – Close (Employee Discount Night)\n$2 off all drinks!",
      "Specials - Thursday": "HAPPY HOUR\nWed – Fri, 6pm – 8pm\n$2.50 Domestics*\n$3 Imports*\n$5 Margaritas (frozen or rocks)\nTHURSDAY\nAfter 9pm\n$2 Bud Light Aluminum Bottles\n$3 Margaritas\n$4 Long Islands\n$4 Fireball Whisky",
      "Specials - Friday": "HAPPY HOUR\nWed – Fri, 6pm – 8pm\n$2.50 Domestics*\n$3 Imports*\n$5 Margaritas (frozen or rocks)",
      "Specials - Saturday": "",
      "Specials - Sunday": "",
      "Note": ""
    },
    {
      "Bar": "Symphony Hotel Jazz Lounge",
      "Description": "",
      "Neighborhood": "Over-the-Rhine",
      "Address": "210 W 14th St, Cincinnati, OH 45202",
      "Phone": "(513) 721-3353",
      "Website": "http://www.symphonyhotel.com/jazz-bar/",
      "Hours - Monday": "Closed",
      "Hours - Tuesday": "Closed",
      "Hours - Wednesday": "Closed",
      "Hours - Thursday": "7–10PM",
      "Hours - Friday": "8–11PM",
      "Hours - Saturday": "8–11PM",
      "Hours - Sunday": "Closed",
      "Specials - Monday": "",
      "Specials - Tuesday": "",
      "Specials - Wednesday": "",
      "Specials - Thursday": "",
      "Specials - Friday": "",
      "Specials - Saturday": "",
      "Specials - Sunday": "",
      "Note": ""
    },
    {
      "Bar": "Maplewood Kitchen and Bar",
      "Description": "Spacious cafe for Californian cuisine for breakfast through dinner amid wooden tables & greenery.",
      "Neighborhood": "Over-the-Rhine",
      "Address": "525 Race St, Cincinnati, OH 45202",
      "Phone": "(513) 421-2100",
      "Website": "http://www.maplewoodkitchenandbar.com/",
      "Hours - Monday": "7AM–9PM",
      "Hours - Tuesday": "7AM–9PM",
      "Hours - Wednesday": "7AM–9PM",
      "Hours - Thursday": "7AM–9PM",
      "Hours - Friday": "7AM–10PM",
      "Hours - Saturday": "8AM–10PM",
      "Hours - Sunday": "8AM–9PM",
      "Specials - Monday": "",
      "Specials - Tuesday": "",
      "Specials - Wednesday": "",
      "Specials - Thursday": "",
      "Specials - Friday": "",
      "Specials - Saturday": "",
      "Specials - Sunday": "",
      "Note": ""
    },
    {
      "Bar": "OTR LIVE",
      "Description": "",
      "Neighborhood": "Over-the-Rhine",
      "Address": "209 E 12th St, Cincinnati, OH 45202",
      "Phone": "(513) 421-5483",
      "Website": "http://otrlivemusic.com/",
      "Hours - Monday": "9AM–4AM",
      "Hours - Tuesday": "9AM–4AM",
      "Hours - Wednesday": "9AM–4AM",
      "Hours - Thursday": "9AM–4AM",
      "Hours - Friday": "9AM–4AM",
      "Hours - Saturday": "9AM–4AM",
      "Hours - Sunday": "9AM–4AM",
      "Specials - Monday": "",
      "Specials - Tuesday": "",
      "Specials - Wednesday": "",
      "Specials - Thursday": "",
      "Specials - Friday": "",
      "Specials - Saturday": "",
      "Specials - Sunday": "",
      "Note": ""
    },
    {
      "Bar": "Igby's",
      "Description": "Expansive, multifloor lounge with wood-planked walls, craft cocktails, small plates & a hip vibe.",
      "Neighborhood": "Over-the-Rhine",
      "Address": "122 E 6th St, Cincinnati, OH 45202",
      "Phone": "(513) 246-4396",
      "Website": "http://igbysbar.com/",
      "Hours - Monday": "4PM–12AM",
      "Hours - Tuesday": "4PM–12AM",
      "Hours - Wednesday": "4PM–12AM",
      "Hours - Thursday": "4PM–12AM",
      "Hours - Friday": "4PM–12AM",
      "Hours - Saturday": "4PM–12AM",
      "Hours - Sunday": "Closed",
      "Specials - Monday": "HAPPY HOUR\nMonday – Friday 4pm – 8pm\nSaturday 4pm – 6pm\n$5 Drafts\n$5 Select Calls\n$5 Glasses of Dark Horse Wine\nMONDAY\n8pm – Close\nHalf-price all wine & $15 charcuterie board\n*Rare exclusions apply",
      "Specials - Tuesday": "HAPPY HOUR\nMonday – Friday 4pm – 8pm\nSaturday 4pm – 6pm\n$5 Drafts\n$5 Select Calls\n$5 Glasses of Dark Horse Wine\nTUESDAY\n8pm – Close\n$3 off all craft cocktails",
      "Specials - Wednesday": "HAPPY HOUR\nMonday – Friday 4pm – 8pm\nSaturday 4pm – 6pm\n$5 Drafts\n$5 Select Calls\n$5 Glasses of Dark Horse Wine\nWEDNESDAY\n8pm – Close\n$3 beers (drafts, bottles, & cans) & $3 wells\n*Rare exclusions apply",
      "Specials - Thursday": "HAPPY HOUR\nMonday – Friday 4pm – 8pm\nSaturday 4pm – 6pm\n$5 Drafts\n$5 Select Calls\n$5 Glasses of Dark Horse Wine\nTHURSDAY\n8pm – Close\n$3 off all tequila & “Kill the Keg”\nFinish off the last of our designated keg and receive a $25 gift card!",
      "Specials - Friday": "HAPPY HOUR\nMonday – Friday 4pm – 8pm\nSaturday 4pm – 6pm\n$5 Drafts\n$5 Select Calls\n$5 Glasses of Dark Horse Wine\nFRIDAY\n8pm – Close\n$100 bottle service bottles\n(Tito’s Handmade Vodka, El Jimador Tequila, Tanqueray Gin, Old Forester Whiskey, & Captain Morgan White Rum)",
      "Specials - Saturday": "",
      "Specials - Sunday": "",
      "Note": ""
    },
    {
      "Bar": "Shooks - Bar & Dance",
      "Description": "",
      "Neighborhood": "Over-the-Rhine",
      "Address": "920 Race St, Cincinnati, OH 45202",
      "Phone": "(513) 600-0990",
      "Website": "https://m.facebook.com/Shooks920/",
      "Hours - Monday": "Closed",
      "Hours - Tuesday": "Closed",
      "Hours - Wednesday": "Closed",
      "Hours - Thursday": "8PM–2:30AM",
      "Hours - Friday": "8PM–2:30AM",
      "Hours - Saturday": "8PM–2:30AM",
      "Hours - Sunday": "Closed",
      "Specials - Monday": "",
      "Specials - Tuesday": "",
      "Specials - Wednesday": "",
      "Specials - Thursday": "",
      "Specials - Friday": "",
      "Specials - Saturday": "",
      "Specials - Sunday": "",
      "Note": ""
    },
    {
      "Bar": "Knockback Nats",
      "Description": "Easygoing game-day hangout with a long bar, typical pub fare & shuffleboard, plus a small patio.",
      "Neighborhood": "Over-the-Rhine",
      "Address": "10 W 7th St, Cincinnati, OH 45202",
      "Phone": "(513) 621-1000",
      "Website": "https://www.facebook.com/Knockback-Nats-Neighborhood-Bar-146296676362/",
      "Hours - Monday": "2PM–2AM",
      "Hours - Tuesday": "2PM–2AM",
      "Hours - Wednesday": "2PM–2AM",
      "Hours - Thursday": "2PM–2AM",
      "Hours - Friday": "2PM–2AM",
      "Hours - Saturday": "12PM–2AM",
      "Hours - Sunday": "12PM–2AM",
      "Specials - Monday": "",
      "Specials - Tuesday": "",
      "Specials - Wednesday": "",
      "Specials - Thursday": "",
      "Specials - Friday": "",
      "Specials - Saturday": "",
      "Specials - Sunday": "",
      "Note": ""
    },
    {
      "Bar": "Nicholson's Tavern & Pub",
      "Description": "Men in kilts serve a Scottish-American gastropub menu with beer & brown spirits plus live music.",
      "Neighborhood": "Over-the-Rhine",
      "Address": "625 Walnut St, Cincinnati, OH 45202",
      "Phone": "(513) 564-9111",
      "Website": "http://www.nicholsonspub.com/",
      "Hours - Monday": "11AM–11PM",
      "Hours - Tuesday": "11AM–11PM",
      "Hours - Wednesday": "11AM–11PM",
      "Hours - Thursday": "11AM–11PM",
      "Hours - Friday": "11AM–1AM",
      "Hours - Saturday": "11AM–1AM",
      "Hours - Sunday": "11AM–9PM",
      "Specials - Monday": "",
      "Specials - Tuesday": "",
      "Specials - Wednesday": "",
      "Specials - Thursday": "",
      "Specials - Friday": "",
      "Specials - Saturday": "",
      "Specials - Sunday": "",
      "Note": ""
    },
    {
      "Bar": "Corkopolis",
      "Description": "",
      "Neighborhood": "Over-the-Rhine",
      "Address": "640 Main St, Cincinnati, OH 45202",
      "Phone": "(513) 381-3752",
      "Website": "http://www.corkopolis.com/",
      "Hours - Monday": "11AM–10PM",
      "Hours - Tuesday": "11AM–10PM",
      "Hours - Wednesday": "11AM–10PM",
      "Hours - Thursday": "11AM–10PM",
      "Hours - Friday": "11AM–11PM",
      "Hours - Saturday": "11AM–11PM",
      "Hours - Sunday": "Closed",
      "Specials - Monday": "",
      "Specials - Tuesday": "",
      "Specials - Wednesday": "",
      "Specials - Thursday": "",
      "Specials - Friday": "",
      "Specials - Saturday": "",
      "Specials - Sunday": "",
      "Note": ""
    },
    {
      "Bar": "Metropole",
      "Description": "Chic American outfit serving seasonal, fireplace-cooked cuisine & cocktails in the 21c Museum Hotel.",
      "Neighborhood": "Over-the-Rhine",
      "Address": "609 Walnut St, Cincinnati, OH 45202",
      "Phone": "(513) 578-6660",
      "Website": "http://metropoleonwalnut.com/",
      "Hours - Monday": "7AM–10PM",
      "Hours - Tuesday": "7AM–10PM",
      "Hours - Wednesday": "7AM–10PM",
      "Hours - Thursday": "7AM–10PM",
      "Hours - Friday": "7AM–11PM",
      "Hours - Saturday": "7AM–11PM",
      "Hours - Sunday": "7AM–10PM",
      "Specials - Monday": "",
      "Specials - Tuesday": "",
      "Specials - Wednesday": "",
      "Specials - Thursday": "",
      "Specials - Friday": "",
      "Specials - Saturday": "",
      "Specials - Sunday": "",
      "Note": ""
    },
    {
      "Bar": "The Blind Lemon",
      "Description": "Whimsical bar, named after bluesman Blind Lemon Jefferson, with live music & lots of cocktails.",
      "Neighborhood": "Over-the-Rhine",
      "Address": "936 Hatch St, Cincinnati, OH 45202",
      "Phone": "(513) 241-3885",
      "Website": "http://www.theblindlemon.com/",
      "Hours - Monday": "5:30PM–2:30AM",
      "Hours - Tuesday": "5:30PM–2:30AM",
      "Hours - Wednesday": "5:30PM–2:30AM",
      "Hours - Thursday": "5:30PM–2:30AM",
      "Hours - Friday": "5:30PM–2:30AM",
      "Hours - Saturday": "3PM–2:30AM",
      "Hours - Sunday": "3PM–2:30AM",
      "Specials - Monday": "",
      "Specials - Tuesday": "",
      "Specials - Wednesday": "",
      "Specials - Thursday": "",
      "Specials - Friday": "",
      "Specials - Saturday": "",
      "Specials - Sunday": "",
      "Note": ""
    },
    {
      "Bar": "Scene Ultra Lounge",
      "Description": "Boisterous nightspot with craft beers, cocktails, DJs, a dance floor & TVs for sports fans.",
      "Neighborhood": "Over-the-Rhine",
      "Address": "637 Walnut St, Cincinnati, OH 45202",
      "Phone": "(513) 381-4327",
      "Website": "http://www.scenecinci.com/",
      "Hours - Monday": "Closed",
      "Hours - Tuesday": "4PM–2AM",
      "Hours - Wednesday": "4PM–2AM",
      "Hours - Thursday": "4PM–2AM",
      "Hours - Friday": "4PM–2AM",
      "Hours - Saturday": "4PM–2AM",
      "Hours - Sunday": "Closed",
      "Specials - Monday": "Half Price Happy Hour 4-8PM",
      "Specials - Tuesday": "Half Price Happy Hour 4-8PM",
      "Specials - Wednesday": "Half Price Happy Hour 4-8PM",
      "Specials - Thursday": "Half Price Happy Hour 4-8PM",
      "Specials - Friday": "Half Price Happy Hour 4-8PM",
      "Specials - Saturday": "Half Price Happy Hour 4-8PM",
      "Specials - Sunday": "Half Price Happy Hour 4-8PM",
      "Note": ""
    },
    {
      "Bar": "Tokyo Kitty",
      "Description": "",
      "Neighborhood": "Over-the-Rhine",
      "Address": "575 Race St, Cincinnati, OH 45202",
      "Phone": "(513) 744-0909",
      "Website": "http://thattokyobar.com/",
      "Hours - Monday": "5PM–2AM",
      "Hours - Tuesday": "5PM–2AM",
      "Hours - Wednesday": "5PM–2AM",
      "Hours - Thursday": "5PM–2AM",
      "Hours - Friday": "5PM–2AM",
      "Hours - Saturday": "5PM–2AM",
      "Hours - Sunday": "5PM–2AM",
      "Specials - Monday": "",
      "Specials - Tuesday": "",
      "Specials - Wednesday": "",
      "Specials - Thursday": "",
      "Specials - Friday": "",
      "Specials - Saturday": "",
      "Specials - Sunday": "",
      "Note": ""
    },
    {
      "Bar": "The Cricket Lounge",
      "Description": "Cincinnatian Hotel lounge for American eats, cocktails & a daily happy hour in relaxed environs.",
      "Neighborhood": "Over-the-Rhine",
      "Address": "601 Vine St, Cincinnati, OH 45202",
      "Phone": "(513) 381-3000",
      "Website": "http://www.cincinnatianhotel.com/dining_cricketlounge.aspx",
      "Hours - Monday": "11:30AM–1AM",
      "Hours - Tuesday": "11:30AM–1AM",
      "Hours - Wednesday": "11:30AM–1AM",
      "Hours - Thursday": "11:30AM–1AM",
      "Hours - Friday": "11:30AM–1AM",
      "Hours - Saturday": "11:30AM–1AM",
      "Hours - Sunday": "11:30AM–1AM",
      "Specials - Monday": "",
      "Specials - Tuesday": "",
      "Specials - Wednesday": "",
      "Specials - Thursday": "",
      "Specials - Friday": "",
      "Specials - Saturday": "",
      "Specials - Sunday": "",
      "Note": ""
    },
    {
      "Bar": "Top of the Park at The Phelps",
      "Description": "Open-air lounge atop the Marriott Residence Inn, with cocktails, light bites & sweeping city views.",
      "Neighborhood": "Over-the-Rhine",
      "Address": "506 E 4th St, Cincinnati, OH 45202",
      "Phone": "(513) 651-1234",
      "Website": "http://www.topoftheparkcincinnati.com/",
      "Hours - Monday": "5–10PM",
      "Hours - Tuesday": "5–10PM",
      "Hours - Wednesday": "5–10PM",
      "Hours - Thursday": "5–10PM",
      "Hours - Friday": "4–11PM",
      "Hours - Saturday": "4–11PM",
      "Hours - Sunday": "Closed",
      "Specials - Monday": "",
      "Specials - Tuesday": "",
      "Specials - Wednesday": "",
      "Specials - Thursday": "",
      "Specials - Friday": "",
      "Specials - Saturday": "",
      "Specials - Sunday": "",
      "Note": ""
    },
    {
      "Bar": "Hightail",
      "Description": "",
      "Neighborhood": "Over-the-Rhine",
      "Address": "941 Pavilion St, Cincinnati, OH 45202",
      "Phone": "(513) 229-9980",
      "Website": "http://www.hightailmtadams.com/",
      "Hours - Monday": "Closed",
      "Hours - Tuesday": "4PM–2:30AM",
      "Hours - Wednesday": "4PM–2:30AM",
      "Hours - Thursday": "4PM–2:30AM",
      "Hours - Friday": "3PM–2:30AM",
      "Hours - Saturday": "4PM–2:30AM",
      "Hours - Sunday": "4PM–12AM",
      "Specials - Monday": "",
      "Specials - Tuesday": "Tues – Thurs\n4PM – 6PM\nFriday\n3PM – 6PM\nHalf-price drinks\n(excluding wine)",
      "Specials - Wednesday": "Tues – Thurs\n4PM – 6PM\nFriday\n3PM – 6PM\nHalf-price drinks\n(excluding wine)",
      "Specials - Thursday": "Tues – Thurs\n4PM – 6PM\nFriday\n3PM – 6PM\nHalf-price drinks\n(excluding wine)\nDecked Out\nEvery Thursday\n$2 off drafts\n$5 bombs\nCard games available",
      "Specials - Friday": "Every Sunday\n7PM – 9PM\nDog-friendly yappy hour. Half-price drinks and dog treats / swag available while supplies last.",
      "Specials - Saturday": "",
      "Specials - Sunday": "",
      "Note": ""
    },
    {
      "Bar": "Holy Grail Tavern & Grille",
      "Description": "Large sports bar by Great American Ball Park with 30+ TVs & a menu of burgers, pizza & sandwiches.",
      "Neighborhood": "Banks",
      "Address": "161 Joe Nuxhall Way, Cincinnati, OH 45202",
      "Phone": "(513) 621-2222",
      "Website": "http://www.holygrailcincy.com/html/banks/banks.php",
      "Hours - Monday": "11AM–2:30AM",
      "Hours - Tuesday": "11AM–2:30AM",
      "Hours - Wednesday": "11AM–2:30AM",
      "Hours - Thursday": "11AM–2:30AM",
      "Hours - Friday": "11AM–2:30AM",
      "Hours - Saturday": "11AM–2:30AM",
      "Hours - Sunday": "11AM–2:30AM",
      "Specials - Monday": "",
      "Specials - Tuesday": "",
      "Specials - Wednesday": "",
      "Specials - Thursday": "",
      "Specials - Friday": "",
      "Specials - Saturday": "",
      "Specials - Sunday": "",
      "Note": " All UC and Xavier televised basketball games 5 for $10 domestic buckets"
    },
    {
      "Bar": "The Stretch",
      "Description": "",
      "Neighborhood": "Banks",
      "Address": "191 E Freedom Way, Cincinnati, OH 45202",
      "Phone": "(513) 229-9065",
      "Website": "http://www.thestretchcincy.com/",
      "Hours - Monday": "3PM–2:30AM",
      "Hours - Tuesday": "3PM–2:30AM",
      "Hours - Wednesday": "3PM–2:30AM",
      "Hours - Thursday": "3PM–2:30AM",
      "Hours - Friday": "3PM–2:30AM",
      "Hours - Saturday": "3PM–2:30AM",
      "Hours - Sunday": "3PM–2:30AM",
      "Specials - Monday": "Happy Hour\n(Monday – Friday from 3pm – 7pm)\n1/2 off all drafts (includes beer, wine, and cocktails) and $2 off select calls\nMondays\nHalf-price draft cocktails",
      "Specials - Tuesday": "Happy Hour\n(Monday – Friday from 3pm – 7pm)\n1/2 off all drafts (includes beer, wine, and cocktails) and $2 off select calls",
      "Specials - Wednesday": "Happy Hour\n(Monday – Friday from 3pm – 7pm)\n1/2 off all drafts (includes beer, wine, and cocktails) and $2 off select calls",
      "Specials - Thursday": "Happy Hour\n(Monday – Friday from 3pm – 7pm)\n1/2 off all drafts (includes beer, wine, and cocktails) and $2 off select calls",
      "Specials - Friday": "Happy Hour\n(Monday – Friday from 3pm – 7pm)\n1/2 off all drafts (includes beer, wine, and cocktails) and $2 off select calls",
      "Specials - Saturday": "",
      "Specials - Sunday": "Sunday Fundays\nAfter 6PM\n$4 drafts\n$4 bombs\n$4 Rumpleminze\n$4 Fireball",
      "Note": ""
    },
    {
      "Bar": "Tin Roof",
      "Description": "Unpretentious shotgun shack bar & music venue with creative takes on American pub food.",
      "Neighborhood": "Banks",
      "Address": "160 E Freedom Way #150, Cincinnati, OH 45202",
      "Phone": "(513) 381-2176",
      "Website": "http://tinroofcincinnati.com/",
      "Hours - Monday": "11AM–3AM",
      "Hours - Tuesday": "11AM–3AM",
      "Hours - Wednesday": "11AM–3AM",
      "Hours - Thursday": "11AM–3AM",
      "Hours - Friday": "11AM–3AM",
      "Hours - Saturday": "11AM–3AM",
      "Hours - Sunday": "11AM–3AM",
      "Specials - Monday": "Monday:  $1 Local Beers\nHAPPY HOUR\nMonday - Friday  2PM - 7PM\n$2 Domestic Drafts\n$3 Import Drafts\n$3.5 Locals Draft \n$3 Wells\n$2 off House Wines",
      "Specials - Tuesday": "Tuesday:  50% off for Industry $3 DosXX 16oz Cans \nHAPPY HOUR\nMonday - Friday  2PM - 7PM\n$2 Domestic Drafts\n$3 Import Drafts\n$3.5 Locals Draft \n$3 Wells\n$2 off House Wines",
      "Specials - Wednesday": "Wednesday: $5 Domestic 32 Oz Drafts\nHAPPY HOUR\nMonday - Friday  2PM - 7PM\n$2 Domestic Drafts\n$3 Import Drafts\n$3.5 Locals Draft \n$3 Wells\n$2 off House Wines",
      "Specials - Thursday": "Thursday: $3 Wells, $3 Fireball all night \nHAPPY HOUR\nMonday - Friday  2PM - 7PM\n$2 Domestic Drafts\n$3 Import Drafts\n$3.5 Locals Draft \n$3 Wells\n$2 off House Wines",
      "Specials - Friday": "Friday:  $3 PBR Tall Boys, $4 House Shots \nHAPPY HOUR\nMonday - Friday  2PM - 7PM\n$2 Domestic Drafts\n$3 Import Drafts\n$3.5 Locals Draft \n$3 Wells\n$2 off House Wines",
      "Specials - Saturday": "Saturday:  5 for $15 Bud Light Buckets till 5pm, $3 PBR Tall Boys, $4 House Shots",
      "Specials - Sunday": "Sunday:  $15 Bottomles Mimosas,  $5 Bloody Mary's",
      "Note": ""
    },
    {
      "Bar": "O'Malleys In the Alley",
      "Description": "Long-standing Irish pub offering sports on TV & classic bar fare such as burgers & sandwiches.",
      "Neighborhood": "Banks",
      "Address": "25 W Ogden Pl, Cincinnati, OH 45202",
      "Phone": "(513) 381-3114",
      "Website": "http://www.omalleyscincy.com/",
      "Hours - Monday": "11AM–2AM",
      "Hours - Tuesday": "11AM–2AM",
      "Hours - Wednesday": "11AM–2AM",
      "Hours - Thursday": "11AM–2AM",
      "Hours - Friday": "11AM–2AM",
      "Hours - Saturday": "11AM–2AM",
      "Hours - Sunday": "11AM–2AM",
      "Specials - Monday": "ABSOLUTELY MONDAY\nLooking for a way to bounce back from a long Monday at work? Come enjoy $4 Absolut drinks any way ya want ’em all day long. Service industry professionals enjoy 30% off drinks from 3 pm to close.",
      "Specials - Tuesday": "TORCHED TUESDAYS\nLooking to light up your night? We’ve got the “hot” ticket right here, with $2 shots of Fireball all night long.",
      "Specials - Wednesday": "WHISKEY WEDNESDAY\nGet over the hump with specials like $2 Jameson shots or $3 Guinness pints, or put that pinky out and enjoy a glass of any house vino for only $3!",
      "Specials - Thursday": "CRAFT CAN THURSDAY\nCome get Crafty with us on Thursdays, when all craft cans are only $3 all day long. Snag a shot of Jagermeister for $3 or make it a Bomb for only $5.",
      "Specials - Friday": "BOMBS AWAY! FRIDAY\nWhat better way to tackle the weekend head-on than slamming down $3 Vegas Bombs from 3 pm to close? Nothing coming to mind? We didn’t think so. Get in here, already!",
      "Specials - Saturday": "CAR BOMB CHAOS SATURDAY\nThe weekend is in full swing, so let’s blow it up with $5 Car Bombs all day long.",
      "Specials - Sunday": "SERVICE INDUSTRY SUNDAY\nService Industry friends enjoy 30% off drinks all day. We also feature Clark’s Famous Furknocker Bloody Marys for $4. Snag a pitcher of draft beer for only $10.50 All. Day. Long.",
      "Note": ""
    },
    {
      "Bar": "Moerlein Lager House",
      "Description": "Artifact-adorned beer bar with New American fare & river views from a wraparound patio.",
      "Neighborhood": "Banks",
      "Address": "115 Joe Nuxhall Way, Cincinnati, OH 45202",
      "Phone": "(513) 421-2337",
      "Website": "http://www.moerleinlagerhouse.com/",
      "Hours - Monday": "11AM–12AM",
      "Hours - Tuesday": "11AM–12AM",
      "Hours - Wednesday": "11AM–12AM",
      "Hours - Thursday": "11AM–12AM",
      "Hours - Friday": "11AM–1AM",
      "Hours - Saturday": "11AM–1AM",
      "Hours - Sunday": "11AM–11PM",
      "Specials - Monday": "",
      "Specials - Tuesday": "",
      "Specials - Wednesday": "",
      "Specials - Thursday": "",
      "Specials - Friday": "",
      "Specials - Saturday": "",
      "Specials - Sunday": "",
      "Note": ""
    },
    {
      "Bar": "JerZees Pub & Grub",
      "Description": "Hangout serving bar fare & drinks in a space with several TVs, patio seating & frequent live music.",
      "Neighborhood": "Oakley",
      "Address": "708 Monmouth St, Newport, KY 41071",
      "Phone": "(859) 491-3500",
      "Website": "http://jerzeespub.com/",
      "Hours - Monday": "11AM–2AM",
      "Hours - Tuesday": "11AM–2AM",
      "Hours - Wednesday": "11AM–2AM",
      "Hours - Thursday": "11AM–2AM",
      "Hours - Friday": "11AM–2AM",
      "Hours - Saturday": "11AM–2AM",
      "Hours - Sunday": "11AM–2AM",
      "Specials - Monday": "",
      "Specials - Tuesday": "",
      "Specials - Wednesday": "",
      "Specials - Thursday": "",
      "Specials - Friday": "",
      "Specials - Saturday": "",
      "Specials - Sunday": "",
      "Note": ""
    },
    {
      "Bar": "Oakley Pub & Grill",
      "Description": "This cozy, casual pub with a heated patio serves American food with creative twists.",
      "Neighborhood": "Oakley",
      "Address": "3924 Isabella Ave, Cincinnati, OH 45209",
      "Phone": "(513) 531-2500",
      "Website": "http://oakleypubandgrill.com/",
      "Hours - Monday": "11AM–12AM",
      "Hours - Tuesday": "11AM–12AM",
      "Hours - Wednesday": "11AM–12AM",
      "Hours - Thursday": "11AM–2:30AM",
      "Hours - Friday": "11AM–2:30AM",
      "Hours - Saturday": "11:30AM–2:30AM",
      "Hours - Sunday": "11:30AM–12AM",
      "Specials - Monday": "69 cent wings Dine-In Only\nHappy Hour Food & Drink Specials 3-6PM & 9PM - Close",
      "Specials - Tuesday": "7.95 Buffalo Chicken Wrap\nHappy Hour Food & Drink Specials 3-6PM & 9PM - Close",
      "Specials - Wednesday": "7.95 Burger Mania\nHappy Hour Food & Drink Specials 3-6PM & 9PM - Close",
      "Specials - Thursday": "8.95 Pulled Pork BBQ\nHappy Hour Food & Drink Specials 3-6PM & 9PM - Close",
      "Specials - Friday": "7.95 Fish Fillet & Fish Tacos\nHappy Hour Food & Drink Specials 3-6PM & 9PM - Close",
      "Specials - Saturday": "Chef's Special\nHappy Hour Food & Drink Specials 3-6PM & 9PM - Close",
      "Specials - Sunday": "Chef's Special\nHappy Hour Food & Drink Specials 3-6PM & 9PM - Close",
      "Note": ""
    },
    {
      "Bar": "Oak Tavern",
      "Description": "Unpretentious sports bar with patio seating & multiple TVs, plus a menu of wings & other pub fare.",
      "Neighborhood": "Oakley",
      "Address": "3089 Madison Rd, Cincinnati, OH 45209",
      "Phone": "(513) 321-6258",
      "Website": "http://www.oaktavernoakley.com/",
      "Hours - Monday": "11AM–11PM",
      "Hours - Tuesday": "11AM–11PM",
      "Hours - Wednesday": "11AM–11PM",
      "Hours - Thursday": "11AM–11PM",
      "Hours - Friday": "11AM–12AM",
      "Hours - Saturday": "11AM–12AM",
      "Hours - Sunday": "11AM–11PM",
      "Specials - Monday": "",
      "Specials - Tuesday": "",
      "Specials - Wednesday": "",
      "Specials - Thursday": "",
      "Specials - Friday": "",
      "Specials - Saturday": "",
      "Specials - Sunday": "",
      "Note": ""
    },
    {
      "Bar": "Slammer's Lounge",
      "Description": "",
      "Neighborhood": "Oakley",
      "Address": "3239 Brotherton Rd, Cincinnati, OH 45209",
      "Phone": "(513) 871-6847",
      "Website": "",
      "Hours - Monday": "11AM–2:30AM",
      "Hours - Tuesday": "11AM–2:30AM",
      "Hours - Wednesday": "11AM–2:30AM",
      "Hours - Thursday": "11AM–2:30AM",
      "Hours - Friday": "11AM–2:30AM",
      "Hours - Saturday": "11AM–2:30AM",
      "Hours - Sunday": "12PM–2:30AM",
      "Specials - Monday": "",
      "Specials - Tuesday": "",
      "Specials - Wednesday": "",
      "Specials - Thursday": "",
      "Specials - Friday": "",
      "Specials - Saturday": "",
      "Specials - Sunday": "",
      "Note": ""
    },
    {
      "Bar": "Habits Café",
      "Description": "Hangout for American eats, craft brews & wine with seasonal outdoor seating & weekly live music.",
      "Neighborhood": "Oakley",
      "Address": "3036 Madison Rd, Cincinnati, OH 45209",
      "Phone": "(513) 631-8367",
      "Website": "http://www.habitscafe.com/",
      "Hours - Monday": "11AM–2:30AM",
      "Hours - Tuesday": "11AM–2:30AM",
      "Hours - Wednesday": "11AM–2:30AM",
      "Hours - Thursday": "11AM–2:30AM",
      "Hours - Friday": "11AM–2:30AM",
      "Hours - Saturday": "9AM–2:30AM",
      "Hours - Sunday": "9AM–2:30AM",
      "Specials - Monday": "",
      "Specials - Tuesday": "",
      "Specials - Wednesday": "",
      "Specials - Thursday": "",
      "Specials - Friday": "",
      "Specials - Saturday": "",
      "Specials - Sunday": "",
      "Note": ""
    },
    {
      "Bar": "Bar Louie",
      "Description": "Upbeat grill chain with American grub, martinis & microbrews, plus happy-hour deals.",
      "Neighborhood": "Oakley",
      "Address": "3100 Vandercar Way, Cincinnati, OH 45209",
      "Phone": "(513) 351-1453",
      "Website": "http://barlouie.com/locations/states/ohio/oakley-station?utm_source=google&utm_medium=listings",
      "Hours - Monday": "11AM–2AM",
      "Hours - Tuesday": "11AM–2AM",
      "Hours - Wednesday": "11AM–2AM",
      "Hours - Thursday": "11AM–2AM",
      "Hours - Friday": "11AM–2AM",
      "Hours - Saturday": "11AM–2AM",
      "Hours - Sunday": "11AM–2AM",
      "Specials - Monday": "HAPPY HOUR\nMonday-Friday\n4pm-7pm\n$3.50 Drafts\n$4.50 Wines\n$5.50 Signature Martinis\nHalf Price Select Apps\nand Flatbreads",
      "Specials - Tuesday": "HAPPY HOUR\nMonday-Friday\n4pm-7pm\n$3.50 Drafts\n$4.50 Wines\n$5.50 Signature Martinis\nHalf Price Select Apps\nand Flatbreads",
      "Specials - Wednesday": "HAPPY HOUR\nMonday-Friday\n4pm-7pm\n$3.50 Drafts\n$4.50 Wines\n$5.50 Signature Martinis\nHalf Price Select Apps\nand Flatbreads",
      "Specials - Thursday": "HAPPY HOUR\nMonday-Friday\n4pm-7pm\n$3.50 Drafts\n$4.50 Wines\n$5.50 Signature Martinis\nHalf Price Select Apps\nand Flatbreads",
      "Specials - Friday": "HAPPY HOUR\nMonday-Friday\n4pm-7pm\n$3.50 Drafts\n$4.50 Wines\n$5.50 Signature Martinis\nHalf Price Select Apps\nand Flatbreads",
      "Specials - Saturday": "",
      "Specials - Sunday": "",
      "Note": ""
    },
    {
      "Bar": "R P Mc Murphy's Irish Pub",
      "Description": "Upbeat bar featuring a range of draft beers, frequent live music & a patio area with fire pits.",
      "Neighborhood": "Oakley",
      "Address": "2910 Wasson Rd, Cincinnati, OH 45209",
      "Phone": "(513) 531-3300",
      "Website": "http://www.rpmcmurphyspub.com/",
      "Hours - Monday": "3PM–2:30AM",
      "Hours - Tuesday": "3PM–2:30AM",
      "Hours - Wednesday": "3PM–2:30AM",
      "Hours - Thursday": "3PM–2:30AM",
      "Hours - Friday": "3PM–2:30AM",
      "Hours - Saturday": "12PM–2:30AM",
      "Hours - Sunday": "12PM–2:30AM",
      "Specials - Monday": "",
      "Specials - Tuesday": "",
      "Specials - Wednesday": "",
      "Specials - Thursday": "",
      "Specials - Friday": "",
      "Specials - Saturday": "",
      "Specials - Sunday": "",
      "Note": ""
    },
    {
      "Bar": "The Casual Pint Oakley Station",
      "Description": "",
      "Neighborhood": "Oakley",
      "Address": "3200 Vandercar Way, Cincinnati, OH 45209",
      "Phone": "(513) 351-2264",
      "Website": "http://oakleystation.thecasualpint.com/",
      "Hours - Monday": "4–10PM",
      "Hours - Tuesday": "12–11PM",
      "Hours - Wednesday": "12–11PM",
      "Hours - Thursday": "12–11PM",
      "Hours - Friday": "12PM–12AM",
      "Hours - Saturday": "12PM–12AM",
      "Hours - Sunday": "1–9PM",
      "Specials - Monday": "",
      "Specials - Tuesday": "",
      "Specials - Wednesday": "",
      "Specials - Thursday": "",
      "Specials - Friday": "",
      "Specials - Saturday": "",
      "Specials - Sunday": "",
      "Note": ""
    },
    {
      "Bar": "Oakley Wines",
      "Description": "",
      "Neighborhood": "Oakley",
      "Address": "4011 Allston St, Cincinnati, OH 45209",
      "Phone": "(513) 531-1400",
      "Website": "http://www.oakleywines.com/",
      "Hours - Monday": "3PM–12AM",
      "Hours - Tuesday": "3PM–12AM",
      "Hours - Wednesday": "3PM–12AM",
      "Hours - Thursday": "3PM–12AM",
      "Hours - Friday": "3PM–1AM",
      "Hours - Saturday": "3PM–1AM",
      "Hours - Sunday": "Closed",
      "Specials - Monday": "Happy Hour prices from 4-6 pm.",
      "Specials - Tuesday": "Happy Hour prices from 4-6 pm.",
      "Specials - Wednesday": "Happy Hour prices from 4-6 pm.",
      "Specials - Thursday": "Happy Hour prices from 4-6 pm.",
      "Specials - Friday": "Happy Hour prices from 4-6 pm.\nFriday Night Tasting\nEVERY FRIDAY NIGHT\n5 - 8 pm, $10\n​Enjoy 5 glass pours. Tasting takes places upstairs in The Tasting Room, but you're welcome to enjoy your wine downstairs in The Cellar.",
      "Specials - Saturday": "Happy Hour prices from 4-6 pm.",
      "Specials - Sunday": "",
      "Note": ""
    },
    {
      "Bar": "Maribelle's eat + drink",
      "Description": "Casual bistro serving area-sourced American eats including vegan options, plus beer & cocktails.",
      "Neighborhood": "Oakley",
      "Address": "3235 Madison Rd, Cincinnati, OH 45209",
      "Phone": "(513) 321-9111",
      "Website": "http://www.maribelleseatdrink.com/",
      "Hours - Monday": "Closed",
      "Hours - Tuesday": "5–9PM",
      "Hours - Wednesday": "5–9PM",
      "Hours - Thursday": "5–9PM",
      "Hours - Friday": "11AM–10PM",
      "Hours - Saturday": "11AM–10PM",
      "Hours - Sunday": "11AM–9PM",
      "Specials - Monday": "",
      "Specials - Tuesday": "",
      "Specials - Wednesday": "",
      "Specials - Thursday": "",
      "Specials - Friday": "",
      "Specials - Saturday": "",
      "Specials - Sunday": "",
      "Note": ""
    },
    {
      "Bar": "Hap's Irish Pub",
      "Description": "",
      "Neighborhood": "Oakley",
      "Address": "3510 Erie Ave, Cincinnati, OH 45208",
      "Phone": "(513) 871-6477",
      "Website": "https://www.facebook.com/Haps-Irish-Pub-125057637545502/",
      "Hours - Monday": "12PM–2:30AM",
      "Hours - Tuesday": "12PM–2:30AM",
      "Hours - Wednesday": "12PM–2:30AM",
      "Hours - Thursday": "12PM–2:30AM",
      "Hours - Friday": "12PM–2:30AM",
      "Hours - Saturday": "9AM–2:30AM",
      "Hours - Sunday": "12PM–2:30AM",
      "Specials - Monday": "",
      "Specials - Tuesday": "",
      "Specials - Wednesday": "",
      "Specials - Thursday": "",
      "Specials - Friday": "",
      "Specials - Saturday": "",
      "Specials - Sunday": "",
      "Note": ""
    },
    {
      "Bar": "Animations",
      "Description": "",
      "Neighborhood": "Oakley",
      "Address": "3059 Madison Rd, Cincinnati, OH 45209",
      "Phone": "(513) 871-7606",
      "Website": "",
      "Hours - Monday": "12PM–2:30AM",
      "Hours - Tuesday": "12PM–2:30AM",
      "Hours - Wednesday": "12PM–2:30AM",
      "Hours - Thursday": "12PM–2:30AM",
      "Hours - Friday": "12PM–2:30AM",
      "Hours - Saturday": "12PM–2:30AM",
      "Hours - Sunday": "12PM–2:30AM",
      "Specials - Monday": "",
      "Specials - Tuesday": "",
      "Specials - Wednesday": "",
      "Specials - Thursday": "",
      "Specials - Friday": "",
      "Specials - Saturday": "",
      "Specials - Sunday": "",
      "Note": ""
    },
    {
      "Bar": "Keystone Bar & Grill",
      "Description": "A lively spot for gourmet bar food (available family-style), cocktails, wine & a lengthy beer menu.",
      "Neighborhood": "Oakley",
      "Address": "1626, 3384 Erie Ave, Cincinnati, OH 45208",
      "Phone": "(513) 321-2150",
      "Website": "http://www.keystonebar.com/",
      "Hours - Monday": "11:30AM–12AM",
      "Hours - Tuesday": "11:30AM–12AM",
      "Hours - Wednesday": "11:30AM–12AM",
      "Hours - Thursday": "11:30AM–12AM",
      "Hours - Friday": "11:30AM–2:30AM",
      "Hours - Saturday": "10AM–2:30AM",
      "Hours - Sunday": "10AM–12AM",
      "Specials - Monday": "Half-Price Mac & Cheese\nw/ beverage purchase until 11pm and $4 Moscow Mules from 6pm – Close\nMonday – Friday 3-6pm\n1/2 price appetizers, 1/2 price bottles of wine, 1/2 price signature cocktails, $2 off select drafts, and $2 domestics",
      "Specials - Tuesday": "Half-Price Quesadillas\nw/ beverage purchase until 11pm and $2 Tall Boys all day\nMonday – Friday 3-6pm\n1/2 price appetizers, 1/2 price bottles of wine, 1/2 price signature cocktails, $2 off select drafts, and $2 domestics",
      "Specials - Wednesday": "BYOB (Build Your Own Burger Night)\nLocal beer of the month for $3 beginning at 6pm\nMonday – Friday 3-6pm\n1/2 price appetizers, 1/2 price bottles of wine, 1/2 price signature cocktails, $2 off select drafts, and $2 domestics",
      "Specials - Thursday": "Half-Price Pints\nall day *rare exclusions apply\nMonday – Friday 3-6pm\n1/2 price appetizers, 1/2 price bottles of wine, 1/2 price signature cocktails, $2 off select drafts, and $2 domestics",
      "Specials - Friday": "Double-Down Happy Hour\nHappy hour pricing from 3-6pm and 9pm-close\nMonday – Friday 3-6pm\n1/2 price appetizers, 1/2 price bottles of wine, 1/2 price signature cocktails, $2 off select drafts, and $2 domestics",
      "Specials - Saturday": "$14 Mimosa Pitchers (10am – 2pm)\n$3 Green Tea, Jameson, Fireball, Big Blue shots with the purchase of any beer from 9pm-close",
      "Specials - Sunday": "$14 Mimosa Pitchers (11am – 2pm)\n$2 domestic bottles and half-price signature cocktails from 2pm-close",
      "Note": ""
    },
    {
      "Bar": "Edge Inn Tavern",
      "Description": "",
      "Neighborhood": "Oakley",
      "Address": "3935 Edwards Rd, Cincinnati, OH 45209",
      "Phone": "(513) 841-9030",
      "Website": "",
      "Hours - Monday": "1PM–2:30AM",
      "Hours - Tuesday": "1PM–2:30AM",
      "Hours - Wednesday": "1PM–2:30AM",
      "Hours - Thursday": "1PM–2:30AM",
      "Hours - Friday": "1PM–2:30AM",
      "Hours - Saturday": "12PM–2:30AM",
      "Hours - Sunday": "12PM–2:30AM",
      "Specials - Monday": "",
      "Specials - Tuesday": "",
      "Specials - Wednesday": "",
      "Specials - Thursday": "",
      "Specials - Friday": "",
      "Specials - Saturday": "",
      "Specials - Sunday": "",
      "Note": ""
    },
    {
      "Bar": "Establishment",
      "Description": "",
      "Neighborhood": "Oakley",
      "Address": "2900 Wasson Rd, Cincinnati, OH 45209",
      "Phone": "(513) 631-9000",
      "Website": "http://theeoakley.com/",
      "Hours - Monday": "3:30PM–2:30AM",
      "Hours - Tuesday": "3:30PM–2:30AM",
      "Hours - Wednesday": "3:30PM–2:30AM",
      "Hours - Thursday": "3:30PM–2:30AM",
      "Hours - Friday": "3:30PM–2:30AM",
      "Hours - Saturday": "3:30PM–2:30AM",
      "Hours - Sunday": "12PM–2:30AM",
      "Specials - Monday": "Happy Hour:\nMonday – Thursday 3:30pm – 9pm\n$2.00 Domestic Bottles and drafts\n$3.00 Well Liquor Drinks",
      "Specials - Tuesday": "Happy Hour:\nMonday – Thursday 3:30pm – 9pm\n$2.00 Domestic Bottles and drafts\n$3.00 Well Liquor Drinks",
      "Specials - Wednesday": "Happy Hour:\nMonday – Thursday 3:30pm – 9pm\n$2.00 Domestic Bottles and drafts\n$3.00 Well Liquor Drinks",
      "Specials - Thursday": "Happy Hour:\nMonday – Thursday 3:30pm – 9pm\n$2.00 Domestic Bottles and drafts\n$3.00 Well Liquor Drinks",
      "Specials - Friday": "Happy Hour:\nFriday 3:30pm – 7:30pm\n$2.00 Domestic Bottles and drafts\n$3.00 Well Liquor Drinks",
      "Specials - Saturday": "Happy Hour:\nSaturday – Sunday 12pm – 7:30pm\n$2.00 Domestic Bottles and drafts\n$3.00 Well Liquor Drinks",
      "Specials - Sunday": "Happy Hour:\nSaturday – Sunday 12pm – 7:30pm\n$2.00 Domestic Bottles and drafts\n$3.00 Well Liquor Drinks",
      "Note": ""
    },
    {
      "Bar": "Unwind Wine Bar & Light Fare",
      "Description": "Modern-yet-rustic bar offering wine, spirits & small plates in a relaxed setting with patio seating.",
      "Neighborhood": "Oakley",
      "Address": "3435 Michigan Ave, Cincinnati, OH 45208",
      "Phone": "(513) 321-9463",
      "Website": "http://www.unwindhydepark.com/",
      "Hours - Monday": "4–11PM",
      "Hours - Tuesday": "4–11PM",
      "Hours - Wednesday": "4–11PM",
      "Hours - Thursday": "4PM–12AM",
      "Hours - Friday": "4PM–1:15AM",
      "Hours - Saturday": "4PM–12AM",
      "Hours - Sunday": "Closed",
      "Specials - Monday": "",
      "Specials - Tuesday": "",
      "Specials - Wednesday": "",
      "Specials - Thursday": "",
      "Specials - Friday": "",
      "Specials - Saturday": "",
      "Specials - Sunday": "",
      "Note": ""
    },
    {
      "Bar": "MadTree Brewing",
      "Description": "Bustling taproom offering craft beers, wood-fired pizzas, growler fills & keg sales, plus a patio.",
      "Neighborhood": "Oakley",
      "Address": "3301 Madison Rd, Cincinnati, OH 45209",
      "Phone": "(513) 836-8733",
      "Website": "http://www.madtreebrewing.com/",
      "Hours - Monday": "11AM–11PM",
      "Hours - Tuesday": "11AM–11PM",
      "Hours - Wednesday": "11AM–11PM",
      "Hours - Thursday": "11AM–11PM",
      "Hours - Friday": "11AM–1AM",
      "Hours - Saturday": "10AM–1AM",
      "Hours - Sunday": "10AM–11PM",
      "Specials - Monday": "",
      "Specials - Tuesday": "",
      "Specials - Wednesday": "",
      "Specials - Thursday": "",
      "Specials - Friday": "",
      "Specials - Saturday": "",
      "Specials - Sunday": "",
      "Note": ""
    },
    {
      "Bar": "The Pub at Rookwood Mews",
      "Description": "British-inspired pub with a wraparound bar serves comfort eats & pints in charming, old-world digs.",
      "Neighborhood": "Oakley",
      "Address": "2692 Edmondson Rd, Cincinnati, OH 45208",
      "Phone": "(513) 841-2748",
      "Website": "http://experiencethepub.com/rookwood",
      "Hours - Monday": "11AM–12AM",
      "Hours - Tuesday": "11AM–12AM",
      "Hours - Wednesday": "11AM–12AM",
      "Hours - Thursday": "11AM–12AM",
      "Hours - Friday": "11AM–1AM",
      "Hours - Saturday": "10AM–1AM",
      "Hours - Sunday": "10AM–11PM",
      "Specials - Monday": "Happy Hour\nMonday – Friday | 3pm – 7pm\n$5.00 Appetizers\nDrink Specials\nMonday\nPub Quiz 7:30pm",
      "Specials - Tuesday": "Happy Hour\nMonday – Friday | 3pm – 7pm\n$5.00 Appetizers\nDrink Specials",
      "Specials - Wednesday": "Happy Hour\nMonday – Friday | 3pm – 7pm\n$5.00 Appetizers\nDrink Specials\nWednesday\n1/2 priced bottles of select wines",
      "Specials - Thursday": "Happy Hour\nMonday – Friday | 3pm – 7pm\n$5.00 Appetizers\nDrink Specials",
      "Specials - Friday": "Happy Hour\nMonday – Friday | 3pm – 7pm\n$5.00 Appetizers\nDrink Specials",
      "Specials - Saturday": "",
      "Specials - Sunday": "",
      "Note": "Military Discount\nAll members of the military receive a 25% discount on food purchases when they present a military ID."
    },
    {
      "Bar": "Dutch's",
      "Description": "A massive collection of handcrafted beer & wine (to drink or buy), plus artisanal meats & cheeses.",
      "Neighborhood": "Oakley",
      "Address": "3378 Erie Ave, Cincinnati, OH 45208",
      "Phone": "(513) 871-1446",
      "Website": "http://www.dutchscincinnati.com/",
      "Hours - Monday": "Closed",
      "Hours - Tuesday": "11AM–9PM",
      "Hours - Wednesday": "11AM–9PM",
      "Hours - Thursday": "11AM–9PM",
      "Hours - Friday": "11AM–10PM",
      "Hours - Saturday": "11AM–10PM",
      "Hours - Sunday": "11AM–9PM",
      "Specials - Monday": "",
      "Specials - Tuesday": "",
      "Specials - Wednesday": "",
      "Specials - Thursday": "",
      "Specials - Friday": "",
      "Specials - Saturday": "",
      "Specials - Sunday": "",
      "Note": ""
    },
    {
      "Bar": "MILLIONS CAFÉ",
      "Description": "",
      "Neighborhood": "Oakley",
      "Address": "3210 Linwood Ave, Cincinnati, OH 45208",
      "Phone": "(513) 815-4500",
      "Website": "http://www.millions-cafe.com/",
      "Hours - Monday": "4PM–2:30AM",
      "Hours - Tuesday": "4PM–2:30AM",
      "Hours - Wednesday": "4PM–2:30AM",
      "Hours - Thursday": "4PM–2:30AM",
      "Hours - Friday": "4PM–2:30AM",
      "Hours - Saturday": "11:30AM–2:30AM",
      "Hours - Sunday": "11:30AM–2:30AM",
      "Specials - Monday": "",
      "Specials - Tuesday": "",
      "Specials - Wednesday": "",
      "Specials - Thursday": "",
      "Specials - Friday": "",
      "Specials - Saturday": "",
      "Specials - Sunday": "",
      "Note": ""
    },
    {
      "Bar": "Hooligan's Pub & Eatery",
      "Description": "Longtime family-owned joint with American eats, an outdoor patio & a seasonal sand volleyball court.",
      "Neighborhood": "Oakley",
      "Address": "3340 Highland Ave, Cincinnati, OH 45213",
      "Phone": "(513) 841-9994",
      "Website": "http://www.hooligans-pub.com/",
      "Hours - Monday": "11AM–2:30AM",
      "Hours - Tuesday": "11AM–2:30AM",
      "Hours - Wednesday": "11AM–2:30AM",
      "Hours - Thursday": "11AM–2:30AM",
      "Hours - Friday": "11AM–2:30AM",
      "Hours - Saturday": "11AM–2:30AM",
      "Hours - Sunday": "11AM–2:30AM",
      "Specials - Monday": "",
      "Specials - Tuesday": "",
      "Specials - Wednesday": "",
      "Specials - Thursday": "",
      "Specials - Friday": "",
      "Specials - Saturday": "",
      "Specials - Sunday": "",
      "Note": ""
    },
    {
      "Bar": "BrewRiver GastroPub",
      "Description": "Riverside tavern with a big patio, serving N’Awlins-style American classics & oodles of local brews.",
      "Neighborhood": "Oakley",
      "Address": "2062 Riverside Dr, Cincinnati, OH 45202",
      "Phone": "(513) 861-2484",
      "Website": "http://brewrivergastropub.com/",
      "Hours - Monday": "Closed",
      "Hours - Tuesday": "11AM–9PM",
      "Hours - Wednesday": "11AM–9PM",
      "Hours - Thursday": "11AM–9PM",
      "Hours - Friday": "11AM–10PM",
      "Hours - Saturday": "10AM–10PM",
      "Hours - Sunday": "10AM–9PM",
      "Specials - Monday": "",
      "Specials - Tuesday": "",
      "Specials - Wednesday": "",
      "Specials - Thursday": "",
      "Specials - Friday": "",
      "Specials - Saturday": "",
      "Specials - Sunday": "",
      "Note": ""
    },
    {
      "Bar": "Mt. Lookout Tavern",
      "Description": "",
      "Neighborhood": "Oakley",
      "Address": "3209 Linwood Ave, Cincinnati, OH 45226",
      "Phone": "(513) 871-9633",
      "Website": "http://www.mtlookouttavern.com/",
      "Hours - Monday": "11AM–2:30AM",
      "Hours - Tuesday": "11AM–2:30AM",
      "Hours - Wednesday": "11AM–2:30AM",
      "Hours - Thursday": "11AM–2:30AM",
      "Hours - Friday": "11AM–2:30AM",
      "Hours - Saturday": "11AM–2:30AM",
      "Hours - Sunday": "11AM–2:30AM",
      "Specials - Monday": "",
      "Specials - Tuesday": "",
      "Specials - Wednesday": "",
      "Specials - Thursday": "",
      "Specials - Friday": "",
      "Specials - Saturday": "",
      "Specials - Sunday": "",
      "Note": ""
    },
    {
      "Bar": "Zip's Café",
      "Description": "Burgers, fried fish sandwiches & other pub-grub classics go alongside beer at this longtime hangout.",
      "Neighborhood": "Oakley",
      "Address": "1036 Delta Ave, Cincinnati, OH 45208",
      "Phone": "(513) 871-9876",
      "Website": "http://www.zipscafe.com/",
      "Hours - Monday": "10:30AM–11PM",
      "Hours - Tuesday": "10:30AM–11PM",
      "Hours - Wednesday": "10:30AM–11PM",
      "Hours - Thursday": "10:30AM–11PM",
      "Hours - Friday": "10:30AM–11:30PM",
      "Hours - Saturday": "10:30AM–11:30PM",
      "Hours - Sunday": "11AM–11PM",
      "Specials - Monday": "",
      "Specials - Tuesday": "",
      "Specials - Wednesday": "",
      "Specials - Thursday": "",
      "Specials - Friday": "",
      "Specials - Saturday": "",
      "Specials - Sunday": "",
      "Note": ""
    },
    {
      "Bar": "Proof Bar",
      "Description": "",
      "Neighborhood": "Oakley",
      "Address": "3195 Linwood Ave, Cincinnati, OH 45208",
      "Phone": "",
      "Website": "",
      "Hours - Monday": "5PM–2:30AM",
      "Hours - Tuesday": "5PM–2:30AM",
      "Hours - Wednesday": "5PM–2:30AM",
      "Hours - Thursday": "5PM–2:30AM",
      "Hours - Friday": "5PM–2:30AM",
      "Hours - Saturday": "5PM–2:30AM",
      "Hours - Sunday": "5PM–2:30AM",
      "Specials - Monday": "",
      "Specials - Tuesday": "",
      "Specials - Wednesday": "",
      "Specials - Thursday": "",
      "Specials - Friday": "",
      "Specials - Saturday": "",
      "Specials - Sunday": "",
      "Note": ""
    },
    {
      "Bar": "Pearl's Bar",
      "Description": "Neighborhood pub serving beer & spirits in a 100-year-old distressed building with an outdoor patio.",
      "Neighborhood": "Oakley",
      "Address": "3520 Eastern Ave, Cincinnati, OH 45226",
      "Phone": "(513) 832-0485",
      "Website": "http://www.pearls-cincy.com/",
      "Hours - Monday": "4PM–2AM",
      "Hours - Tuesday": "4PM–2AM",
      "Hours - Wednesday": "4PM–2AM",
      "Hours - Thursday": "4PM–2AM",
      "Hours - Friday": "3PM–2AM",
      "Hours - Saturday": "12PM–2AM",
      "Hours - Sunday": "12PM–12AM",
      "Specials - Monday": "",
      "Specials - Tuesday": "",
      "Specials - Wednesday": "",
      "Specials - Thursday": "",
      "Specials - Friday": "",
      "Specials - Saturday": "",
      "Specials - Sunday": "",
      "Note": ""
    },
    {
      "Bar": "The Hi-Mark",
      "Description": "Easygoing, industrial cocktail & craft beer bar inside an 1866 house with a spacious patio.",
      "Neighborhood": "Oakley",
      "Address": "3229 Riverside Dr, Cincinnati, OH 45226",
      "Phone": "(513) 492-7119",
      "Website": "http://www.thehimark.com/",
      "Hours - Monday": "4PM–12AM",
      "Hours - Tuesday": "4PM–12AM",
      "Hours - Wednesday": "4PM–12AMM–12AM",
      "Hours - Thursday": "4PM–12AM",
      "Hours - Friday": "4PM–2AM",
      "Hours - Saturday": "12PM–2AM",
      "Hours - Sunday": "12PM–12AM",
      "Specials - Monday": "",
      "Specials - Tuesday": "",
      "Specials - Wednesday": "",
      "Specials - Thursday": "",
      "Specials - Friday": "",
      "Specials - Saturday": "",
      "Specials - Sunday": "",
      "Note": ""
    },
    {
      "Bar": "Spittoon Saloon",
      "Description": "",
      "Neighborhood": "Oakley",
      "Address": "4835 Eastern Ave, Cincinnati, OH 45208",
      "Phone": "",
      "Website": "",
      "Hours - Monday": "Closed",
      "Hours - Tuesday": "Closed",
      "Hours - Wednesday": "Closed",
      "Hours - Thursday": "5PM–3AM",
      "Hours - Friday": "5PM–3AM",
      "Hours - Saturday": "5PM–3AM",
      "Hours - Sunday": "5PM–3AM",
      "Specials - Monday": "",
      "Specials - Tuesday": "",
      "Specials - Wednesday": "",
      "Specials - Thursday": "",
      "Specials - Friday": "",
      "Specials - Saturday": "",
      "Specials - Sunday": "",
      "Note": ""
    },
    {
      "Bar": "Cock & Bull Public House",
      "Description": "",
      "Neighborhood": "Hyde Park",
      "Address": "2645 Erie Ave, Cincinnati, OH 45208",
      "Phone": "(513) 533-4253",
      "Website": "http://www.cockandbullcincinnati.com/",
      "Hours - Monday": "11AM–11PM",
      "Hours - Tuesday": "11AM–11PM",
      "Hours - Wednesday": "11AM–11PM",
      "Hours - Thursday": "11AM–12AM",
      "Hours - Friday": "11AM–2AM",
      "Hours - Saturday": "11AM–2AM",
      "Hours - Sunday": "11AM–10PM",
      "Specials - Monday": "",
      "Specials - Tuesday": "",
      "Specials - Wednesday": "",
      "Specials - Thursday": "Pint Night - 6PM Keep the Glass",
      "Specials - Friday": "",
      "Specials - Saturday": "",
      "Specials - Sunday": "",
      "Note": ""
    }
  ]

  // barList.forEach((i) => {
  //   console.log(i.Bar, i.Neighborhood, i.Phone);
  // })