export const barList = [
  {
    "ID": 1,
    "Bar": "Taft's Ale House",
    "Description": "Artisanal beers, steaks & salads served in a classic brewpub named after Cincinnati’s favorite son.",
    "Neighborhood": "Over-the-Rhine",
    "Address": "1429 Race St, Cincinnati, OH 45202",
    "Phone": "(513) 334-1393",
    "Website": "http://taftsalehouse.com/",
    "hoursMonday": "11:30AM–10PM",
    "hoursTuesday": "11:30AM–10PM",
    "hoursWednesday": "11:30AM–11PM",
    "hoursThursday": "11:30AM–12AM",
    "hoursFriday": "11:30AM–12AM",
    "hoursSaturday": "11:30AM–12AM",
    "hoursSunday": "11:30AM–9PM",
    "specialMonday": "",
    "specialTuesday": "Taft Tuesdays - Enjoy Half-Price Pints & Growler Fills ALL DAY by wearing any Brewery or Beer Apparel. Don’t have any threads? Stop-n-shop in Nellie’s Tap Room to pick up your gear!",
    "specialWednesday": "",
    "specialThursday": "",
    "specialFriday": "",
    "specialSaturday": "",
    "specialSunday": "",
    "Note": "",
    "lat": 39.111325,
    "long": -84.51750995
  },
  {
    "ID": 2,
    "Bar": "Sundry and Vice",
    "Description": "Striking, well-appointed cocktail spot with a tin ceiling & vintage feel offering inventive drinks.",
    "Neighborhood": "Over-the-Rhine",
    "Address": "18 W 13th St, Cincinnati, OH 45202",
    "Phone": "(513) 721-8423",
    "Website": "http://sundryandvice.com/",
    "hoursMonday": "Closed",
    "hoursTuesday": "4PM–2AM",
    "hoursWednesday": "4PM–2AM",
    "hoursThursday": "4PM–2AM",
    "hoursFriday": "4PM–2AM",
    "hoursSaturday": "12PM–2AM",
    "hoursSunday": "12PM–12AM",
    "specialMonday": "",
    "specialTuesday": "",
    "specialWednesday": "",
    "specialThursday": "",
    "specialFriday": "",
    "specialSaturday": "",
    "specialSunday": "",
    "Note": "",
    "lat": 39.1094369,
    "long": -84.5160001
  },
  {
    "ID": 3,
    "Bar": "The Rook OTR",
    "Description": "",
    "Neighborhood": "Over-the-Rhine",
    "Address": "1115 Vine St, Cincinnati, OH 45202",
    "Phone": "(513) 954-8191",
    "Website": "https://www.facebook.com/therookotr/",
    "hoursMonday": "4PM–12AM",
    "hoursTuesday": "4PM–12AM",
    "hoursWednesday": "4PM–12AM",
    "hoursThursday": "4PM–12AM",
    "hoursFriday": "4PM–2AM",
    "hoursSaturday": "11AM–2AM",
    "hoursSunday": "11AM–12AM",
    "specialMonday": "",
    "specialTuesday": "",
    "specialWednesday": "",
    "specialThursday": "",
    "specialFriday": "",
    "specialSaturday": "",
    "specialSunday": "",
    "Note": "Lots of different events.",
    "lat": 39.1076943,
    "long": -84.5148587
  },
  {
    "ID": 4,
    "Bar": "The Lackman",
    "Description": "Luxe lounge in a turn-of-the-century building offering craft beers & eclectic wines, plus a jukebox.",
    "Neighborhood": "Over-the-Rhine",
    "Address": "1237 Vine Street, Cincinnati, OH 45202",
    "Phone": "(513) 381-0741",
    "Website": "http://www.lackmanbar.com/",
    "hoursMonday": "4PM–2AM",
    "hoursTuesday": "4PM–2AM",
    "hoursWednesday": "4PM–2AM",
    "hoursThursday": "4PM–2AM",
    "hoursFriday": "3PM–2AM",
    "hoursSaturday": "12PM–2AM",
    "hoursSunday": "12PM–12AM",
    "specialMonday": "HAPPY HOUR, Happy Hour | 4-8PM, $2 Off Drafts, $3.25 Domestics, $4.50 Calls, $5 Dark Horse Wines",
    "specialTuesday": "HAPPY HOUR, Happy Hour | 4-8PM, $2 Off Drafts, $3.25 Domestics, $4.50 Calls, $5 Dark Horse Wines",
    "specialWednesday": "HAPPY HOUR, Happy Hour | 4-8PM, $2 Off Drafts, $3.25 Domestics, $4.50 Calls, $5 Dark Horse Wines",
    "specialThursday": "HAPPY HOUR, Happy Hour | 4-8PM, $2 Off Drafts, $3.25 Domestics, $4.50 Calls, $5 Dark Horse Wines",
    "specialFriday": "HAPPY HOUR, Happy Hour | 4-8PM, $2 Off Drafts, $3.25 Domestics, $4.50 Calls, $5 Dark Horse Wines",
    "specialSaturday": "HAPPY HOUR, Happy Hour | 4-8PM, $2 Off Drafts, $3.25 Domestics, $4.50 Calls, $5 Dark Horse Wines",
    "specialSunday": "HAPPY HOUR, Happy Hour | 4-8PM, $2 Off Drafts, $3.25 Domestics, $4.50 Calls, $5 Dark Horse Wines",
    "Note": "",
    "lat": 39.1093292,
    "long": -84.5152165
  },
  {
    "ID": 5,
    "Bar": "Japp's - Since 1879",
    "Description": "Bustling spot for classic & creative cocktails served in casual environs in a storied building.",
    "Neighborhood": "Over-the-Rhine",
    "Address": "1136 Main St, Cincinnati, OH 45202",
    "Phone": "(513) 381-1524",
    "Website": "http://japps1879.com/",
    "hoursMonday": "Closed",
    "hoursTuesday": "4PM–1AM",
    "hoursWednesday": "4PM–1AM",
    "hoursThursday": "4PM–1AM",
    "hoursFriday": "4PM–2AM",
    "hoursSaturday": "5PM–2AM",
    "hoursSunday": "Closed",
    "specialMonday": "",
    "specialTuesday": "",
    "specialWednesday": "",
    "specialThursday": "Live Music from Jess Lamb and Friends, 9:00 PM – 11:30 PM, Live music from Cincinnati native, Jess Lamb, and special guests, every week!",
    "specialFriday": "The Burning Caravan at Japp's,  5:30 PM – 8:30 PM, Live Music from The Burning Caravan from 530-830pm EVERY Friday!, Rotating Local DJ's in the Lounge, 9:00 PM – 11:30 PM, Every Friday night we host a DJ for a late night set in the lounge! Check us out on Facebook for info on this week's DJ! , 9pm-close every Friday!",
    "specialSaturday": "Live Happy Hour Music, 6:00 PM – 9:00 PM, Live Happy Hour Music Every Saturday.",
    "specialSunday": "",
    "Note": "",
    "lat": 39.1088678,
    "long": -84.5113795
  },
  {
    "ID": 6,
    "Bar": "rhinehaus",
    "Description": "Laid-back hangout with sports on TV & craft beers offered in a contemporary, exposed-brick space.",
    "Neighborhood": "Over-the-Rhine",
    "Address": "119 E 12th St, Cincinnati, OH 45202",
    "Phone": "(513) 381-2277",
    "Website": "http://www.rhinehausbar.com/",
    "hoursMonday": "4PM–2AM",
    "hoursTuesday": "4PM–2AM",
    "hoursWednesday": "4PM–2AM",
    "hoursThursday": "4PM–2AM",
    "hoursFriday": "4PM–2AM",
    "hoursSaturday": "7AM–2AM",
    "hoursSunday": "7AM–12AM",
    "specialMonday": "",
    "specialTuesday": "",
    "specialWednesday": "",
    "specialThursday": "",
    "specialFriday": "",
    "specialSaturday": "",
    "specialSunday": "",
    "Note": "",
    "lat": 39.108539,
    "long": -84.5124497
  },
  {
    "ID": 7,
    "Bar": "Motr Pub",
    "Description": "Easygoing hangout with local art on the walls, featuring live rock bands & hearty comfort fare.",
    "Neighborhood": "Over-the-Rhine",
    "Address": "1345 Main St, Cincinnati, OH 45202",
    "Phone": "(513) 381-6687",
    "Website": "http://www.pubcincinnati.com/",
    "hoursMonday": "11AM–2:30AM",
    "hoursTuesday": "11AM–2:30AM",
    "hoursWednesday": "11AM–2:30AM",
    "hoursThursday": "11AM–2:30AM",
    "hoursFriday": "11AM–2:30AM",
    "hoursSaturday": "10AM–2:30AM",
    "hoursSunday": "10AM–2:30AM",
    "specialMonday": "",
    "specialTuesday": "",
    "specialWednesday": "",
    "specialThursday": "",
    "specialFriday": "",
    "specialSaturday": "",
    "specialSunday": "",
    "Note": "",
    "lat": 39.111099,
    "long": -84.5123402
  },
  {
    "ID": 8,
    "Bar": "Bakersfield OTR",
    "Description": "Tacos & a few other Mexican dishes are delivered in a chic, upbeat, margarita-fueled atmosphere.",
    "Neighborhood": "Over-the-Rhine",
    "Address": "1213 Vine St, Cincinnati, OH 45202",
    "Phone": "(513) 579-0446",
    "Website": "http://www.bakersfieldtacos.com/",
    "hoursMonday": "11AM–12AM",
    "hoursTuesday": "11AM–12AM",
    "hoursWednesday": "11AM–12AM",
    "hoursThursday": "11AM–12AM",
    "hoursFriday": "11AM–2AM",
    "hoursSaturday": "11AM–2AM",
    "hoursSunday": "11AM–12AM",
    "specialMonday": "",
    "specialTuesday": "",
    "specialWednesday": "",
    "specialThursday": "",
    "specialFriday": "",
    "specialSaturday": "",
    "specialSunday": "",
    "Note": "",
    "lat": 39.1086918,
    "long": -84.5150696
  },
  {
    "ID": 9,
    "Bar": "Below Zero Lounge",
    "Description": "Trendy spot with upbeat music serving over 100 vodkas, with featured vodkas served at 6° F.",
    "Neighborhood": "Over-the-Rhine",
    "Address": "1120 Walnut St, Cincinnati, OH 45202",
    "Phone": "(513) 421-9376",
    "Website": "http://www.belowzerolounge.com/",
    "hoursMonday": "Closed",
    "hoursTuesday": "Closed",
    "hoursWednesday": "4PM–12AM",
    "hoursThursday": "4PM–2AM",
    "hoursFriday": "4PM–2AM",
    "hoursSaturday": "4PM–2AM",
    "hoursSunday": "4PM–12AM",
    "specialMonday": "Happy Hour, 4-8pm",
    "specialTuesday": "Happy Hour, 4-8pm",
    "specialWednesday": "Happy Hour, 4-8pm",
    "specialThursday": "Happy Hour, 4-8pm",
    "specialFriday": "Happy Hour, 4-8pm",
    "specialSaturday": "Happy Hour, 4-8pm",
    "specialSunday": "Happy Hour, 4-8pm",
    "Note": "",
    "lat": 39.10836,
    "long": -84.5128840013411
  },
  {
    "ID": 10,
    "Bar": "1215 Wine Bar & Coffee Lab",
    "Description": "Homey, brick-walled cafe & bar offering breakfast, baked goods, small plates & wine tastings.",
    "Neighborhood": "Over-the-Rhine",
    "Address": "1215 Vine St, Cincinnati, OH 45202",
    "Phone": "(513) 429-5745",
    "Website": "http://www.1215vine.com/",
    "hoursMonday": "8AM–10PM",
    "hoursTuesday": "8AM–10PM",
    "hoursWednesday": "8AM–11PM",
    "hoursThursday": "8AM–12AM",
    "hoursFriday": "8AM–12AM",
    "hoursSaturday": "9AM–12AM",
    "hoursSunday": "9AM–7PM",
    "specialMonday": "",
    "specialTuesday": "",
    "specialWednesday": "",
    "specialThursday": "",
    "specialFriday": "",
    "specialSaturday": "",
    "specialSunday": "",
    "Note": "",
    "lat": 39.1072609,
    "long": -84.514515
  },
  {
    "ID": 11,
    "Bar": "Revolution Rotisserie & Bar",
    "Description": "American dishes centered around rotisserie chicken & cocktails are the draw at this modern outpost.",
    "Neighborhood": "Over-the-Rhine",
    "Address": "1106 Race St, Cincinnati, OH 45202",
    "Phone": "(513) 381-0009",
    "Website": "http://revolutionrotisserie.com/",
    "hoursMonday": "11AM–9PM",
    "hoursTuesday": "11AM–9PM",
    "hoursWednesday": "11AM–9PM",
    "hoursThursday": "11AM–9PM",
    "hoursFriday": "11AM–10PM",
    "hoursSaturday": "11AM–10PM",
    "hoursSunday": "10AM–9PM",
    "specialMonday": "Six Dollar Mules, Happy Hour 3-6PM",
    "specialTuesday": "Six Dollar Sangrias, Happy Hour 3-6PM",
    "specialWednesday": "Four Dollar Drafts, Happy Hour 3-6PM",
    "specialThursday": "Six Dollar Wines by the Glass, Happy Hour 3-6PM",
    "specialFriday": "Three Dollar Craft Beer Cans, Happy Hour 3-6PM",
    "specialSaturday": "Four Dollar Infusion Shots",
    "specialSunday": "Bottomless Mimosas & Brunch Cocktails",
    "Note": "Happy Hour:, Four Dollar Drafts, Six Dollar Wines By the Glass, Six Dollar Mules/Sangrias, Complimentary Bottomless Tater Tots during Happy Hour with purchase of alcoholic beverage.",
    "lat": 39.1073976,
    "long": -84.5159119
  },
  {
    "ID": 12,
    "Bar": "Low Spark",
    "Description": "",
    "Neighborhood": "Over-the-Rhine",
    "Address": "15 W 14th St, Cincinnati, OH 45202",
    "Phone": "(513) 371-5722",
    "Website": "http://www.lowsparkbar.com/",
    "hoursMonday": "4PM–2:30AM",
    "hoursTuesday": "4PM–2:30AM",
    "hoursWednesday": "4PM–2:30AM",
    "hoursThursday": "4PM–2:30AM",
    "hoursFriday": "4PM–2:30AM",
    "hoursSaturday": "12PM–2:30AM",
    "hoursSunday": "Closed",
    "specialMonday": "SHOT & BEER SPECIAL, MON – THU | 8pm – Close, $5 Shot & Beer Pairing, HAPPY HOUR, MON – FRI | 4pm – 7pm, $2 off signature cocktails, $2 off select drafts, $2 off calls, $1 off domestic beers, $1 off wine, EVERY DAY, $3 Budweiser drafts all day, every day",
    "specialTuesday": "SHOT & BEER SPECIAL, MON – THU | 8pm – Close, $5 Shot & Beer Pairing, HAPPY HOUR, MON – FRI | 4pm – 7pm, $2 off signature cocktails, $2 off select drafts, $2 off calls, $1 off domestic beers, $1 off wine, EVERY DAY, $3 Budweiser drafts all day, every day",
    "specialWednesday": "SHOT & BEER SPECIAL, MON – THU | 8pm – Close, $5 Shot & Beer Pairing, HAPPY HOUR, MON – FRI | 4pm – 7pm, $2 off signature cocktails, $2 off select drafts, $2 off calls, $1 off domestic beers, $1 off wine, EVERY DAY, $3 Budweiser drafts all day, every day",
    "specialThursday": "SHOT & BEER SPECIAL, MON – THU | 8pm – Close, $5 Shot & Beer Pairing, HAPPY HOUR, MON – FRI | 4pm – 7pm, $2 off signature cocktails, $2 off select drafts, $2 off calls, $1 off domestic beers, $1 off wine, EVERY DAY, $3 Budweiser drafts all day, every day",
    "specialFriday": "HAPPY HOUR, MON – FRI | 4pm – 7pm, $2 off signature cocktails, $2 off select drafts, $2 off calls, $1 off domestic beers, $1 off wine, EVERY DAY, $3 Budweiser drafts all day, every day",
    "specialSaturday": "EVERY DAY, $3 Budweiser drafts all day, every day",
    "specialSunday": "EVERY DAY, $3 Budweiser drafts all day, every day",
    "Note": "MUSIC HALL SPECIALS, Show your Cincinnati Music Hall tickets or program to receive $1 off drafts, $1 off domestics, and $1 off Tito’s vodka",
    "lat": 39.1103807,
    "long": -84.5163092
  },
  {
    "ID": 13,
    "Bar": "Longfellow",
    "Description": "",
    "Neighborhood": "Over-the-Rhine",
    "Address": "1233 Clay St, Cincinnati, OH 45202",
    "Phone": "(513) 549-0744",
    "Website": "https://longfellowbar.com/",
    "hoursMonday": "Closed",
    "hoursTuesday": "4PM–2AM",
    "hoursWednesday": "4PM–2AM",
    "hoursThursday": "4PM–2AM",
    "hoursFriday": "4PM–2AM",
    "hoursSaturday": "2PM–2AM",
    "hoursSunday": "2PM–12AM",
    "specialMonday": "",
    "specialTuesday": "Happy Hour Blue Plate Special $7, 16 oz tall boy beer, scrap sandwich OR liverwurst W/potato chips 4-7PM, Late Night Pierogies One $2 - Three $5 - Five $8 , 11PM-2AM",
    "specialWednesday": "Happy Hour Blue Plate Special $7, 16 oz tall boy beer, scrap sandwich OR liverwurst W/potato chips 4-7PM, Late Night Pierogies One $2 - Three $5 - Five $8 , 11PM-2AM, Hot Plate Curry & Rice $8",
    "specialThursday": "Happy Hour Blue Plate Special $7, 16 oz tall boy beer, scrap sandwich OR liverwurst W/potato chips 4-7PM, Late Night Pierogies One $2 - Three $5 - Five $8 , 11PM-2AM, Hot Plate Curry & Rice $8",
    "specialFriday": "Happy Hour Blue Plate Special $7, 16 oz tall boy beer, scrap sandwich OR liverwurst W/potato chips 4-7PM, Late Night Pierogies One $2 - Three $5 - Five $8 , 11PM-2AM",
    "specialSaturday": "Late Night Pierogies One $2 - Three $5 - Five $8 , 11PM-2AM",
    "specialSunday": "Late Night Pierogies One $2 - Three $5 - Five $8 , All Day",
    "Note": "",
    "lat": 39.1096956,
    "long": -84.5127973
  },
  {
    "ID": 14,
    "Bar": "Queen City Radio",
    "Description": "Spacious bar in a buzzy, industrial indoor/outdoor space offering food-truck eats, DJs & live music.",
    "Neighborhood": "Over-the-Rhine",
    "Address": "222 W 12th St, Cincinnati, OH 45202",
    "Phone": "(513) 381-0918",
    "Website": "http://qcrbar.com/",
    "hoursMonday": "4PM–2:30AM",
    "hoursTuesday": "4PM–2:30AM",
    "hoursWednesday": "4PM–2:30AM",
    "hoursThursday": "4PM–2:30AM",
    "hoursFriday": "4PM–2:30AM",
    "hoursSaturday": "12PM–2:30AM",
    "hoursSunday": "12PM–2:30AM",
    "specialMonday": "",
    "specialTuesday": "",
    "specialWednesday": "",
    "specialThursday": "",
    "specialFriday": "",
    "specialSaturday": "",
    "specialSunday": "",
    "Note": "",
    "lat": 39.1078318,
    "long": -84.519097
  },
  {
    "ID": 15,
    "Bar": "HalfCut",
    "Description": "Rotating taps of craft brews are the focus of this rustic bar that also sells growlers & wine.",
    "Neighborhood": "Over-the-Rhine",
    "Address": "1126 Walnut St, Cincinnati, OH 45202",
    "Phone": "(513) 381-1952",
    "Website": "http://www.halfcut.com/",
    "hoursMonday": "Closed",
    "hoursTuesday": "4–10PM",
    "hoursWednesday": "4–10PM",
    "hoursThursday": "11AM–12AM",
    "hoursFriday": "11AM–2:30AM",
    "hoursSaturday": "11AM–2:30AM",
    "hoursSunday": "Closed",
    "specialMonday": "",
    "specialTuesday": "",
    "specialWednesday": "",
    "specialThursday": "",
    "specialFriday": "",
    "specialSaturday": "",
    "specialSunday": "",
    "Note": "",
    "lat": 39.1083636153846,
    "long": -84.5130170769231
  },
  {
    "ID": 16,
    "Bar": "Krueger's Tavern",
    "Description": "Stylish, seasonal New American kitchen with a menu of small & large plates & a rooftop patio.",
    "Neighborhood": "Over-the-Rhine",
    "Address": "1211 Vine St, Cincinnati, OH 45202",
    "Phone": "(513) 834-8670",
    "Website": "http://www.kruegerstavern.com/",
    "hoursMonday": "11AM–12AM",
    "hoursTuesday": "11AM–12AM",
    "hoursWednesday": "11AM–12AM",
    "hoursThursday": "11AM–12AM",
    "hoursFriday": "11AM–12AM",
    "hoursSaturday": "11AM–12AM",
    "hoursSunday": "11AM–10PM",
    "specialMonday": "",
    "specialTuesday": "",
    "specialWednesday": "",
    "specialThursday": "",
    "specialFriday": "",
    "specialSaturday": "",
    "specialSunday": "",
    "Note": "",
    "lat": 39.10859605,
    "long": -84.5152225113226
  },
  {
    "ID": 17,
    "Bar": "Treehouse Patio Bar",
    "Description": "",
    "Neighborhood": "Over-the-Rhine",
    "Address": "1133 Sycamore St, Cincinnati, OH 45202",
    "Phone": "",
    "Website": "http://treehousepatiobar.berlindoener.info/",
    "hoursMonday": "Closed",
    "hoursTuesday": "4PM–2AM",
    "hoursWednesday": "4PM–2AM",
    "hoursThursday": "4PM–2AM",
    "hoursFriday": "4PM–2AM",
    "hoursSaturday": "2PM–2AM",
    "hoursSunday": "2PM–2AM",
    "specialMonday": "",
    "specialTuesday": "",
    "specialWednesday": "",
    "specialThursday": "",
    "specialFriday": "",
    "specialSaturday": "",
    "specialSunday": "",
    "Note": "",
    "lat": 39.1092069,
    "long": -84.5104021
  },
  {
    "ID": 18,
    "Bar": "Zula Restaurant & Wine Bar",
    "Description": "New American dishes, wine, craft beer & cocktails offered in a warm, industrial-style atmosphere",
    "Neighborhood": "Over-the-Rhine",
    "Address": "7010, 1400 Race St, Cincinnati, OH 45202",
    "Phone": "(513) 744-9852",
    "Website": "http://www.zulabistro.com/",
    "hoursMonday": "Closed",
    "hoursTuesday": "5PM–12AM",
    "hoursWednesday": "5PM–12AM",
    "hoursThursday": "5PM–12AM",
    "hoursFriday": "4PM–1AM",
    "hoursSaturday": "4PM–1AM",
    "hoursSunday": "Closed",
    "specialMonday": "",
    "specialTuesday": "",
    "specialWednesday": "",
    "specialThursday": "",
    "specialFriday": "",
    "specialSaturday": "",
    "specialSunday": "",
    "Note": "",
    "lat": 39.11047,
    "long": -84.516829
  },
  {
    "ID": 19,
    "Bar": "Anchor OTR",
    "Description": "Charming seafood eatery with a patio for seasonal outdoor dining & a bar with signature cocktails.",
    "Neighborhood": "Over-the-Rhine",
    "Address": "1401 Race St, Cincinnati, OH 45202",
    "Phone": "(513) 421-8111",
    "Website": "http://www.theanchor-otr.com/",
    "hoursMonday": "Closed",
    "hoursTuesday": "5–10PM",
    "hoursWednesday": "5–10PM",
    "hoursThursday": "5–10PM",
    "hoursFriday": "11:30AM–2:30PM,4:30–11PM",
    "hoursSaturday": "11:30AM–2:30PM,4:30–11PM",
    "hoursSunday": "Closed",
    "specialMonday": "HAPPY HOUR, weeknights from 5 – 7 p.m., $1.50 OYSTERS – SHUCKER’S CHOICE, $1 OFF ALL BEERS + $7 RED, WHITE AND ROSÉ WINES",
    "specialTuesday": "HAPPY HOUR, weeknights from 5 – 7 p.m., $1.50 OYSTERS – SHUCKER’S CHOICE, $1 OFF ALL BEERS + $7 RED, WHITE AND ROSÉ WINES",
    "specialWednesday": "HAPPY HOUR, weeknights from 5 – 7 p.m., $1.50 OYSTERS – SHUCKER’S CHOICE, $1 OFF ALL BEERS + $7 RED, WHITE AND ROSÉ WINES",
    "specialThursday": "HAPPY HOUR, weeknights from 5 – 7 p.m., $1.50 OYSTERS – SHUCKER’S CHOICE, $1 OFF ALL BEERS + $7 RED, WHITE AND ROSÉ WINES",
    "specialFriday": "HAPPY HOUR, weeknights from 5 – 7 p.m., $1.50 OYSTERS – SHUCKER’S CHOICE, $1 OFF ALL BEERS + $7 RED, WHITE AND ROSÉ WINES, Fish Fry Fridays!! 4:30 -9:00, 2 for 1 Draft Beer, $2 Oysters Raw or Oven Roasted, $6  Rum Daiquiris, $12 baskets of Fish & Chios",
    "specialSaturday": "",
    "specialSunday": "",
    "Note": "",
    "lat": 39.1104288,
    "long": -84.5171923
  },
  {
    "ID": 20,
    "Bar": "A Tavola Bar + Trattoria",
    "Description": "Neapolitan pies are wood-fired & served with antipasti & craft cocktails in an industrial-chic room.",
    "Neighborhood": "Over-the-Rhine",
    "Address": "1220 Vine St, Cincinnati, OH 45202",
    "Phone": "(513) 246-0192",
    "Website": "http://www.atavolapizza.com/",
    "hoursMonday": "11AM–10PM",
    "hoursTuesday": "11AM–10PM",
    "hoursWednesday": "11AM–10PM",
    "hoursThursday": "11AM–10PM",
    "hoursFriday": "11AM–12AM",
    "hoursSaturday": "11AM–12AM",
    "hoursSunday": "12–10PM",
    "specialMonday": "",
    "specialTuesday": "",
    "specialWednesday": "",
    "specialThursday": "",
    "specialFriday": "",
    "specialSaturday": "",
    "specialSunday": "",
    "Note": "",
    "lat": 39.1090279,
    "long": -84.5148005
  },
  {
    "ID": 21,
    "Bar": "Nation Kitchen and Bar",
    "Description": "Rustic-chic place with a large beer menu, craft cocktails, gourmet burgers & creative potato sides.",
    "Neighborhood": "Over-the-Rhine",
    "Address": "1200 Broadway St, Cincinnati, OH 45202",
    "Phone": "(513) 381-3794",
    "Website": "http://nationkitchenandbar.com/",
    "hoursMonday": "11AM–12AM",
    "hoursTuesday": "11AM–12AM",
    "hoursWednesday": "11AM–12AM",
    "hoursThursday": "11AM–12AM",
    "hoursFriday": "11AM–2AM",
    "hoursSaturday": "10AM–2AM",
    "hoursSunday": "10AM–12AM",
    "specialMonday": "",
    "specialTuesday": "",
    "specialWednesday": "",
    "specialThursday": "",
    "specialFriday": "",
    "specialSaturday": "",
    "specialSunday": "",
    "Note": "",
    "lat": 39.1097757,
    "long": -84.508276
  },
  {
    "ID": 22,
    "Bar": "The Drinkery",
    "Description": "Unpretentious, brick-lined bar & club featuring a patio, local bands, DJs & craft beers.",
    "Neighborhood": "Over-the-Rhine",
    "Address": "1150 Main St, Cincinnati, OH 45202",
    "Phone": "(513) 509-2574",
    "Website": "http://www.drinkotr.com/",
    "hoursMonday": "4PM–2AM",
    "hoursTuesday": "4PM–2AM",
    "hoursWednesday": "4PM–2AM",
    "hoursThursday": "4PM–2AM",
    "hoursFriday": "4PM–2AM",
    "hoursSaturday": "12PM–2AM",
    "hoursSunday": "12PM–2AM",
    "specialMonday": "",
    "specialTuesday": "",
    "specialWednesday": "",
    "specialThursday": "",
    "specialFriday": "",
    "specialSaturday": "",
    "specialSunday": "",
    "Note": "",
    "lat": 39.1091052,
    "long": -84.5114524
  },
  {
    "ID": 23,
    "Bar": "Senate",
    "Description": "Trendy pub serving gourmet hot dogs with creative toppings, plus local brews & retro cocktails.",
    "Neighborhood": "Over-the-Rhine",
    "Address": "1212 Vine St, Cincinnati, OH 45202",
    "Phone": "(513) 421-2020",
    "Website": "http://www.senatepub.com/",
    "hoursMonday": "Closed",
    "hoursTuesday": "11:30AM–10PM",
    "hoursWednesday": "11:30AM–10PM",
    "hoursThursday": "11:30AM–10PM",
    "hoursFriday": "11:30AM–11PM",
    "hoursSaturday": "11:30AM–11PM",
    "hoursSunday": "Closed",
    "specialMonday": "",
    "specialTuesday": "",
    "specialWednesday": "",
    "specialThursday": "",
    "specialFriday": "",
    "specialSaturday": "",
    "specialSunday": "",
    "Note": "",
    "lat": 39.1087911,
    "long": -84.5147421
  },
  {
    "ID": 24,
    "Bar": "Mr Pitiful's",
    "Description": "Cozy neighborhood bar with diverse entertainment, including sports on TV, live music & DJs.",
    "Neighborhood": "Over-the-Rhine",
    "Address": "1323 Main St, Cincinnati, OH 45202",
    "Phone": "(513) 369-0202",
    "Website": "http://mrpitifulsotr.com/",
    "hoursMonday": "6PM–12AM",
    "hoursTuesday": "5PM–12AM",
    "hoursWednesday": "5PM–1AM",
    "hoursThursday": "5PM–2AM",
    "hoursFriday": "4PM–2AM",
    "hoursSaturday": "5PM–12AM",
    "hoursSunday": "12–8PM",
    "specialMonday": "",
    "specialTuesday": "",
    "specialWednesday": "",
    "specialThursday": "",
    "specialFriday": "",
    "specialSaturday": "",
    "specialSunday": "",
    "Note": "",
    "lat": 39.110617,
    "long": -84.512122
  },
  {
    "ID": 25,
    "Bar": "Vestry at the Transept",
    "Description": "",
    "Neighborhood": "Over-the-Rhine",
    "Address": "1205 Elm St, Cincinnati, OH 45202",
    "Phone": "(513) 841-9999",
    "Website": "http://vestryotr.com/",
    "hoursMonday": "Closed",
    "hoursTuesday": "Closed",
    "hoursWednesday": "4PM–12AM",
    "hoursThursday": "4PM–12AM",
    "hoursFriday": "4PM–2AM",
    "hoursSaturday": "4PM–2AM",
    "hoursSunday": "Closed",
    "specialMonday": "HAPPY HOUR 4P-8P, $4 CALLS, $3 DOMESTICS, $2 OFF DRAFTS, $5 GLASSES OF SPANISH WINE, Monday: “Manhattan Mondays”, $5 Bulleit Manhattans",
    "specialTuesday": "HAPPY HOUR 4P-8P, $4 CALLS, $3 DOMESTICS, $2 OFF DRAFTS, $5 GLASSES OF SPANISH WINE",
    "specialWednesday": "HAPPY HOUR 4P-8P, $4 CALLS, $3 DOMESTICS, $2 OFF DRAFTS, $5 GLASSES OF SPANISH WINE, Wednesday: “Wine Down Wednesdays”, $15 Polus & Maques De Reinosa BottlesHAPPY HOUR 4P-8P, $4 CALLS, $3 DOMESTICS, $2 OFF DRAFTS, $5 GLASSES OF SPANISH WINE, Wednesday: “Wine Down Wednesdays”, $15 Polus & Maques De Reinosa Bottles",
    "specialThursday": "HAPPY HOUR 4P-8P, $4 CALLS, $3 DOMESTICS, $2 OFF DRAFTS, $5 GLASSES OF SPANISH WINE, Thursday: “Thirsty Thursdays”, $4 Craft Cans, $4 Jameson*HAPPY HOUR 4P-8P, $4 CALLS, $3 DOMESTICS, $2 OFF DRAFTS, $5 GLASSES OF SPANISH WINE, Thursday: “Thirsty Thursdays”, $4 Craft Cans, $4 Jameson*",
    "specialFriday": "HAPPY HOUR 4P-8P, $4 CALLS, $3 DOMESTICS, $2 OFF DRAFTS, $5 GLASSES OF SPANISH WINEHAPPY HOUR 4P-8P, $4 CALLS, $3 DOMESTICS, $2 OFF DRAFTS, $5 GLASSES OF SPANISH WINE",
    "specialSaturday": "HAPPY HOUR 4P-8P, $4 CALLS, $3 DOMESTICS, $2 OFF DRAFTS, $5 GLASSES OF SPANISH WINEHAPPY HOUR 4P-8P, $4 CALLS, $3 DOMESTICS, $2 OFF DRAFTS, $5 GLASSES OF SPANISH WINE",
    "specialSunday": "",
    "Note": "",
    "lat": 39.1079009,
    "long": -84.518178
  },
  {
    "ID": 26,
    "Bar": "Wiseguy Lounge",
    "Description": "",
    "Neighborhood": "Over-the-Rhine",
    "Address": "1211 Main St, Cincinnati, OH 45202",
    "Phone": "(513) 381-3625",
    "Website": "http://www.goodfellaspizzeria.com/wiseguy-option-2/",
    "hoursMonday": "11AM–1AM",
    "hoursTuesday": "11AM–1AM",
    "hoursWednesday": "11AM–1AM",
    "hoursThursday": "11AM–2:30AM",
    "hoursFriday": "11AM–2:30AM",
    "hoursSaturday": "11AM–2:30AM",
    "hoursSunday": "11AM–1AM",
    "specialMonday": "",
    "specialTuesday": "",
    "specialWednesday": "",
    "specialThursday": "",
    "specialFriday": "",
    "specialSaturday": "",
    "specialSunday": "",
    "Note": "",
    "lat": 39.1091302,
    "long": -84.5118141
  },
  {
    "ID": 27,
    "Bar": "Revel OTR Urban Winery",
    "Description": "Cozy winery with live music, handcrafted wines & light snacks in rustic-chic digs with live music.",
    "Neighborhood": "Over-the-Rhine",
    "Address": "111 E 12th St, Cincinnati, OH 45202",
    "Phone": "(513) 579-9463",
    "Website": "http://www.revelotr.com/",
    "hoursMonday": "Closed",
    "hoursTuesday": "4PM–12AM",
    "hoursWednesday": "4PM–12AM",
    "hoursThursday": "4PM–12AM",
    "hoursFriday": "4PM–2AM",
    "hoursSaturday": "12PM–2AM",
    "hoursSunday": "Closed",
    "specialMonday": "",
    "specialTuesday": "",
    "specialWednesday": "Happy Hour 4-7 PM, $5 - Wine, Beer, Wine Cocktails, Olives and Cheese, Bread & OilHappy Hour 4-7 PM, $5 - Wine, Beer, Wine Cocktails, Olives and Cheese, Bread & Oil",
    "specialThursday": "Happy Hour 4-7 PM, $5 - Wine, Beer, Wine Cocktails, Olives and Cheese, Bread & OilHappy Hour 4-7 PM, $5 - Wine, Beer, Wine Cocktails, Olives and Cheese, Bread & Oil",
    "specialFriday": "Happy Hour 4-7 PM, $5 - Wine, Beer, Wine Cocktails, Olives and Cheese, Bread & OilHappy Hour 4-7 PM, $5 - Wine, Beer, Wine Cocktails, Olives and Cheese, Bread & Oil",
    "specialSaturday": "",
    "specialSunday": "Sangria Sunday 12-10PM, $7 Red & White Wine Sangrias, Traditional Mimosas, Draft Beers, $5 Limoncello Crema, $4 Limoncello ClassicSangria Sunday 12-10PM, $7 Red & White Wine Sangrias, Traditional Mimosas, Draft Beers, $5 Limoncello Crema, $4 Limoncello Classic",
    "Note": "",
    "lat": 39.1085275,
    "long": -84.5126641
  },
  {
    "ID": 28,
    "Bar": "Kaze",
    "Description": "Gastropub serving sushi & creative Japanese fare in a stylish space, with a lounge & beer garden.",
    "Neighborhood": "Over-the-Rhine",
    "Address": "1400 Vine St, Cincinnati, OH 45202",
    "Phone": "(513) 898-7991",
    "Website": "http://www.kazeotr.com/",
    "hoursMonday": "Closed",
    "hoursTuesday": "4–10PM",
    "hoursWednesday": "4–10PM",
    "hoursThursday": "4–10PM",
    "hoursFriday": "4–11PM",
    "hoursSaturday": "12–11PM",
    "hoursSunday": "12–9PM",
    "specialMonday": "HAPPY HOUR  DAILY - 4-7PM,    • Specialty cocktails are $5,    • Discounted select sushi rolls,    • Ramen is only $4.5",
    "specialTuesday": "HAPPY HOUR  DAILY - 4-7PM, Specialty cocktails are $5, Discounted select sushi rolls, Ramen is only $4.50",
    "specialWednesday": "HAPPY HOUR  DAILY - 4-7PM,    • Specialty cocktails are $5,    • Discounted select sushi rolls,    • Ramen is only $4.5",
    "specialThursday": "HAPPY HOUR  DAILY - 4-7PM,    • Specialty cocktails are $5,    • Discounted select sushi rolls,    • Ramen is only $4.5",
    "specialFriday": "HAPPY HOUR  DAILY - 4-7PM,    • Specialty cocktails are $5,    • Discounted select sushi rolls,    • Ramen is only $4.5",
    "specialSaturday": "HAPPY HOUR  DAILY - 4-6PM,    • Specialty cocktails are $5,    • Discounted select sushi rolls,    • Ramen is only $4.5",
    "specialSunday": "HAPPY HOUR  DAILY - 4-6PM,    • Specialty cocktails are $5,    • Discounted select sushi rolls,    • Ramen is only $4.5",
    "Note": "",
    "lat": 39.1110442,
    "long": -84.5152882
  },
  {
    "ID": 29,
    "Bar": "Ché",
    "Description": "Artisanal Argentine cuisine & empanadas, plus drinks, offered in a rustic, dimly lit dining room.",
    "Neighborhood": "Over-the-Rhine",
    "Address": "1342 Walnut St, Cincinnati, OH 45202",
    "Phone": "(513) 345-8838",
    "Website": "http://www.checincinnati.com/",
    "hoursMonday": "4PM–12AM",
    "hoursTuesday": "11AM–2:30AM",
    "hoursWednesday": "11AM–2:30AM",
    "hoursThursday": "11AM–2:30AM",
    "hoursFriday": "11AM–2:30AM",
    "hoursSaturday": "11AM–2:30AM",
    "hoursSunday": "11AM–12AM",
    "specialMonday": "Malbec Mondays, Come enjoy any of our Malbecs by the glass for only $5 all day long.",
    "specialTuesday": "Service Industry Night, Our friends in the Service Industry enjoy 30% off drinks all night long!, $3 Jack Daniels,",
    "specialWednesday": "Whiskey Wednesday $3, Get over Hump Day by joining us for $3 shots of Jameson all evening long.Whiskey Wednesday $3, Get over Hump Day by joining us for $3 shots of Jameson all evening long.",
    "specialThursday": "Thirsty Thursday$4 Drafts, Beer aficionados unite! Thursday at Ché means it's time for $4 drafts on any of our 20 beers on tap!Thirsty Thursday$4 Drafts, Beer aficionados unite! Thursday at Ché means it's time for $4 drafts on any of our 20 beers on tap!",
    "specialFriday": "Fireball Friday, Ready to start your weekends with a bang? Pop by and joinus for $3 shots of Fireball 'till the wheels fall off!Fireball Friday, Ready to start your weekends with a bang? Pop by and joinus for $3 shots of Fireball 'till the wheels fall off!",
    "specialSaturday": "Weekend Brunch,  Come check in OTR's best kept secret! 10 exclusive menu items, $4 Mimosas, and $5 Bloody Marys., When:, Saturdays and Sundays from  11am to 3pm.",
    "specialSunday": "Weekend Brunch,  Come check in OTR's best kept secret! 10 exclusive menu items, $4 Mimosas, and $5 Bloody Marys., When:, Saturdays and Sundays from  11am to 3pm.",
    "Note": "",
    "lat": 39.1108982,
    "long": -84.5135673
  },
  {
    "ID": 30,
    "Bar": "The Hub",
    "Description": "",
    "Neighborhood": "Over-the-Rhine",
    "Address": "1209 Main St, Cincinnati, OH 45202",
    "Phone": "(513) 746-6572",
    "Website": "http://thehubotr.com/",
    "hoursMonday": "4PM–2AM",
    "hoursTuesday": "2PM–2AM",
    "hoursWednesday": "2PM–2AM",
    "hoursThursday": "2PM–2AM",
    "hoursFriday": "2PM–2AM",
    "hoursSaturday": "2PM–2AM",
    "hoursSunday": "4PM–2AM",
    "specialMonday": "",
    "specialTuesday": "",
    "specialWednesday": "",
    "specialThursday": "",
    "specialFriday": "",
    "specialSaturday": "",
    "specialSunday": "",
    "Note": "",
    "lat": 39.1089554444444,
    "long": -84.51171
  },
  {
    "ID": 31,
    "Bar": "Four Entertainment Group",
    "Description": "",
    "Neighborhood": "Over-the-Rhine",
    "Address": "1404 Vine St, Cincinnati, OH 45202",
    "Phone": "(513) 721-0083",
    "Website": "http://www.foureg.com/",
    "hoursMonday": "10AM–6PM",
    "hoursTuesday": "10AM–6PM",
    "hoursWednesday": "10AM–6PM",
    "hoursThursday": "10AM–6PM",
    "hoursFriday": "10AM–6PM",
    "hoursSaturday": "Closed",
    "hoursSunday": "Closed",
    "specialMonday": "",
    "specialTuesday": "",
    "specialWednesday": "",
    "specialThursday": "",
    "specialFriday": "",
    "specialSaturday": "",
    "specialSunday": "",
    "Note": "",
    "lat": 39.1110911428571,
    "long": -84.5153729591837
  },
  {
    "ID": 32,
    "Bar": "The Mercer OTR",
    "Description": "Varied European-influenced dishes are served in a stylish venue at this modern restaurant.",
    "Neighborhood": "Over-the-Rhine",
    "Address": "1324 Vine St, Cincinnati, OH 45202",
    "Phone": "(513) 421-5111",
    "Website": "http://www.themercerotr.com/",
    "hoursMonday": "Closed",
    "hoursTuesday": "5–10PM",
    "hoursWednesday": "5–10PM",
    "hoursThursday": "5–10PM",
    "hoursFriday": "5–11PM",
    "hoursSaturday": "5–11PM",
    "hoursSunday": "4:30–8:30PM",
    "specialMonday": "",
    "specialTuesday": "Tuesday-Half Price Wine, Bottles of wine up through $74 are 50% off. Wines $75 and up, and wines in half bottles are 25% off.",
    "specialWednesday": "Tuesday-Half Price Wine, Bottles of wine up through $74 are 50% off. Wines $75 and up, and wines in half bottles are 25% off.",
    "specialThursday": "Thursday Bar Burger Night, $10 Burger & Fries, $2 High Life cans, and $2 Coors drafts., **This promotion is only available in the bar, lounge, and patio**",
    "specialFriday": "Friday-Half Price Wine, Bottles of wine up through $74 are 50% off. Wines $75 and up, and wines in half bottles are 25% off.",
    "specialSaturday": "",
    "specialSunday": "Sunday Funday $5 All Night Happy Hour, All night in the bar, lounge, and patio you can enjoy $5 select, cocktails, wines by the glass, and beer specials.",
    "Note": "",
    "lat": 39.1101752,
    "long": -84.5150813
  },
  {
    "ID": 33,
    "Bar": "Pontiac BBQ",
    "Description": "Rustic-chic spot with a vintage vibe offering eclectic BBQ & classic sides, plus creative cocktails.",
    "Neighborhood": "Over-the-Rhine",
    "Address": "1403 Vine St, Cincinnati, OH 45202",
    "Phone": "(513) 579-8500",
    "Website": "http://www.pontiacbbq.com/",
    "hoursMonday": "Closed",
    "hoursTuesday": "11AM–10PM",
    "hoursWednesday": "11AM–10PM",
    "hoursThursday": "11AM–10PM",
    "hoursFriday": "11AM–11PM",
    "hoursSaturday": "11AM–11PM",
    "hoursSunday": "11AM–9PM",
    "specialMonday": "",
    "specialTuesday": "",
    "specialWednesday": "",
    "specialThursday": "",
    "specialFriday": "",
    "specialSaturday": "",
    "specialSunday": "",
    "Note": "",
    "lat": 39.1107045,
    "long": -84.5155743
  },
  {
    "ID": 34,
    "Bar": "THE FUEL LOUNGE OTR",
    "Description": "",
    "Neighborhood": "Over-the-Rhine",
    "Address": "1424 Main St, Cincinnati, OH 45202",
    "Phone": "(513) 344-6274",
    "Website": "",
    "hoursMonday": "Closed",
    "hoursTuesday": "Closed",
    "hoursWednesday": "Closed",
    "hoursThursday": "9PM–1AM",
    "hoursFriday": "9PM–1AM",
    "hoursSaturday": "9PM–1AM",
    "hoursSunday": "Close",
    "specialMonday": "",
    "specialTuesday": "",
    "specialWednesday": "",
    "specialThursday": "",
    "specialFriday": "",
    "specialSaturday": "",
    "specialSunday": "",
    "Note": "",
    "lat": 39.1120257,
    "long": -84.5121277620096
  },
  {
    "ID": 35,
    "Bar": "Please",
    "Description": "Upscale New American kitchen with a rotating, inventive tasting menu, plus a few à la carte options.",
    "Neighborhood": "Over-the-Rhine",
    "Address": "1405 Clay St, Cincinnati, OH 45202",
    "Phone": "(513) 405-8859",
    "Website": "http://www.pleasecincinnati.com/",
    "hoursMonday": "Closed",
    "hoursTuesday": "5:30–10PM",
    "hoursWednesday": "5:30PM–12AM",
    "hoursThursday": "5:30PM–12AM",
    "hoursFriday": "5:30PM–12AM",
    "hoursSaturday": "5:30PM–12AM",
    "hoursSunday": "Closed",
    "specialMonday": "",
    "specialTuesday": "",
    "specialWednesday": "Happy Hour runs Wednesday through Friday 5:30-7:30 with cocktail, wine glass & bottle specials.",
    "specialThursday": "Happy Hour runs Wednesday through Friday 5:30-7:30 with cocktail, wine glass & bottle specials.",
    "specialFriday": "Happy Hour runs Wednesday through Friday 5:30-7:30 with cocktail, wine glass & bottle specials.",
    "specialSaturday": "",
    "specialSunday": "",
    "Note": "",
    "lat": 39.1113753,
    "long": -84.5131298
  },
  {
    "ID": 36,
    "Bar": "The Pony",
    "Description": "",
    "Neighborhood": "Over-the-Rhine",
    "Address": "1346 Main St, Cincinnati, OH 45202",
    "Phone": "(513) 954-8415",
    "Website": "",
    "hoursMonday": "4PM–2AM",
    "hoursTuesday": "4PM–2AM",
    "hoursWednesday": "4PM–2AM",
    "hoursThursday": "4PM–2AM",
    "hoursFriday": "4PM–2AM",
    "hoursSaturday": "12PM–2AM",
    "hoursSunday": "12PM–2AM",
    "specialMonday": "",
    "specialTuesday": "",
    "specialWednesday": "",
    "specialThursday": "",
    "specialFriday": "",
    "specialSaturday": "",
    "specialSunday": "",
    "Note": "",
    "lat": 39.1111356,
    "long": -84.5119275
  },
  {
    "ID": 37,
    "Bar": "The Righteous Room",
    "Description": "Arty nightspot offering beer, wine & cocktails, VIP tables & an open-air lounge with DJ music.",
    "Neighborhood": "Over-the-Rhine",
    "Address": "641 Walnut St, Cincinnati, OH 45202",
    "Phone": "(513) 381-4408",
    "Website": "http://www.therighteousroom.com/",
    "hoursMonday": "4PM–2:30AM",
    "hoursTuesday": "4PM–2:30AM",
    "hoursWednesday": "4PM–2:30AM",
    "hoursThursday": "4PM–2:30AM",
    "hoursFriday": "4PM–2:30AM",
    "hoursSaturday": "4PM–2:30AM",
    "hoursSunday": "8PM–2:30AM",
    "specialMonday": "EVERY DAY, Open – Close, $5 Rosé (Apothic or Bellarouche), $5 Shots of our Infused Liquor of Month, HAPPY HOUR, Monday – Saturday | 4-8pm, 1/2 Off All Drinks, MONDAY, 8pm – Close, $5 Moscow Mules, $5 Paris to Moscows",
    "specialTuesday": "EVERY DAY, Open – Close, $5 Rosé (Apothic or Bellarouche), $5 Shots of our Infused Liquor of Month, HAPPY HOUR, Monday – Saturday | 4-8pm, 1/2 Off All Drinks, TUESDAY, 8pm – Close, $3 Local Canned Beers, $3 Shots of Jameson",
    "specialWednesday": "EVERY DAY, Open – Close, $5 Rosé (Apothic or Bellarouche), $5 Shots of our Infused Liquor of Month, HAPPY HOUR, Monday – Saturday | 4-8pm, 1/2 Off All Drinks, WEDNESDAY, 8pm – Close, Half-price glasses of wine, Half-price bottles of wine",
    "specialThursday": "EVERY DAY, Open – Close, $5 Rosé (Apothic or Bellarouche), $5 Shots of our Infused Liquor of Month, HAPPY HOUR, Monday – Saturday | 4-8pm, 1/2 Off All Drinks, THURSDAY, 8pm – Close, $6 Don Julio Blanco, $7 Don Julio Reposado, $8 Don Julio Añejo, $15 Don Julio 1942",
    "specialFriday": "EVERY DAY, Open – Close, $5 Rosé (Apothic or Bellarouche), $5 Shots of our Infused Liquor of Month, HAPPY HOUR, Monday – Saturday | 4-8pm, 1/2 Off All Drinks",
    "specialSaturday": "EVERY DAY, Open – Close, $5 Rosé (Apothic or Bellarouche), $5 Shots of our Infused Liquor of Month, HAPPY HOUR, Monday – Saturday | 4-8pm, 1/2 Off All Drinks",
    "specialSunday": "EVERY DAY, Open – Close, $5 Rosé (Apothic or Bellarouche), $5 Shots of our Infused Liquor of Month, SUNDAY, 8pm – Close, Reverse Happy Hour, Half-price drinks",
    "Note": "",
    "lat": 39.1035073421053,
    "long": -84.5120170263158
  },
  {
    "ID": 38,
    "Bar": "Rosedale",
    "Description": "",
    "Neighborhood": "Over-the-Rhine",
    "Address": "208 E 12th St, Cincinnati, OH 45202",
    "Phone": "(513) 864-5400",
    "Website": "http://www.rosedaleotr.com/",
    "hoursMonday": "4PM–12:30AM",
    "hoursTuesday": "4PM–2AM",
    "hoursWednesday": "4PM–2AM",
    "hoursThursday": "4PM–2AM",
    "hoursFriday": "4PM–2AM",
    "hoursSaturday": "4PM–2AM",
    "hoursSunday": "4PM–12:30AM",
    "specialMonday": "Monday – Friday: 4pm – 7pm, Half Price Drinks (excluding house cocktails and bottles of wine)",
    "specialTuesday": "Monday – Friday: 4pm – 7pm, Half Price Drinks (excluding house cocktails and bottles of wine)",
    "specialWednesday": "Monday – Friday: 4pm – 7pm, Half Price Drinks (excluding house cocktails and bottles of wine)",
    "specialThursday": "Monday – Friday: 4pm – 7pm, Half Price Drinks (excluding house cocktails and bottles of wine)",
    "specialFriday": "Monday – Friday: 4pm – 7pm, Half Price Drinks (excluding house cocktails and bottles of wine)",
    "specialSaturday": "",
    "specialSunday": "",
    "Note": "",
    "lat": 39.109344,
    "long": -84.511072
  },
  {
    "ID": 39,
    "Bar": "Miltons The Prospect Hill Tavern",
    "Description": "",
    "Neighborhood": "Over-the-Rhine",
    "Address": "301 Milton St, Cincinnati, OH 45202",
    "Phone": "(513) 784-9938",
    "Website": "",
    "hoursMonday": "4PM–2:30AM",
    "hoursTuesday": "4PM–2:30AM",
    "hoursWednesday": "4PM–2:30AM",
    "hoursThursday": "4PM–2:30AM",
    "hoursFriday": "4PM–2:30AM",
    "hoursSaturday": "4PM–2:30AM",
    "hoursSunday": "4PM–2:30AM",
    "specialMonday": "",
    "specialTuesday": "",
    "specialWednesday": "",
    "specialThursday": "",
    "specialFriday": "",
    "specialSaturday": "",
    "specialSunday": "",
    "Note": "",
    "lat": 39.11334,
    "long": -84.509693
  },
  {
    "ID": 40,
    "Bar": "Queen City Exchange",
    "Description": "",
    "Neighborhood": "Over-the-Rhine",
    "Address": "32 W Court St, Cincinnati, OH 45202",
    "Phone": "(513) 954-0395",
    "Website": "http://www.queencityexchange.com/",
    "hoursMonday": "4–10PM",
    "hoursTuesday": "4–11PM",
    "hoursWednesday": "4–11PM",
    "hoursThursday": "4PM–12AM",
    "hoursFriday": "3PM–2AM",
    "hoursSaturday": "12PM–2AM",
    "hoursSunday": "12–10PM",
    "specialMonday": "",
    "specialTuesday": "",
    "specialWednesday": "",
    "specialThursday": "",
    "specialFriday": "",
    "specialSaturday": "",
    "specialSunday": "",
    "Note": "",
    "lat": 39.106282,
    "long": -84.5153191
  },
  {
    "ID": 41,
    "Bar": "Race Inn",
    "Description": "",
    "Neighborhood": "Over-the-Rhine",
    "Address": "1606 Race St, Cincinnati, OH 45202",
    "Phone": "(513) 421-2722",
    "Website": "",
    "hoursMonday": "1–8PM",
    "hoursTuesday": "1–8PM",
    "hoursWednesday": "1–8PM",
    "hoursThursday": "1–8PM",
    "hoursFriday": "1–8PM",
    "hoursSaturday": "1–8PM",
    "hoursSunday": "1–8PM",
    "specialMonday": "",
    "specialTuesday": "",
    "specialWednesday": "",
    "specialThursday": "",
    "specialFriday": "",
    "specialSaturday": "",
    "specialSunday": "",
    "Note": "",
    "lat": 39.1132835,
    "long": -84.5175945
  },
  {
    "ID": 42,
    "Bar": "Mt. Adams Pavilion",
    "Description": "Live bands & DJs perform at this hip dance club in a historic house with 4 decks & city views.",
    "Neighborhood": "Over-the-Rhine",
    "Address": "949 Pavilion St, Cincinnati, OH 45202",
    "Phone": "(513) 744-9200",
    "Website": "http://www.mountadamspavilion.com/",
    "hoursMonday": "Closed",
    "hoursTuesday": "Closed",
    "hoursWednesday": "6PM–2:30AM",
    "hoursThursday": "6PM–2:30AM",
    "hoursFriday": "6PM–2:30AM",
    "hoursSaturday": "6PM–2:30AM",
    "hoursSunday": "Closed",
    "specialMonday": "",
    "specialTuesday": "",
    "specialWednesday": "HAPPY HOUR, Wed – Fri, 6pm – 8pm, $2.50 Domestics*, $3 Imports*, $5 Margaritas (frozen or rocks), WEDNESDAY, 6pm – 9pm, Extended Happy Hour, , 10pm – Close (Employee Discount Night), $2 off all drinks!",
    "specialThursday": "HAPPY HOUR, Wed – Fri, 6pm – 8pm, $2.50 Domestics*, $3 Imports*, $5 Margaritas (frozen or rocks), THURSDAY, After 9pm, $2 Bud Light Aluminum Bottles, $3 Margaritas, $4 Long Islands, $4 Fireball Whisky",
    "specialFriday": "HAPPY HOUR, Wed – Fri, 6pm – 8pm, $2.50 Domestics*, $3 Imports*, $5 Margaritas (frozen or rocks)",
    "specialSaturday": "",
    "specialSunday": "",
    "Note": "",
    "lat": 39.1075596666667,
    "long": -84.4971821111111
  },
  {
    "ID": 43,
    "Bar": "Symphony Hotel Jazz Lounge",
    "Description": "",
    "Neighborhood": "Over-the-Rhine",
    "Address": "210 W 14th St, Cincinnati, OH 45202",
    "Phone": "(513) 721-3353",
    "Website": "http://www.symphonyhotel.com/jazz-bar/",
    "hoursMonday": "Closed",
    "hoursTuesday": "Closed",
    "hoursWednesday": "Closed",
    "hoursThursday": "7–10PM",
    "hoursFriday": "8–11PM",
    "hoursSaturday": "8–11PM",
    "hoursSunday": "Closed",
    "specialMonday": "",
    "specialTuesday": "",
    "specialWednesday": "",
    "specialThursday": "",
    "specialFriday": "",
    "specialSaturday": "",
    "specialSunday": "",
    "Note": "",
    "lat": 39.1101737,
    "long": -84.5192065
  },
  {
    "ID": 44,
    "Bar": "Maplewood Kitchen and Bar",
    "Description": "Spacious cafe for Californian cuisine for breakfast through dinner amid wooden tables & greenery.",
    "Neighborhood": "Over-the-Rhine",
    "Address": "525 Race St, Cincinnati, OH 45202",
    "Phone": "(513) 421-2100",
    "Website": "http://www.maplewoodkitchenandbar.com/",
    "hoursMonday": "7AM–9PM",
    "hoursTuesday": "7AM–9PM",
    "hoursWednesday": "7AM–9PM",
    "hoursThursday": "7AM–9PM",
    "hoursFriday": "7AM–10PM",
    "hoursSaturday": "8AM–10PM",
    "hoursSunday": "8AM–9PM",
    "specialMonday": "",
    "specialTuesday": "",
    "specialWednesday": "",
    "specialThursday": "",
    "specialFriday": "",
    "specialSaturday": "",
    "specialSunday": "",
    "Note": "",
    "lat": 39.1018325,
    "long": -84.5151463
  },
  {
    "ID": 45,
    "Bar": "OTR LIVE",
    "Description": "",
    "Neighborhood": "Over-the-Rhine",
    "Address": "209 E 12th St, Cincinnati, OH 45202",
    "Phone": "(513) 421-5483",
    "Website": "http://otrlivemusic.com/",
    "hoursMonday": "9AM–4AM",
    "hoursTuesday": "9AM–4AM",
    "hoursWednesday": "9AM–4AM",
    "hoursThursday": "9AM–4AM",
    "hoursFriday": "9AM–4AM",
    "hoursSaturday": "9AM–4AM",
    "hoursSunday": "9AM–4AM",
    "specialMonday": "",
    "specialTuesday": "",
    "specialWednesday": "",
    "specialThursday": "",
    "specialFriday": "",
    "specialSaturday": "",
    "specialSunday": "",
    "Note": "",
    "lat": 39.10939695,
    "long": -84.5110322267084
  },
  {
    "ID": 46,
    "Bar": "Igby's",
    "Description": "Expansive, multifloor lounge with wood-planked walls, craft cocktails, small plates & a hip vibe.",
    "Neighborhood": "Over-the-Rhine",
    "Address": "122 E 6th St, Cincinnati, OH 45202",
    "Phone": "(513) 246-4396",
    "Website": "http://igbysbar.com/",
    "hoursMonday": "4PM–12AM",
    "hoursTuesday": "4PM–12AM",
    "hoursWednesday": "4PM–12AM",
    "hoursThursday": "4PM–12AM",
    "hoursFriday": "4PM–12AM",
    "hoursSaturday": "4PM–12AM",
    "hoursSunday": "Closed",
    "specialMonday": "HAPPY HOUR, Monday – Friday 4pm – 8pm, Saturday 4pm – 6pm, $5 Drafts, $5 Select Calls, $5 Glasses of Dark Horse Wine, MONDAY, 8pm – Close, Half-price all wine & $15 charcuterie board, *Rare exclusions apply",
    "specialTuesday": "HAPPY HOUR, Monday – Friday 4pm – 8pm, Saturday 4pm – 6pm, $5 Drafts, $5 Select Calls, $5 Glasses of Dark Horse Wine, TUESDAY, 8pm – Close, $3 off all craft cocktails",
    "specialWednesday": "HAPPY HOUR, Monday – Friday 4pm – 8pm, Saturday 4pm – 6pm, $5 Drafts, $5 Select Calls, $5 Glasses of Dark Horse Wine, WEDNESDAY, 8pm – Close, $3 beers (drafts, bottles, & cans) & $3 wells, *Rare exclusions apply",
    "specialThursday": "HAPPY HOUR, Monday – Friday 4pm – 8pm, Saturday 4pm – 6pm, $5 Drafts, $5 Select Calls, $5 Glasses of Dark Horse Wine, THURSDAY, 8pm – Close, $3 off all tequila & “Kill the Keg”, Finish off the last of our designated keg and receive a $25 gift card!",
    "specialFriday": "HAPPY HOUR, Monday – Friday 4pm – 8pm, Saturday 4pm – 6pm, $5 Drafts, $5 Select Calls, $5 Glasses of Dark Horse Wine, FRIDAY, 8pm – Close, $100 bottle service bottles, (Tito’s Handmade Vodka, El Jimador Tequila, Tanqueray Gin, Old Forester Whiskey, & Captain Morgan White Rum)",
    "specialSaturday": "",
    "specialSunday": "",
    "Note": "",
    "lat": 39.1028889633675,
    "long": -84.5109204945222
  },
  {
    "ID": 47,
    "Bar": "Shooks - Bar & Dance",
    "Description": "",
    "Neighborhood": "Over-the-Rhine",
    "Address": "920 Race St, Cincinnati, OH 45202",
    "Phone": "(513) 600-0990",
    "Website": "https://m.facebook.com/Shooks920/",
    "hoursMonday": "Closed",
    "hoursTuesday": "Closed",
    "hoursWednesday": "Closed",
    "hoursThursday": "8PM–2:30AM",
    "hoursFriday": "8PM–2:30AM",
    "hoursSaturday": "8PM–2:30AM",
    "hoursSunday": "Closed",
    "specialMonday": "",
    "specialTuesday": "",
    "specialWednesday": "",
    "specialThursday": "",
    "specialFriday": "",
    "specialSaturday": "",
    "specialSunday": "",
    "Note": "",
    "lat": 39.105299,
    "long": -84.5156075714286
  },
  {
    "ID": 48,
    "Bar": "Knockback Nats",
    "Description": "Easygoing game-day hangout with a long bar, typical pub fare & shuffleboard, plus a small patio.",
    "Neighborhood": "Over-the-Rhine",
    "Address": "10 W 7th St, Cincinnati, OH 45202",
    "Phone": "(513) 621-1000",
    "Website": "https://www.facebook.com/Knockback-Nats-Neighborhood-Bar-146296676362/",
    "hoursMonday": "2PM–2AM",
    "hoursTuesday": "2PM–2AM",
    "hoursWednesday": "2PM–2AM",
    "hoursThursday": "2PM–2AM",
    "hoursFriday": "2PM–2AM",
    "hoursSaturday": "12PM–2AM",
    "hoursSunday": "12PM–2AM",
    "specialMonday": "",
    "specialTuesday": "",
    "specialWednesday": "",
    "specialThursday": "",
    "specialFriday": "",
    "specialSaturday": "",
    "specialSunday": "",
    "Note": "",
    "lat": 39.1038396,
    "long": -84.5141989
  },
  {
    "ID": 49,
    "Bar": "Nicholson's Tavern & Pub",
    "Description": "Men in kilts serve a Scottish-American gastropub menu with beer & brown spirits plus live music.",
    "Neighborhood": "Over-the-Rhine",
    "Address": "625 Walnut St, Cincinnati, OH 45202",
    "Phone": "(513) 564-9111",
    "Website": "http://www.nicholsonspub.com/",
    "hoursMonday": "11AM–11PM",
    "hoursTuesday": "11AM–11PM",
    "hoursWednesday": "11AM–11PM",
    "hoursThursday": "11AM–11PM",
    "hoursFriday": "11AM–1AM",
    "hoursSaturday": "11AM–1AM",
    "hoursSunday": "11AM–9PM",
    "specialMonday": "",
    "specialTuesday": "",
    "specialWednesday": "",
    "specialThursday": "",
    "specialFriday": "",
    "specialSaturday": "",
    "specialSunday": "",
    "Note": "",
    "lat": 39.1031773,
    "long": -84.5120802
  },
  {
    "ID": 50,
    "Bar": "Corkopolis",
    "Description": "",
    "Neighborhood": "Over-the-Rhine",
    "Address": "640 Main St, Cincinnati, OH 45202",
    "Phone": "(513) 381-3752",
    "Website": "http://www.corkopolis.com/",
    "hoursMonday": "11AM–10PM",
    "hoursTuesday": "11AM–10PM",
    "hoursWednesday": "11AM–10PM",
    "hoursThursday": "11AM–10PM",
    "hoursFriday": "11AM–11PM",
    "hoursSaturday": "11AM–11PM",
    "hoursSunday": "Closed",
    "specialMonday": "",
    "specialTuesday": "",
    "specialWednesday": "",
    "specialThursday": "",
    "specialFriday": "",
    "specialSaturday": "",
    "specialSunday": "",
    "Note": "",
    "lat": 39.1039354,
    "long": -84.5100858
  },
  {
    "ID": 51,
    "Bar": "Metropole",
    "Description": "Chic American outfit serving seasonal, fireplace-cooked cuisine & cocktails in the 21c Museum Hotel.",
    "Neighborhood": "Over-the-Rhine",
    "Address": "609 Walnut St, Cincinnati, OH 45202",
    "Phone": "(513) 578-6660",
    "Website": "http://metropoleonwalnut.com/",
    "hoursMonday": "7AM–10PM",
    "hoursTuesday": "7AM–10PM",
    "hoursWednesday": "7AM–10PM",
    "hoursThursday": "7AM–10PM",
    "hoursFriday": "7AM–11PM",
    "hoursSaturday": "7AM–11PM",
    "hoursSunday": "7AM–10PM",
    "specialMonday": "",
    "specialTuesday": "",
    "specialWednesday": "",
    "specialThursday": "",
    "specialFriday": "",
    "specialSaturday": "",
    "specialSunday": "",
    "Note": "",
    "lat": 39.1031016,
    "long": -84.5120392
  },
  {
    "ID": 52,
    "Bar": "The Blind Lemon",
    "Description": "Whimsical bar, named after bluesman Blind Lemon Jefferson, with live music & lots of cocktails.",
    "Neighborhood": "Over-the-Rhine",
    "Address": "936 Hatch St, Cincinnati, OH 45202",
    "Phone": "(513) 241-3885",
    "Website": "http://www.theblindlemon.com/",
    "hoursMonday": "5:30PM–2:30AM",
    "hoursTuesday": "5:30PM–2:30AM",
    "hoursWednesday": "5:30PM–2:30AM",
    "hoursThursday": "5:30PM–2:30AM",
    "hoursFriday": "5:30PM–2:30AM",
    "hoursSaturday": "3PM–2:30AM",
    "hoursSunday": "3PM–2:30AM",
    "specialMonday": "",
    "specialTuesday": "",
    "specialWednesday": "",
    "specialThursday": "",
    "specialFriday": "",
    "specialSaturday": "",
    "specialSunday": "",
    "Note": "",
    "lat": 39.109372,
    "long": -84.497458
  },
  {
    "ID": 53,
    "Bar": "Scene Ultra Lounge",
    "Description": "Boisterous nightspot with craft beers, cocktails, DJs, a dance floor & TVs for sports fans.",
    "Neighborhood": "Over-the-Rhine",
    "Address": "637 Walnut St, Cincinnati, OH 45202",
    "Phone": "(513) 381-4327",
    "Website": "http://www.scenecinci.com/",
    "hoursMonday": "Closed",
    "hoursTuesday": "4PM–2AM",
    "hoursWednesday": "4PM–2AM",
    "hoursThursday": "4PM–2AM",
    "hoursFriday": "4PM–2AM",
    "hoursSaturday": "4PM–2AM",
    "hoursSunday": "Closed",
    "specialMonday": "Half Price Happy Hour 4-8PM",
    "specialTuesday": "Half Price Happy Hour 4-8PM",
    "specialWednesday": "Half Price Happy Hour 4-8PM",
    "specialThursday": "Half Price Happy Hour 4-8PM",
    "specialFriday": "Half Price Happy Hour 4-8PM",
    "specialSaturday": "Half Price Happy Hour 4-8PM",
    "specialSunday": "Half Price Happy Hour 4-8PM",
    "Note": "",
    "lat": 39.1034877105263,
    "long": -84.5120121315789
  },
  {
    "ID": 54,
    "Bar": "Tokyo Kitty",
    "Description": "",
    "Neighborhood": "Over-the-Rhine",
    "Address": "575 Race St, Cincinnati, OH 45202",
    "Phone": "(513) 744-0909",
    "Website": "http://thattokyobar.com/",
    "hoursMonday": "5PM–2AM",
    "hoursTuesday": "5PM–2AM",
    "hoursWednesday": "5PM–2AM",
    "hoursThursday": "5PM–2AM",
    "hoursFriday": "5PM–2AM",
    "hoursSaturday": "5PM–2AM",
    "hoursSunday": "5PM–2AM",
    "specialMonday": "",
    "specialTuesday": "",
    "specialWednesday": "",
    "specialThursday": "",
    "specialFriday": "",
    "specialSaturday": "",
    "specialSunday": "",
    "Note": "",
    "lat": 39.1020465,
    "long": -84.5150943
  },
  {
    "ID": 55,
    "Bar": "The Cricket Lounge",
    "Description": "Cincinnatian Hotel lounge for American eats, cocktails & a daily happy hour in relaxed environs.",
    "Neighborhood": "Over-the-Rhine",
    "Address": "601 Vine St, Cincinnati, OH 45202",
    "Phone": "(513) 381-3000",
    "Website": "http://www.cincinnatianhotel.com/dining_cricketlounge.aspx",
    "hoursMonday": "11:30AM–1AM",
    "hoursTuesday": "11:30AM–1AM",
    "hoursWednesday": "11:30AM–1AM",
    "hoursThursday": "11:30AM–1AM",
    "hoursFriday": "11:30AM–1AM",
    "hoursSaturday": "11:30AM–1AM",
    "hoursSunday": "11:30AM–1AM",
    "specialMonday": "",
    "specialTuesday": "",
    "specialWednesday": "",
    "specialThursday": "",
    "specialFriday": "",
    "specialSaturday": "",
    "specialSunday": "",
    "Note": "",
    "lat": 39.102544,
    "long": -84.513429
  },
  {
    "ID": 56,
    "Bar": "Top of the Park at The Phelps",
    "Description": "Open-air lounge atop the Marriott Residence Inn, with cocktails, light bites & sweeping city views.",
    "Neighborhood": "Over-the-Rhine",
    "Address": "506 E 4th St, Cincinnati, OH 45202",
    "Phone": "(513) 651-1234",
    "Website": "http://www.topoftheparkcincinnati.com/",
    "hoursMonday": "5–10PM",
    "hoursTuesday": "5–10PM",
    "hoursWednesday": "5–10PM",
    "hoursThursday": "5–10PM",
    "hoursFriday": "4–11PM",
    "hoursSaturday": "4–11PM",
    "hoursSunday": "Closed",
    "specialMonday": "",
    "specialTuesday": "",
    "specialWednesday": "",
    "specialThursday": "",
    "specialFriday": "",
    "specialSaturday": "",
    "specialSunday": "",
    "Note": "",
    "lat": 39.1025707727273,
    "long": -84.5019645
  },
  {
    "ID": 57,
    "Bar": "Hightail",
    "Description": "",
    "Neighborhood": "Over-the-Rhine",
    "Address": "941 Pavilion St, Cincinnati, OH 45202",
    "Phone": "(513) 229-9980",
    "Website": "http://www.hightailmtadams.com/",
    "hoursMonday": "Closed",
    "hoursTuesday": "4PM–2:30AM",
    "hoursWednesday": "4PM–2:30AM",
    "hoursThursday": "4PM–2:30AM",
    "hoursFriday": "3PM–2:30AM",
    "hoursSaturday": "4PM–2:30AM",
    "hoursSunday": "4PM–12AM",
    "specialMonday": "",
    "specialTuesday": "Tues – Thurs, 4PM – 6PM, Friday, 3PM – 6PM, Half-price drinks, (excluding wine)",
    "specialWednesday": "Tues – Thurs, 4PM – 6PM, Friday, 3PM – 6PM, Half-price drinks, (excluding wine)",
    "specialThursday": "Tues – Thurs, 4PM – 6PM, Friday, 3PM – 6PM, Half-price drinks, (excluding wine), Decked Out, Every Thursday, $2 off drafts, $5 bombs, Card games available",
    "specialFriday": "Every Sunday, 7PM – 9PM, Dog-friendly yappy hour. Half-price drinks and dog treats / swag available while supplies last.",
    "specialSaturday": "",
    "specialSunday": "",
    "Note": "",
    "lat": 39.1075645555556,
    "long": -84.4972489259259
  },
  {
    "ID": 58,
    "Bar": "Holy Grail Tavern & Grille",
    "Description": "Large sports bar by Great American Ball Park with 30+ TVs & a menu of burgers, pizza & sandwiches.",
    "Neighborhood": "Banks",
    "Address": "161 Joe Nuxhall Way, Cincinnati, OH 45202",
    "Phone": "(513) 621-2222",
    "Website": "http://www.holygrailcincy.com/html/banks/banks.php",
    "hoursMonday": "11AM–2:30AM",
    "hoursTuesday": "11AM–2:30AM",
    "hoursWednesday": "11AM–2:30AM",
    "hoursThursday": "11AM–2:30AM",
    "hoursFriday": "11AM–2:30AM",
    "hoursSaturday": "11AM–2:30AM",
    "hoursSunday": "11AM–2:30AM",
    "specialMonday": "",
    "specialTuesday": "",
    "specialWednesday": "",
    "specialThursday": "",
    "specialFriday": "",
    "specialSaturday": "",
    "specialSunday": "",
    "Note": "All UC and Xavier televised basketball games 5 for $10 domestic buckets",
    "lat": 39.0975783,
    "long": -84.5090142
  },
  {
    "ID": 59,
    "Bar": "The Stretch",
    "Description": "",
    "Neighborhood": "Banks",
    "Address": "191 E Freedom Way, Cincinnati, OH 45202",
    "Phone": "(513) 229-9065",
    "Website": "http://www.thestretchcincy.com/",
    "hoursMonday": "3PM–2:30AM",
    "hoursTuesday": "3PM–2:30AM",
    "hoursWednesday": "3PM–2:30AM",
    "hoursThursday": "3PM–2:30AM",
    "hoursFriday": "3PM–2:30AM",
    "hoursSaturday": "3PM–2:30AM",
    "hoursSunday": "3PM–2:30AM",
    "specialMonday": "Happy Hour, (Monday – Friday from 3pm – 7pm), 1/2 off all drafts (includes beer, wine, and cocktails) and $2 off select calls, Mondays, Half-price draft cocktails",
    "specialTuesday": "Happy Hour, (Monday – Friday from 3pm – 7pm), 1/2 off all drafts (includes beer, wine, and cocktails) and $2 off select calls",
    "specialWednesday": "Happy Hour, (Monday – Friday from 3pm – 7pm), 1/2 off all drafts (includes beer, wine, and cocktails) and $2 off select calls",
    "specialThursday": "Happy Hour, (Monday – Friday from 3pm – 7pm), 1/2 off all drafts (includes beer, wine, and cocktails) and $2 off select calls",
    "specialFriday": "Happy Hour, (Monday – Friday from 3pm – 7pm), 1/2 off all drafts (includes beer, wine, and cocktails) and $2 off select calls",
    "specialSaturday": "",
    "specialSunday": "Sunday Fundays, After 6PM, $4 drafts, $4 bombs, $4 Rumpleminze, $4 Fireball",
    "Note": "",
    "lat": 39.097176,
    "long": -84.5093324
  },
  {
    "ID": 60,
    "Bar": "Tin Roof",
    "Description": "Unpretentious shotgun shack bar & music venue with creative takes on American pub food.",
    "Neighborhood": "Banks",
    "Address": "160 E Freedom Way #150, Cincinnati, OH 45202",
    "Phone": "(513) 381-2176",
    "Website": "http://tinroofcincinnati.com/",
    "hoursMonday": "11AM–3AM",
    "hoursTuesday": "11AM–3AM",
    "hoursWednesday": "11AM–3AM",
    "hoursThursday": "11AM–3AM",
    "hoursFriday": "11AM–3AM",
    "hoursSaturday": "11AM–3AM",
    "hoursSunday": "11AM–3AM",
    "specialMonday": "Monday:  $1 Local Beers, HAPPY HOUR, Monday - Friday  2PM - 7PM, $2 Domestic Drafts, $3 Import Drafts, $3.5 Locals Draft , $3 Wells, $2 off House Wines",
    "specialTuesday": "Tuesday:  50% off for Industry $3 DosXX 16oz Cans , HAPPY HOUR, Monday - Friday  2PM - 7PM, $2 Domestic Drafts, $3 Import Drafts, $3.5 Locals Draft , $3 Wells, $2 off House Wines",
    "specialWednesday": "Wednesday: $5 Domestic 32 Oz Drafts, HAPPY HOUR, Monday - Friday  2PM - 7PM, $2 Domestic Drafts, $3 Import Drafts, $3.5 Locals Draft , $3 Wells, $2 off House Wines",
    "specialThursday": "Thursday: $3 Wells, $3 Fireball all night , HAPPY HOUR, Monday - Friday  2PM - 7PM, $2 Domestic Drafts, $3 Import Drafts, $3.5 Locals Draft , $3 Wells, $2 off House Wines",
    "specialFriday": "Friday:  $3 PBR Tall Boys, $4 House Shots , HAPPY HOUR, Monday - Friday  2PM - 7PM, $2 Domestic Drafts, $3 Import Drafts, $3.5 Locals Draft , $3 Wells, $2 off House Wines",
    "specialSaturday": "Saturday:  5 for $15 Bud Light Buckets till 5pm, $3 PBR Tall Boys, $4 House Shots",
    "specialSunday": "Sunday:  $15 Bottomles Mimosas,  $5 Bloody Mary's",
    "Note": "",
    "lat": 39.097524,
    "long": -84.509556
  },
  {
    "ID": 61,
    "Bar": "O'Malleys In the Alley",
    "Description": "Long-standing Irish pub offering sports on TV & classic bar fare such as burgers & sandwiches.",
    "Neighborhood": "Banks",
    "Address": "25 W Ogden Pl, Cincinnati, OH 45202",
    "Phone": "(513) 381-3114",
    "Website": "http://www.omalleyscincy.com/",
    "hoursMonday": "11AM–2AM",
    "hoursTuesday": "11AM–2AM",
    "hoursWednesday": "11AM–2AM",
    "hoursThursday": "11AM–2AM",
    "hoursFriday": "11AM–2AM",
    "hoursSaturday": "11AM–2AM",
    "hoursSunday": "11AM–2AM",
    "specialMonday": "ABSOLUTELY MONDAY, Looking for a way to bounce back from a long Monday at work? Come enjoy $4 Absolut drinks any way ya want ’em all day long. Service industry professionals enjoy 30% off drinks from 3 pm to close.",
    "specialTuesday": "TORCHED TUESDAYS, Looking to light up your night? We’ve got the “hot” ticket right here, with $2 shots of Fireball all night long.",
    "specialWednesday": "WHISKEY WEDNESDAY, Get over the hump with specials like $2 Jameson shots or $3 Guinness pints, or put that pinky out and enjoy a glass of any house vino for only $3!",
    "specialThursday": "CRAFT CAN THURSDAY, Come get Crafty with us on Thursdays, when all craft cans are only $3 all day long. Snag a shot of Jagermeister for $3 or make it a Bomb for only $5.",
    "specialFriday": "BOMBS AWAY! FRIDAY, What better way to tackle the weekend head-on than slamming down $3 Vegas Bombs from 3 pm to close? Nothing coming to mind? We didn’t think so. Get in here, already!",
    "specialSaturday": "CAR BOMB CHAOS SATURDAY, The weekend is in full swing, so let’s blow it up with $5 Car Bombs all day long.",
    "specialSunday": "SERVICE INDUSTRY SUNDAY, Service Industry friends enjoy 30% off drinks all day. We also feature Clark’s Famous Furknocker Bloody Marys for $4. Snag a pitcher of draft beer for only $10.50 All. Day. Long.",
    "Note": "",
    "lat": 39.099223,
    "long": -84.513532
  },
  {
    "ID": 62,
    "Bar": "Moerlein Lager House",
    "Description": "Artifact-adorned beer bar with New American fare & river views from a wraparound patio.",
    "Neighborhood": "Banks",
    "Address": "115 Joe Nuxhall Way, Cincinnati, OH 45202",
    "Phone": "(513) 421-2337",
    "Website": "http://www.moerleinlagerhouse.com/",
    "hoursMonday": "11AM–12AM",
    "hoursTuesday": "11AM–12AM",
    "hoursWednesday": "11AM–12AM",
    "hoursThursday": "11AM–12AM",
    "hoursFriday": "11AM–1AM",
    "hoursSaturday": "11AM–1AM",
    "hoursSunday": "11AM–11PM",
    "specialMonday": "",
    "specialTuesday": "",
    "specialWednesday": "",
    "specialThursday": "",
    "specialFriday": "",
    "specialSaturday": "",
    "specialSunday": "",
    "Note": "",
    "lat": 39.09630095,
    "long": -84.5087167704914
  },
  {
    "ID": 63,
    "Bar": "JerZees Pub & Grub",
    "Description": "Hangout serving bar fare & drinks in a space with several TVs, patio seating & frequent live music.",
    "Neighborhood": "Oakley",
    "Address": "708 Monmouth St, Newport, KY 41071",
    "Phone": "(859) 491-3500",
    "Website": "http://jerzeespub.com/",
    "hoursMonday": "11AM–2AM",
    "hoursTuesday": "11AM–2AM",
    "hoursWednesday": "11AM–2AM",
    "hoursThursday": "11AM–2AM",
    "hoursFriday": "11AM–2AM",
    "hoursSaturday": "11AM–2AM",
    "hoursSunday": "11AM–2AM",
    "specialMonday": "",
    "specialTuesday": "",
    "specialWednesday": "",
    "specialThursday": "",
    "specialFriday": "",
    "specialSaturday": "",
    "specialSunday": "",
    "Note": "",
    "lat": 39.0901104046977,
    "long": -84.4923346489161
  },
  {
    "ID": 64,
    "Bar": "Oakley Pub & Grill",
    "Description": "This cozy, casual pub with a heated patio serves American food with creative twists.",
    "Neighborhood": "Oakley",
    "Address": "3924 Isabella Ave, Cincinnati, OH 45209",
    "Phone": "(513) 531-2500",
    "Website": "http://oakleypubandgrill.com/",
    "hoursMonday": "11AM–12AM",
    "hoursTuesday": "11AM–12AM",
    "hoursWednesday": "11AM–12AM",
    "hoursThursday": "11AM–2:30AM",
    "hoursFriday": "11AM–2:30AM",
    "hoursSaturday": "11:30AM–2:30AM",
    "hoursSunday": "11:30AM–12AM",
    "specialMonday": "69 cent wings Dine-In Only, Happy Hour Food & Drink Specials 3-6PM & 9PM - Close",
    "specialTuesday": "7.95 Buffalo Chicken Wrap, Happy Hour Food & Drink Specials 3-6PM & 9PM - Close",
    "specialWednesday": "7.95 Burger Mania, Happy Hour Food & Drink Specials 3-6PM & 9PM - Close",
    "specialThursday": "8.95 Pulled Pork BBQ, Happy Hour Food & Drink Specials 3-6PM & 9PM - Close",
    "specialFriday": "7.95 Fish Fillet & Fish Tacos, Happy Hour Food & Drink Specials 3-6PM & 9PM - Close",
    "specialSaturday": "Chef's Special, Happy Hour Food & Drink Specials 3-6PM & 9PM - Close",
    "specialSunday": "Chef's Special, Happy Hour Food & Drink Specials 3-6PM & 9PM - Close",
    "Note": "",
    "lat": 39.15136225,
    "long": -84.4320140420265
  },
  {
    "ID": 65,
    "Bar": "Oak Tavern",
    "Description": "Unpretentious sports bar with patio seating & multiple TVs, plus a menu of wings & other pub fare.",
    "Neighborhood": "Oakley",
    "Address": "3089 Madison Rd, Cincinnati, OH 45209",
    "Phone": "(513) 321-6258",
    "Website": "http://www.oaktavernoakley.com/",
    "hoursMonday": "11AM–11PM",
    "hoursTuesday": "11AM–11PM",
    "hoursWednesday": "11AM–11PM",
    "hoursThursday": "11AM–11PM",
    "hoursFriday": "11AM–12AM",
    "hoursSaturday": "11AM–12AM",
    "hoursSunday": "11AM–11PM",
    "specialMonday": "",
    "specialTuesday": "",
    "specialWednesday": "",
    "specialThursday": "",
    "specialFriday": "",
    "specialSaturday": "",
    "specialSunday": "",
    "Note": "",
    "lat": 39.1525388,
    "long": -84.4306678797942
  },
  {
    "ID": 66,
    "Bar": "Slammer's Lounge",
    "Description": "",
    "Neighborhood": "Oakley",
    "Address": "3239 Brotherton Rd, Cincinnati, OH 45209",
    "Phone": "(513) 871-6847",
    "Website": "",
    "hoursMonday": "11AM–2:30AM",
    "hoursTuesday": "11AM–2:30AM",
    "hoursWednesday": "11AM–2:30AM",
    "hoursThursday": "11AM–2:30AM",
    "hoursFriday": "11AM–2:30AM",
    "hoursSaturday": "11AM–2:30AM",
    "hoursSunday": "12PM–2:30AM",
    "specialMonday": "",
    "specialTuesday": "",
    "specialWednesday": "",
    "specialThursday": "",
    "specialFriday": "",
    "specialSaturday": "",
    "specialSunday": "",
    "Note": "",
    "lat": 39.1539138586247,
    "long": -84.4266419468094
  },
  {
    "ID": 67,
    "Bar": "Habits Café",
    "Description": "Hangout for American eats, craft brews & wine with seasonal outdoor seating & weekly live music.",
    "Neighborhood": "Oakley",
    "Address": "3036 Madison Rd, Cincinnati, OH 45209",
    "Phone": "(513) 631-8367",
    "Website": "http://www.habitscafe.com/",
    "hoursMonday": "11AM–2:30AM",
    "hoursTuesday": "11AM–2:30AM",
    "hoursWednesday": "11AM–2:30AM",
    "hoursThursday": "11AM–2:30AM",
    "hoursFriday": "11AM–2:30AM",
    "hoursSaturday": "9AM–2:30AM",
    "hoursSunday": "9AM–2:30AM",
    "specialMonday": "",
    "specialTuesday": "",
    "specialWednesday": "",
    "specialThursday": "",
    "specialFriday": "",
    "specialSaturday": "",
    "specialSunday": "",
    "Note": "",
    "lat": 39.1517762,
    "long": -84.4328744
  },
  {
    "ID": 68,
    "Bar": "Bar Louie",
    "Description": "Upbeat grill chain with American grub, martinis & microbrews, plus happy-hour deals.",
    "Neighborhood": "Oakley",
    "Address": "3100 Vandercar Way, Cincinnati, OH 45209",
    "Phone": "(513) 351-1453",
    "Website": "http://barlouie.com/locations/states/ohio/oakley-station?utm_source=google&utm_medium=listings",
    "hoursMonday": "11AM–2AM",
    "hoursTuesday": "11AM–2AM",
    "hoursWednesday": "11AM–2AM",
    "hoursThursday": "11AM–2AM",
    "hoursFriday": "11AM–2AM",
    "hoursSaturday": "11AM–2AM",
    "hoursSunday": "11AM–2AM",
    "specialMonday": "HAPPY HOUR, Monday-Friday, 4pm-7pm, $3.50 Drafts, $4.50 Wines, $5.50 Signature Martinis, Half Price Select Apps, and Flatbreads",
    "specialTuesday": "HAPPY HOUR, Monday-Friday, 4pm-7pm, $3.50 Drafts, $4.50 Wines, $5.50 Signature Martinis, Half Price Select Apps, and Flatbreads",
    "specialWednesday": "HAPPY HOUR, Monday-Friday, 4pm-7pm, $3.50 Drafts, $4.50 Wines, $5.50 Signature Martinis, Half Price Select Apps, and Flatbreads",
    "specialThursday": "HAPPY HOUR, Monday-Friday, 4pm-7pm, $3.50 Drafts, $4.50 Wines, $5.50 Signature Martinis, Half Price Select Apps, and Flatbreads",
    "specialFriday": "HAPPY HOUR, Monday-Friday, 4pm-7pm, $3.50 Drafts, $4.50 Wines, $5.50 Signature Martinis, Half Price Select Apps, and Flatbreads",
    "specialSaturday": "",
    "specialSunday": "",
    "Note": "",
    "lat": 39.158331,
    "long": -84.4276546
  },
  {
    "ID": 69,
    "Bar": "R P Mc Murphy's Irish Pub",
    "Description": "Upbeat bar featuring a range of draft beers, frequent live music & a patio area with fire pits.",
    "Neighborhood": "Oakley",
    "Address": "2910 Wasson Rd, Cincinnati, OH 45209",
    "Phone": "(513) 531-3300",
    "Website": "http://www.rpmcmurphyspub.com/",
    "hoursMonday": "3PM–2:30AM",
    "hoursTuesday": "3PM–2:30AM",
    "hoursWednesday": "3PM–2:30AM",
    "hoursThursday": "3PM–2:30AM",
    "hoursFriday": "3PM–2:30AM",
    "hoursSaturday": "12PM–2:30AM",
    "hoursSunday": "12PM–2:30AM",
    "specialMonday": "",
    "specialTuesday": "",
    "specialWednesday": "",
    "specialThursday": "",
    "specialFriday": "",
    "specialSaturday": "",
    "specialSunday": "",
    "Note": "",
    "lat": 39.144556,
    "long": -84.4350567
  },
  {
    "ID": 70,
    "Bar": "The Casual Pint Oakley Station",
    "Description": "",
    "Neighborhood": "Oakley",
    "Address": "3200 Vandercar Way, Cincinnati, OH 45209",
    "Phone": "(513) 351-2264",
    "Website": "http://oakleystation.thecasualpint.com/",
    "hoursMonday": "4–10PM",
    "hoursTuesday": "12–11PM",
    "hoursWednesday": "12–11PM",
    "hoursThursday": "12–11PM",
    "hoursFriday": "12PM–12AM",
    "hoursSaturday": "12PM–12AM",
    "hoursSunday": "1–9PM",
    "specialMonday": "",
    "specialTuesday": "",
    "specialWednesday": "",
    "specialThursday": "",
    "specialFriday": "",
    "specialSaturday": "",
    "specialSunday": "",
    "Note": "",
    "lat": 39.158331,
    "long": -84.4276546
  },
  {
    "ID": 71,
    "Bar": "Oakley Wines",
    "Description": "",
    "Neighborhood": "Oakley",
    "Address": "4011 Allston St, Cincinnati, OH 45209",
    "Phone": "(513) 531-1400",
    "Website": "http://www.oakleywines.com/",
    "hoursMonday": "3PM–12AM",
    "hoursTuesday": "3PM–12AM",
    "hoursWednesday": "3PM–12AM",
    "hoursThursday": "3PM–12AM",
    "hoursFriday": "3PM–1AM",
    "hoursSaturday": "3PM–1AM",
    "hoursSunday": "Closed",
    "specialMonday": "Happy Hour prices from 4-6 pm.",
    "specialTuesday": "Happy Hour prices from 4-6 pm.",
    "specialWednesday": "Happy Hour prices from 4-6 pm.",
    "specialThursday": "Happy Hour prices from 4-6 pm.",
    "specialFriday": "Happy Hour prices from 4-6 pm., Friday Night Tasting, EVERY FRIDAY NIGHT, 5 - 8 pm, $10, ​Enjoy 5 glass pours. Tasting takes places upstairs in The Tasting Room, but you're welcome to enjoy your wine downstairs in The Cellar.",
    "specialSaturday": "Happy Hour prices from 4-6 pm.",
    "specialSunday": "",
    "Note": "",
    "lat": 39.152024,
    "long": -84.4331021
  },
  {
    "ID": 72,
    "Bar": "Maribelle's eat + drink",
    "Description": "Casual bistro serving area-sourced American eats including vegan options, plus beer & cocktails.",
    "Neighborhood": "Oakley",
    "Address": "3235 Madison Rd, Cincinnati, OH 45209",
    "Phone": "(513) 321-9111",
    "Website": "http://www.maribelleseatdrink.com/",
    "hoursMonday": "Closed",
    "hoursTuesday": "5–9PM",
    "hoursWednesday": "5–9PM",
    "hoursThursday": "5–9PM",
    "hoursFriday": "11AM–10PM",
    "hoursSaturday": "11AM–10PM",
    "hoursSunday": "11AM–9PM",
    "specialMonday": "",
    "specialTuesday": "",
    "specialWednesday": "",
    "specialThursday": "",
    "specialFriday": "",
    "specialSaturday": "",
    "specialSunday": "",
    "Note": "",
    "lat": 39.1546832,
    "long": -84.4261936
  },
  {
    "ID": 73,
    "Bar": "Hap's Irish Pub",
    "Description": "",
    "Neighborhood": "Oakley",
    "Address": "3510 Erie Ave, Cincinnati, OH 45208",
    "Phone": "(513) 871-6477",
    "Website": "https://www.facebook.com/Haps-Irish-Pub-125057637545502/",
    "hoursMonday": "12PM–2:30AM",
    "hoursTuesday": "12PM–2:30AM",
    "hoursWednesday": "12PM–2:30AM",
    "hoursThursday": "12PM–2:30AM",
    "hoursFriday": "12PM–2:30AM",
    "hoursSaturday": "9AM–2:30AM",
    "hoursSunday": "12PM–2:30AM",
    "specialMonday": "",
    "specialTuesday": "",
    "specialWednesday": "",
    "specialThursday": "",
    "specialFriday": "",
    "specialSaturday": "",
    "specialSunday": "",
    "Note": "",
    "lat": 39.1412901,
    "long": -84.4187775
  },
  {
    "ID": 74,
    "Bar": "Animations",
    "Description": "",
    "Neighborhood": "Oakley",
    "Address": "3059 Madison Rd, Cincinnati, OH 45209",
    "Phone": "(513) 871-7606",
    "Website": "",
    "hoursMonday": "12PM–2:30AM",
    "hoursTuesday": "12PM–2:30AM",
    "hoursWednesday": "12PM–2:30AM",
    "hoursThursday": "12PM–2:30AM",
    "hoursFriday": "12PM–2:30AM",
    "hoursSaturday": "12PM–2:30AM",
    "hoursSunday": "12PM–2:30AM",
    "specialMonday": "",
    "specialTuesday": "",
    "specialWednesday": "",
    "specialThursday": "",
    "specialFriday": "",
    "specialSaturday": "",
    "specialSunday": "",
    "Note": "",
    "lat": 39.1518389,
    "long": -84.4319005
  },
  {
    "ID": 75,
    "Bar": "Keystone Bar & Grill",
    "Description": "A lively spot for gourmet bar food (available family-style), cocktails, wine & a lengthy beer menu.",
    "Neighborhood": "Oakley",
    "Address": "1626, 3384 Erie Ave, Cincinnati, OH 45208",
    "Phone": "(513) 321-2150",
    "Website": "http://www.keystonebar.com/",
    "hoursMonday": "11:30AM–12AM",
    "hoursTuesday": "11:30AM–12AM",
    "hoursWednesday": "11:30AM–12AM",
    "hoursThursday": "11:30AM–12AM",
    "hoursFriday": "11:30AM–2:30AM",
    "hoursSaturday": "10AM–2:30AM",
    "hoursSunday": "10AM–12AM",
    "specialMonday": "Half-Price Mac & Cheese, w/ beverage purchase until 11pm and $4 Moscow Mules from 6pm – Close, Monday – Friday 3-6pm, 1/2 price appetizers, 1/2 price bottles of wine, 1/2 price signature cocktails, $2 off select drafts, and $2 domestics",
    "specialTuesday": "Half-Price Quesadillas, w/ beverage purchase until 11pm and $2 Tall Boys all day, Monday – Friday 3-6pm, 1/2 price appetizers, 1/2 price bottles of wine, 1/2 price signature cocktails, $2 off select drafts, and $2 domestics",
    "specialWednesday": "BYOB (Build Your Own Burger Night), Local beer of the month for $3 beginning at 6pm, Monday – Friday 3-6pm, 1/2 price appetizers, 1/2 price bottles of wine, 1/2 price signature cocktails, $2 off select drafts, and $2 domestics",
    "specialThursday": "Half-Price Pints, all day *rare exclusions apply, Monday – Friday 3-6pm, 1/2 price appetizers, 1/2 price bottles of wine, 1/2 price signature cocktails, $2 off select drafts, and $2 domestics",
    "specialFriday": "Double-Down Happy Hour, Happy hour pricing from 3-6pm and 9pm-close, Monday – Friday 3-6pm, 1/2 price appetizers, 1/2 price bottles of wine, 1/2 price signature cocktails, $2 off select drafts, and $2 domestics",
    "specialSaturday": "$14 Mimosa Pitchers (10am – 2pm), $3 Green Tea, Jameson, Fireball, Big Blue shots with the purchase of any beer from 9pm-close",
    "specialSunday": "$14 Mimosa Pitchers (11am – 2pm), $2 domestic bottles and half-price signature cocktails from 2pm-close",
    "Note": "",
    "lat": 39.141479,
    "long": -84.421071
  },
  {
    "ID": 76,
    "Bar": "Edge Inn Tavern",
    "Description": "",
    "Neighborhood": "Oakley",
    "Address": "3935 Edwards Rd, Cincinnati, OH 45209",
    "Phone": "(513) 841-9030",
    "Website": "",
    "hoursMonday": "1PM–2:30AM",
    "hoursTuesday": "1PM–2:30AM",
    "hoursWednesday": "1PM–2:30AM",
    "hoursThursday": "1PM–2:30AM",
    "hoursFriday": "1PM–2:30AM",
    "hoursSaturday": "12PM–2:30AM",
    "hoursSunday": "12PM–2:30AM",
    "specialMonday": "",
    "specialTuesday": "",
    "specialWednesday": "",
    "specialThursday": "",
    "specialFriday": "",
    "specialSaturday": "",
    "specialSunday": "",
    "Note": "",
    "lat": 39.1511605,
    "long": -84.4424661
  },
  {
    "ID": 77,
    "Bar": "Establishment",
    "Description": "",
    "Neighborhood": "Oakley",
    "Address": "2900 Wasson Rd, Cincinnati, OH 45209",
    "Phone": "(513) 631-9000",
    "Website": "http://theeoakley.com/",
    "hoursMonday": "3:30PM–2:30AM",
    "hoursTuesday": "3:30PM–2:30AM",
    "hoursWednesday": "3:30PM–2:30AM",
    "hoursThursday": "3:30PM–2:30AM",
    "hoursFriday": "3:30PM–2:30AM",
    "hoursSaturday": "3:30PM–2:30AM",
    "hoursSunday": "12PM–2:30AM",
    "specialMonday": "Happy Hour:, Monday – Thursday 3:30pm – 9pm, $2.00 Domestic Bottles and drafts, $3.00 Well Liquor Drinks",
    "specialTuesday": "Happy Hour:, Monday – Thursday 3:30pm – 9pm, $2.00 Domestic Bottles and drafts, $3.00 Well Liquor Drinks",
    "specialWednesday": "Happy Hour:, Monday – Thursday 3:30pm – 9pm, $2.00 Domestic Bottles and drafts, $3.00 Well Liquor Drinks",
    "specialThursday": "Happy Hour:, Monday – Thursday 3:30pm – 9pm, $2.00 Domestic Bottles and drafts, $3.00 Well Liquor Drinks",
    "specialFriday": "Happy Hour:, Friday 3:30pm – 7:30pm, $2.00 Domestic Bottles and drafts, $3.00 Well Liquor Drinks",
    "specialSaturday": "Happy Hour:, Saturday – Sunday 12pm – 7:30pm, $2.00 Domestic Bottles and drafts, $3.00 Well Liquor Drinks",
    "specialSunday": "Happy Hour:, Saturday – Sunday 12pm – 7:30pm, $2.00 Domestic Bottles and drafts, $3.00 Well Liquor Drinks",
    "Note": "",
    "lat": 39.1445352,
    "long": -84.4354027
  },
  {
    "ID": 78,
    "Bar": "Unwind Wine Bar & Light Fare",
    "Description": "Modern-yet-rustic bar offering wine, spirits & small plates in a relaxed setting with patio seating.",
    "Neighborhood": "Oakley",
    "Address": "3435 Michigan Ave, Cincinnati, OH 45208",
    "Phone": "(513) 321-9463",
    "Website": "http://www.unwindhydepark.com/",
    "hoursMonday": "4–11PM",
    "hoursTuesday": "4–11PM",
    "hoursWednesday": "4–11PM",
    "hoursThursday": "4PM–12AM",
    "hoursFriday": "4PM–1:15AM",
    "hoursSaturday": "4PM–12AM",
    "hoursSunday": "Closed",
    "specialMonday": "",
    "specialTuesday": "",
    "specialWednesday": "",
    "specialThursday": "",
    "specialFriday": "",
    "specialSaturday": "",
    "specialSunday": "",
    "Note": "",
    "lat": 39.1387176,
    "long": -84.4419998
  },
  {
    "ID": 79,
    "Bar": "MadTree Brewing",
    "Description": "Bustling taproom offering craft beers, wood-fired pizzas, growler fills & keg sales, plus a patio.",
    "Neighborhood": "Oakley",
    "Address": "3301 Madison Rd, Cincinnati, OH 45209",
    "Phone": "(513) 836-8733",
    "Website": "http://www.madtreebrewing.com/",
    "hoursMonday": "11AM–11PM",
    "hoursTuesday": "11AM–11PM",
    "hoursWednesday": "11AM–11PM",
    "hoursThursday": "11AM–11PM",
    "hoursFriday": "11AM–1AM",
    "hoursSaturday": "10AM–1AM",
    "hoursSunday": "10AM–11PM",
    "specialMonday": "",
    "specialTuesday": "",
    "specialWednesday": "",
    "specialThursday": "",
    "specialFriday": "",
    "specialSaturday": "",
    "specialSunday": "",
    "Note": "",
    "lat": 39.1563725,
    "long": -84.4239715
  },
  {
    "ID": 80,
    "Bar": "The Pub at Rookwood Mews",
    "Description": "British-inspired pub with a wraparound bar serves comfort eats & pints in charming, old-world digs.",
    "Neighborhood": "Oakley",
    "Address": "2692 Edmondson Rd, Cincinnati, OH 45208",
    "Phone": "(513) 841-2748",
    "Website": "http://experiencethepub.com/rookwood",
    "hoursMonday": "11AM–12AM",
    "hoursTuesday": "11AM–12AM",
    "hoursWednesday": "11AM–12AM",
    "hoursThursday": "11AM–12AM",
    "hoursFriday": "11AM–1AM",
    "hoursSaturday": "10AM–1AM",
    "hoursSunday": "10AM–11PM",
    "specialMonday": "Happy Hour, Monday – Friday | 3pm – 7pm, $5.00 Appetizers, Drink Specials, Monday, Pub Quiz 7:30pm",
    "specialTuesday": "Happy Hour, Monday – Friday | 3pm – 7pm, $5.00 Appetizers, Drink Specials",
    "specialWednesday": "Happy Hour, Monday – Friday | 3pm – 7pm, $5.00 Appetizers, Drink Specials, Wednesday, 1/2 priced bottles of select wines",
    "specialThursday": "Happy Hour, Monday – Friday | 3pm – 7pm, $5.00 Appetizers, Drink Specials",
    "specialFriday": "Happy Hour, Monday – Friday | 3pm – 7pm, $5.00 Appetizers, Drink Specials",
    "specialSaturday": "",
    "specialSunday": "",
    "Note": "Military Discount, All members of the military receive a 25% discount on food purchases when they present a military ID.",
    "lat": 39.1482873,
    "long": -84.4427869
  },
  {
    "ID": 81,
    "Bar": "Dutch's",
    "Description": "A massive collection of handcrafted beer & wine (to drink or buy), plus artisanal meats & cheeses.",
    "Neighborhood": "Oakley",
    "Address": "3378 Erie Ave, Cincinnati, OH 45208",
    "Phone": "(513) 871-1446",
    "Website": "http://www.dutchscincinnati.com/",
    "hoursMonday": "Closed",
    "hoursTuesday": "11AM–9PM",
    "hoursWednesday": "11AM–9PM",
    "hoursThursday": "11AM–9PM",
    "hoursFriday": "11AM–10PM",
    "hoursSaturday": "11AM–10PM",
    "hoursSunday": "11AM–9PM",
    "specialMonday": "",
    "specialTuesday": "",
    "specialWednesday": "",
    "specialThursday": "",
    "specialFriday": "",
    "specialSaturday": "",
    "specialSunday": "",
    "Note": "",
    "lat": 39.1414011,
    "long": -84.4215840603453
  },
  {
    "ID": 82,
    "Bar": "MILLIONS CAFÉ",
    "Description": "",
    "Neighborhood": "Oakley",
    "Address": "3210 Linwood Ave, Cincinnati, OH 45208",
    "Phone": "(513) 815-4500",
    "Website": "http://www.millions-cafe.com/",
    "hoursMonday": "4PM–2:30AM",
    "hoursTuesday": "4PM–2:30AM",
    "hoursWednesday": "4PM–2:30AM",
    "hoursThursday": "4PM–2:30AM",
    "hoursFriday": "4PM–2:30AM",
    "hoursSaturday": "11:30AM–2:30AM",
    "hoursSunday": "11:30AM–2:30AM",
    "specialMonday": "",
    "specialTuesday": "",
    "specialWednesday": "",
    "specialThursday": "",
    "specialFriday": "",
    "specialSaturday": "",
    "specialSunday": "",
    "Note": "",
    "lat": 39.1282003,
    "long": -84.4299379
  },
  {
    "ID": 83,
    "Bar": "Hooligan's Pub & Eatery",
    "Description": "Longtime family-owned joint with American eats, an outdoor patio & a seasonal sand volleyball court.",
    "Neighborhood": "Oakley",
    "Address": "3340 Highland Ave, Cincinnati, OH 45213",
    "Phone": "(513) 841-9994",
    "Website": "http://www.hooligans-pub.com/",
    "hoursMonday": "11AM–2:30AM",
    "hoursTuesday": "11AM–2:30AM",
    "hoursWednesday": "11AM–2:30AM",
    "hoursThursday": "11AM–2:30AM",
    "hoursFriday": "11AM–2:30AM",
    "hoursSaturday": "11AM–2:30AM",
    "hoursSunday": "11AM–2:30AM",
    "specialMonday": "",
    "specialTuesday": "",
    "specialWednesday": "",
    "specialThursday": "",
    "specialFriday": "",
    "specialSaturday": "",
    "specialSunday": "",
    "Note": "",
    "lat": 39.167171,
    "long": -84.429478
  },
  {
    "ID": 84,
    "Bar": "BrewRiver GastroPub",
    "Description": "Riverside tavern with a big patio, serving N’Awlins-style American classics & oodles of local brews.",
    "Neighborhood": "Oakley",
    "Address": "2062 Riverside Dr, Cincinnati, OH 45202",
    "Phone": "(513) 861-2484",
    "Website": "http://brewrivergastropub.com/",
    "hoursMonday": "Closed",
    "hoursTuesday": "11AM–9PM",
    "hoursWednesday": "11AM–9PM",
    "hoursThursday": "11AM–9PM",
    "hoursFriday": "11AM–10PM",
    "hoursSaturday": "10AM–10PM",
    "hoursSunday": "10AM–9PM",
    "specialMonday": "",
    "specialTuesday": "",
    "specialWednesday": "",
    "specialThursday": "",
    "specialFriday": "",
    "specialSaturday": "",
    "specialSunday": "",
    "Note": "",
    "lat": 39.1217775,
    "long": -84.4751191
  },
  {
    "ID": 85,
    "Bar": "Mt. Lookout Tavern",
    "Description": "",
    "Neighborhood": "Oakley",
    "Address": "3209 Linwood Ave, Cincinnati, OH 45226",
    "Phone": "(513) 871-9633",
    "Website": "http://www.mtlookouttavern.com/",
    "hoursMonday": "11AM–2:30AM",
    "hoursTuesday": "11AM–2:30AM",
    "hoursWednesday": "11AM–2:30AM",
    "hoursThursday": "11AM–2:30AM",
    "hoursFriday": "11AM–2:30AM",
    "hoursSaturday": "11AM–2:30AM",
    "hoursSunday": "11AM–2:30AM",
    "specialMonday": "",
    "specialTuesday": "",
    "specialWednesday": "",
    "specialThursday": "",
    "specialFriday": "",
    "specialSaturday": "",
    "specialSunday": "",
    "Note": "",
    "lat": 39.1226349,
    "long": -84.4186019
  },
  {
    "ID": 86,
    "Bar": "Zip's Café",
    "Description": "Burgers, fried fish sandwiches & other pub-grub classics go alongside beer at this longtime hangout.",
    "Neighborhood": "Oakley",
    "Address": "1036 Delta Ave, Cincinnati, OH 45208",
    "Phone": "(513) 871-9876",
    "Website": "http://www.zipscafe.com/",
    "hoursMonday": "10:30AM–11PM",
    "hoursTuesday": "10:30AM–11PM",
    "hoursWednesday": "10:30AM–11PM",
    "hoursThursday": "10:30AM–11PM",
    "hoursFriday": "10:30AM–11:30PM",
    "hoursSaturday": "10:30AM–11:30PM",
    "hoursSunday": "11AM–11PM",
    "specialMonday": "",
    "specialTuesday": "",
    "specialWednesday": "",
    "specialThursday": "",
    "specialFriday": "",
    "specialSaturday": "",
    "specialSunday": "",
    "Note": "",
    "lat": 39.1297005,
    "long": -84.4293832
  },
  {
    "ID": 87,
    "Bar": "Proof Bar",
    "Description": "",
    "Neighborhood": "Oakley",
    "Address": "3195 Linwood Ave, Cincinnati, OH 45208",
    "Phone": "",
    "Website": "",
    "hoursMonday": "5PM–2:30AM",
    "hoursTuesday": "5PM–2:30AM",
    "hoursWednesday": "5PM–2:30AM",
    "hoursThursday": "5PM–2:30AM",
    "hoursFriday": "5PM–2:30AM",
    "hoursSaturday": "5PM–2:30AM",
    "hoursSunday": "5PM–2:30AM",
    "specialMonday": "",
    "specialTuesday": "",
    "specialWednesday": "",
    "specialThursday": "",
    "specialFriday": "",
    "specialSaturday": "",
    "specialSunday": "",
    "Note": "",
    "lat": 39.1288464,
    "long": -84.4305803
  },
  {
    "ID": 88,
    "Bar": "Pearl's Bar",
    "Description": "Neighborhood pub serving beer & spirits in a 100-year-old distressed building with an outdoor patio.",
    "Neighborhood": "Oakley",
    "Address": "3520 Eastern Ave, Cincinnati, OH 45226",
    "Phone": "(513) 832-0485",
    "Website": "http://www.pearls-cincy.com/",
    "hoursMonday": "4PM–2AM",
    "hoursTuesday": "4PM–2AM",
    "hoursWednesday": "4PM–2AM",
    "hoursThursday": "4PM–2AM",
    "hoursFriday": "3PM–2AM",
    "hoursSaturday": "12PM–2AM",
    "hoursSunday": "12PM–12AM",
    "specialMonday": "",
    "specialTuesday": "",
    "specialWednesday": "",
    "specialThursday": "",
    "specialFriday": "",
    "specialSaturday": "",
    "specialSunday": "",
    "Note": "",
    "lat": 39.11607725,
    "long": -84.4389978359318
  },
  {
    "ID": 89,
    "Bar": "The Hi-Mark",
    "Description": "Easygoing, industrial cocktail & craft beer bar inside an 1866 house with a spacious patio.",
    "Neighborhood": "Oakley",
    "Address": "3229 Riverside Dr, Cincinnati, OH 45226",
    "Phone": "(513) 492-7119",
    "Website": "http://www.thehimark.com/",
    "hoursMonday": "4PM–12AM",
    "hoursTuesday": "4PM–12AM",
    "hoursWednesday": "4PM–12AMM–12AM",
    "hoursThursday": "4PM–12AM",
    "hoursFriday": "4PM–2AM",
    "hoursSaturday": "12PM–2AM",
    "hoursSunday": "12PM–12AM",
    "specialMonday": "",
    "specialTuesday": "",
    "specialWednesday": "",
    "specialThursday": "",
    "specialFriday": "",
    "specialSaturday": "",
    "specialSunday": "",
    "Note": "",
    "lat": 39.118528,
    "long": -84.443819
  },
  {
    "ID": 90,
    "Bar": "Spittoon Saloon",
    "Description": "",
    "Neighborhood": "Oakley",
    "Address": "4835 Eastern Ave, Cincinnati, OH 45208",
    "Phone": "",
    "Website": "",
    "hoursMonday": "Closed",
    "hoursTuesday": "Closed",
    "hoursWednesday": "Closed",
    "hoursThursday": "5PM–3AM",
    "hoursFriday": "5PM–3AM",
    "hoursSaturday": "5PM–3AM",
    "hoursSunday": "5PM–3AM",
    "specialMonday": "",
    "specialTuesday": "",
    "specialWednesday": "",
    "specialThursday": "",
    "specialFriday": "",
    "specialSaturday": "",
    "specialSunday": "",
    "Note": "",
    "lat": 39.1225108552086,
    "long": -84.4154351749061
  },
  {
    "ID": 91,
    "Bar": "Cock & Bull Public House Hyde Park Square",
    "Description": "",
    "Neighborhood": "Oakley",
    "Address": "2645 Erie Ave, Cincinnati, OH 45208",
    "Phone": "(513) 533-4253",
    "Website": "http://www.cockandbullcincinnati.com/",
    "hoursMonday": "11AM–11PM",
    "hoursTuesday": "11AM–11PM",
    "hoursWednesday": "11AM–11PM",
    "hoursThursday": "11AM–12AM",
    "hoursFriday": "11AM–2AM",
    "hoursSaturday": "11AM–2AM",
    "hoursSunday": "11AM–10PM",
    "specialMonday": "",
    "specialTuesday": "",
    "specialWednesday": "",
    "specialThursday": "Pint Night - 6PM Keep the Glass",
    "specialFriday": "",
    "specialSaturday": "",
    "specialSunday": "",
    "Note": "",
    "lat": 39.1394519,
    "long": -84.4434628
  }
]