export const barList = [
  {
    "ID": 1,
    "Bar": "Taft's Ale House",
    "Description": "Artisanal beers, steaks & salads served in a classic brewpub named after Cincinnati’s favorite son.",
    "Neighborhood": "Over-the-Rhine",
    "Address": "1429 Race St, Cincinnati, OH 45202",
    "Phone": "(513) 334-1393",
    "Website": "http://taftsalehouse.com/",
    "hoursMonday": "11:30AM–10PM",
    "hoursTuesday": "11:30AM–10PM",
    "hoursWednesday": "11:30AM–11PM",
    "hoursThursday": "11:30AM–12AM",
    "hoursFriday": "11:30AM–12AM",
    "hoursSaturday": "11:30AM–12AM",
    "hoursSunday": "11:30AM–9PM",
    "specialMonday": "",
    "specialTuesday": "Taft Tuesdays - Enjoy Half-Price Pints & Growler Fills ALL DAY by wearing any Brewery or Beer Apparel. Don’t have any threads? Stop-n-shop in Nellie’s Tap Room to pick up your gear!",
    "specialWednesday": "",
    "specialThursday": "",
    "specialFriday": "",
    "specialSaturday": "",
    "specialSunday": "",
    "Note": ""
  },
  {
    "ID": 2,
    "Bar": "Sundry and Vice",
    "Description": "Striking, well-appointed cocktail spot with a tin ceiling & vintage feel offering inventive drinks.",
    "Neighborhood": "Over-the-Rhine",
    "Address": "18 W 13th St, Cincinnati, OH 45202",
    "Phone": "(513) 721-8423",
    "Website": "http://sundryandvice.com/",
    "hoursMonday": "Closed",
    "hoursTuesday": "4PM–2AM",
    "hoursWednesday": "4PM–2AM",
    "hoursThursday": "4PM–2AM",
    "hoursFriday": "4PM–2AM",
    "hoursSaturday": "12PM–2AM",
    "hoursSunday": "12PM–12AM",
    "specialMonday": "",
    "specialTuesday": "",
    "specialWednesday": "",
    "specialThursday": "",
    "specialFriday": "",
    "specialSaturday": "",
    "specialSunday": "",
    "Note": ""
  },
  {
    "ID": 3,
    "Bar": "The Rook OTR",
    "Description": "",
    "Neighborhood": "Over-the-Rhine",
    "Address": "1115 Vine St, Cincinnati, OH 45202",
    "Phone": "(513) 954-8191",
    "Website": "https://www.facebook.com/therookotr/",
    "hoursMonday": "4PM–12AM",
    "hoursTuesday": "4PM–12AM",
    "hoursWednesday": "4PM–12AM",
    "hoursThursday": "4PM–12AM",
    "hoursFriday": "4PM–2AM",
    "hoursSaturday": "11AM–2AM",
    "hoursSunday": "11AM–12AM",
    "specialMonday": "",
    "specialTuesday": "",
    "specialWednesday": "",
    "specialThursday": "",
    "specialFriday": "",
    "specialSaturday": "",
    "specialSunday": "",
    "Note": "Lots of different events. "
  },
  {
    "ID": 4,
    "Bar": "The Lackman",
    "Description": "Luxe lounge in a turn-of-the-century building offering craft beers & eclectic wines, plus a jukebox.",
    "Neighborhood": "Over-the-Rhine",
    "Address": "1237 Vine Street, Cincinnati, OH 45202",
    "Phone": "(513) 381-0741",
    "Website": "http://www.lackmanbar.com/",
    "hoursMonday": "4PM–2AM",
    "hoursTuesday": "4PM–2AM",
    "hoursWednesday": "4PM–2AM",
    "hoursThursday": "4PM–2AM",
    "hoursFriday": "3PM–2AM",
    "hoursSaturday": "12PM–2AM",
    "hoursSunday": "12PM–12AM",
    "specialMonday": "HAPPY HOUR\nHappy Hour | 4-8PM\n$2 Off Drafts\n$3.25 Domestics\n$4.50 Calls\n$5 Dark Horse Wines",
    "specialTuesday": "HAPPY HOUR\nHappy Hour | 4-8PM\n$2 Off Drafts\n$3.25 Domestics\n$4.50 Calls\n$5 Dark Horse Wines",
    "specialWednesday": "HAPPY HOUR\nHappy Hour | 4-8PM\n$2 Off Drafts\n$3.25 Domestics\n$4.50 Calls\n$5 Dark Horse Wines",
    "specialThursday": "HAPPY HOUR\nHappy Hour | 4-8PM\n$2 Off Drafts\n$3.25 Domestics\n$4.50 Calls\n$5 Dark Horse Wines",
    "specialFriday": "HAPPY HOUR\nHappy Hour | 4-8PM\n$2 Off Drafts\n$3.25 Domestics\n$4.50 Calls\n$5 Dark Horse Wines",
    "specialSaturday": "HAPPY HOUR\nHappy Hour | 4-8PM\n$2 Off Drafts\n$3.25 Domestics\n$4.50 Calls\n$5 Dark Horse Wines",
    "specialSunday": "HAPPY HOUR\nHappy Hour | 4-8PM\n$2 Off Drafts\n$3.25 Domestics\n$4.50 Calls\n$5 Dark Horse Wines",
    "Note": ""
  },
  {
    "ID": 5,
    "Bar": "Japp's - Since 1879",
    "Description": "Bustling spot for classic & creative cocktails served in casual environs in a storied building.",
    "Neighborhood": "Over-the-Rhine",
    "Address": "1136 Main St, Cincinnati, OH 45202",
    "Phone": "(513) 381-1524",
    "Website": "http://japps1879.com/",
    "hoursMonday": "Closed",
    "hoursTuesday": "4PM–1AM",
    "hoursWednesday": "4PM–1AM",
    "hoursThursday": "4PM–1AM",
    "hoursFriday": "4PM–2AM",
    "hoursSaturday": "5PM–2AM",
    "hoursSunday": "Closed",
    "specialMonday": "",
    "specialTuesday": "",
    "specialWednesday": "",
    "specialThursday": "Live Music from Jess Lamb and Friends\n9:00 PM – 11:30 PM\nLive music from Cincinnati native, Jess Lamb, and special guests, every week!",
    "specialFriday": "The Burning Caravan at Japp's\n 5:30 PM – 8:30 PM\nLive Music from The Burning Caravan from 530-830pm EVERY Friday!\nRotating Local DJ's in the Lounge\n9:00 PM – 11:30 PM\nEvery Friday night we host a DJ for a late night set in the lounge! Check us out on Facebook for info on this week's DJ! \n9pm-close every Friday!",
    "specialSaturday": "Live Happy Hour Music\n6:00 PM – 9:00 PM\nLive Happy Hour Music Every Saturday.",
    "specialSunday": "",
    "Note": ""
  },
  {
    "ID": 6,
    "Bar": "rhinehaus",
    "Description": "Laid-back hangout with sports on TV & craft beers offered in a contemporary, exposed-brick space.",
    "Neighborhood": "Over-the-Rhine",
    "Address": "119 E 12th St, Cincinnati, OH 45202",
    "Phone": "(513) 381-2277",
    "Website": "http://www.rhinehausbar.com/",
    "hoursMonday": "4PM–2AM",
    "hoursTuesday": "4PM–2AM",
    "hoursWednesday": "4PM–2AM",
    "hoursThursday": "4PM–2AM",
    "hoursFriday": "4PM–2AM",
    "hoursSaturday": "7AM–2AM",
    "hoursSunday": "7AM–12AM",
    "specialMonday": "",
    "specialTuesday": "",
    "specialWednesday": "",
    "specialThursday": "",
    "specialFriday": "",
    "specialSaturday": "",
    "specialSunday": "",
    "Note": ""
  },
  {
    "ID": 7,
    "Bar": "Motr Pub",
    "Description": "Easygoing hangout with local art on the walls, featuring live rock bands & hearty comfort fare.",
    "Neighborhood": "Over-the-Rhine",
    "Address": "1345 Main St, Cincinnati, OH 45202",
    "Phone": "(513) 381-6687",
    "Website": "http://www.pubcincinnati.com/",
    "hoursMonday": "11AM–2:30AM",
    "hoursTuesday": "11AM–2:30AM",
    "hoursWednesday": "11AM–2:30AM",
    "hoursThursday": "11AM–2:30AM",
    "hoursFriday": "11AM–2:30AM",
    "hoursSaturday": "10AM–2:30AM",
    "hoursSunday": "10AM–2:30AM",
    "specialMonday": "",
    "specialTuesday": "",
    "specialWednesday": "",
    "specialThursday": "",
    "specialFriday": "",
    "specialSaturday": "",
    "specialSunday": "",
    "Note": ""
  },
  {
    "ID": 8,
    "Bar": "Bakersfield OTR",
    "Description": "Tacos & a few other Mexican dishes are delivered in a chic, upbeat, margarita-fueled atmosphere.",
    "Neighborhood": "Over-the-Rhine",
    "Address": "1213 Vine St, Cincinnati, OH 45202",
    "Phone": "(513) 579-0446",
    "Website": "http://www.bakersfieldtacos.com/",
    "hoursMonday": "11AM–12AM",
    "hoursTuesday": "11AM–12AM",
    "hoursWednesday": "11AM–12AM",
    "hoursThursday": "11AM–12AM",
    "hoursFriday": "11AM–2AM",
    "hoursSaturday": "11AM–2AM",
    "hoursSunday": "11AM–12AM",
    "specialMonday": "",
    "specialTuesday": "",
    "specialWednesday": "",
    "specialThursday": "",
    "specialFriday": "",
    "specialSaturday": "",
    "specialSunday": "",
    "Note": ""
  },
  {
    "ID": 9,
    "Bar": "Below Zero Lounge",
    "Description": "Trendy spot with upbeat music serving over 100 vodkas, with featured vodkas served at 6° F.",
    "Neighborhood": "Over-the-Rhine",
    "Address": "1120 Walnut St, Cincinnati, OH 45202",
    "Phone": "(513) 421-9376",
    "Website": "http://www.belowzerolounge.com/",
    "hoursMonday": "Closed",
    "hoursTuesday": "Closed",
    "hoursWednesday": "4PM–12AM",
    "hoursThursday": "4PM–2AM",
    "hoursFriday": "4PM–2AM",
    "hoursSaturday": "4PM–2AM",
    "hoursSunday": "4PM–12AM",
    "specialMonday": "Happy Hour, 4-8pm",
    "specialTuesday": "Happy Hour, 4-8pm",
    "specialWednesday": "Happy Hour, 4-8pm",
    "specialThursday": "Happy Hour, 4-8pm",
    "specialFriday": "Happy Hour, 4-8pm",
    "specialSaturday": "Happy Hour, 4-8pm",
    "specialSunday": "Happy Hour, 4-8pm",
    "Note": ""
  },
  {
    "ID": 10,
    "Bar": "1215 Wine Bar & Coffee Lab",
    "Description": "Homey, brick-walled cafe & bar offering breakfast, baked goods, small plates & wine tastings.",
    "Neighborhood": "Over-the-Rhine",
    "Address": "1215 Vine St, Cincinnati, OH 45202",
    "Phone": "(513) 429-5745",
    "Website": "http://www.1215vine.com/",
    "hoursMonday": "8AM–10PM",
    "hoursTuesday": "8AM–10PM",
    "hoursWednesday": "8AM–11PM",
    "hoursThursday": "8AM–12AM",
    "hoursFriday": "8AM–12AM",
    "hoursSaturday": "9AM–12AM",
    "hoursSunday": "9AM–7PM",
    "specialMonday": "",
    "specialTuesday": "",
    "specialWednesday": "",
    "specialThursday": "",
    "specialFriday": "",
    "specialSaturday": "",
    "specialSunday": "",
    "Note": ""
  },
  {
    "ID": 11,
    "Bar": "Revolution Rotisserie & Bar",
    "Description": "American dishes centered around rotisserie chicken & cocktails are the draw at this modern outpost.",
    "Neighborhood": "Over-the-Rhine",
    "Address": "1106 Race St, Cincinnati, OH 45202",
    "Phone": "(513) 381-0009",
    "Website": "http://revolutionrotisserie.com/",
    "hoursMonday": "11AM–9PM",
    "hoursTuesday": "11AM–9PM",
    "hoursWednesday": "11AM–9PM",
    "hoursThursday": "11AM–9PM",
    "hoursFriday": "11AM–10PM",
    "hoursSaturday": "11AM–10PM",
    "hoursSunday": "10AM–9PM",
    "specialMonday": "Six Dollar Mules\nHappy Hour 3-6PM",
    "specialTuesday": "Six Dollar Sangrias\nHappy Hour 3-6PM",
    "specialWednesday": "Four Dollar Drafts\nHappy Hour 3-6PM",
    "specialThursday": "Six Dollar Wines by the Glass\nHappy Hour 3-6PM",
    "specialFriday": "Three Dollar Craft Beer Cans\nHappy Hour 3-6PM",
    "specialSaturday": "Four Dollar Infusion Shots",
    "specialSunday": "Bottomless Mimosas & Brunch Cocktails",
    "Note": "Happy Hour:\nFour Dollar Drafts\nSix Dollar Wines By the Glass\nSix Dollar Mules/Sangrias\nComplimentary Bottomless Tater Tots during Happy Hour with purchase of alcoholic beverage."
  },
  {
    "ID": 12,
    "Bar": "Low Spark",
    "Description": "",
    "Neighborhood": "Over-the-Rhine",
    "Address": "15 W 14th St, Cincinnati, OH 45202",
    "Phone": "(513) 371-5722",
    "Website": "http://www.lowsparkbar.com/",
    "hoursMonday": "4PM–2:30AM",
    "hoursTuesday": "4PM–2:30AM",
    "hoursWednesday": "4PM–2:30AM",
    "hoursThursday": "4PM–2:30AM",
    "hoursFriday": "4PM–2:30AM",
    "hoursSaturday": "12PM–2:30AM",
    "hoursSunday": "Closed",
    "specialMonday": "8pm – Close\n$5 Shot & Beer Pairing\n4pm – 7pm\n$2 off signature cocktails\n$2 off select drafts\n$2 off calls\n$1 off domestic beers\n$1 off wine\n$3 Budweiser drafts all day",
    "specialTuesday": "8pm – Close\n$5 Shot & Beer Pairing\n4pm – 7pm\n$2 off signature cocktails\n$2 off select drafts\n$2 off calls\n$1 off domestic beers\n$1 off wine\n$3 Budweiser drafts all day",
    "specialWednesday": "8pm – Close\n$5 Shot & Beer Pairing\n4pm – 7pm\n$2 off signature cocktails\n$2 off select drafts\n$2 off calls\n$1 off domestic beers\n$1 off wine\n$3 Budweiser drafts all day",
    "specialThursday": "8pm – Close\n$5 Shot & Beer Pairing\n4pm – 7pm\n$2 off signature cocktails\n$2 off select drafts\n$2 off calls\n$1 off domestic beers\n$1 off wine\n$3 Budweiser drafts all day",
    "specialFriday": "4pm – 7pm\n$2 off signature cocktails\n$2 off select drafts\n$2 off calls\n$1 off domestic beers\n$1 off wine\n$3 Budweiser drafts all day",
    "specialSaturday": "$3 Budweiser drafts all day",
    "specialSunday": "$3 Budweiser drafts all day",
    "Note": "MUSIC HALL SPECIALS\nShow your Cincinnati Music Hall tickets or program to receive $1 off drafts, $1 off domestics, and $1 off Tito’s vodka"
  },
  {
    "ID": 13,
    "Bar": "Longfellow",
    "Description": "",
    "Neighborhood": "Over-the-Rhine",
    "Address": "1233 Clay St, Cincinnati, OH 45202",
    "Phone": "(513) 549-0744",
    "Website": "https://longfellowbar.com/",
    "hoursMonday": "Closed",
    "hoursTuesday": "4PM–2AM",
    "hoursWednesday": "4PM–2AM",
    "hoursThursday": "4PM–2AM",
    "hoursFriday": "4PM–2AM",
    "hoursSaturday": "2PM–2AM",
    "hoursSunday": "2PM–12AM",
    "specialMonday": "",
    "specialTuesday": "Happy Hour Blue Plate Special $7\n16 oz tall boy beer, scrap sandwich OR liverwurst W/potato chips 4-7PM\nLate Night Pierogies One $2 - Three $5 - Five $8 \n11PM-2AM",
    "specialWednesday": "Happy Hour Blue Plate Special $7\n16 oz tall boy beer, scrap sandwich OR liverwurst W/potato chips 4-7PM\nLate Night Pierogies One $2 - Three $5 - Five $8 \n11PM-2AM\nHot Plate Curry & Rice $8",
    "specialThursday": "Happy Hour Blue Plate Special $7\n16 oz tall boy beer, scrap sandwich OR liverwurst W/potato chips 4-7PM\nLate Night Pierogies One $2 - Three $5 - Five $8 \n11PM-2AM\nHot Plate Curry & Rice $8",
    "specialFriday": "Happy Hour Blue Plate Special $7\n16 oz tall boy beer, scrap sandwich OR liverwurst W/potato chips 4-7PM\nLate Night Pierogies One $2 - Three $5 - Five $8 \n11PM-2AM",
    "specialSaturday": "Late Night Pierogies One $2 - Three $5 - Five $8 \n11PM-2AM",
    "specialSunday": "Late Night Pierogies One $2 - Three $5 - Five $8 \nAll Day",
    "Note": ""
  },
  {
    "ID": 14,
    "Bar": "Queen City Radio",
    "Description": "Spacious bar in a buzzy, industrial indoor/outdoor space offering food-truck eats, DJs & live music.",
    "Neighborhood": "Over-the-Rhine",
    "Address": "222 W 12th St, Cincinnati, OH 45202",
    "Phone": "(513) 381-0918",
    "Website": "http://qcrbar.com/",
    "hoursMonday": "4PM–2:30AM",
    "hoursTuesday": "4PM–2:30AM",
    "hoursWednesday": "4PM–2:30AM",
    "hoursThursday": "4PM–2:30AM",
    "hoursFriday": "4PM–2:30AM",
    "hoursSaturday": "12PM–2:30AM",
    "hoursSunday": "12PM–2:30AM",
    "specialMonday": "",
    "specialTuesday": "",
    "specialWednesday": "",
    "specialThursday": "",
    "specialFriday": "",
    "specialSaturday": "",
    "specialSunday": "",
    "Note": ""
  },
  {
    "ID": 15,
    "Bar": "HalfCut",
    "Description": "Rotating taps of craft brews are the focus of this rustic bar that also sells growlers & wine.",
    "Neighborhood": "Over-the-Rhine",
    "Address": "1126 Walnut St, Cincinnati, OH 45202",
    "Phone": "(513) 381-1952",
    "Website": "http://www.halfcut.com/",
    "hoursMonday": "Closed",
    "hoursTuesday": "4–10PM",
    "hoursWednesday": "4–10PM",
    "hoursThursday": "11AM–12AM",
    "hoursFriday": "11AM–2:30AM",
    "hoursSaturday": "11AM–2:30AM",
    "hoursSunday": "Closed",
    "specialMonday": "",
    "specialTuesday": "",
    "specialWednesday": "",
    "specialThursday": "",
    "specialFriday": "",
    "specialSaturday": "",
    "specialSunday": "",
    "Note": ""
  },
  {
    "ID": 16,
    "Bar": "Krueger's Tavern",
    "Description": "Stylish, seasonal New American kitchen with a menu of small & large plates & a rooftop patio.",
    "Neighborhood": "Over-the-Rhine",
    "Address": "1211 Vine St, Cincinnati, OH 45202",
    "Phone": "(513) 834-8670",
    "Website": "http://www.kruegerstavern.com/",
    "hoursMonday": "11AM–12AM",
    "hoursTuesday": "11AM–12AM",
    "hoursWednesday": "11AM–12AM",
    "hoursThursday": "11AM–12AM",
    "hoursFriday": "11AM–12AM",
    "hoursSaturday": "11AM–12AM",
    "hoursSunday": "11AM–10PM",
    "specialMonday": "",
    "specialTuesday": "",
    "specialWednesday": "",
    "specialThursday": "",
    "specialFriday": "",
    "specialSaturday": "",
    "specialSunday": "",
    "Note": ""
  },
  {
    "ID": 17,
    "Bar": "Treehouse Patio Bar",
    "Description": "",
    "Neighborhood": "Over-the-Rhine",
    "Address": "1133 Sycamore St, Cincinnati, OH 45202",
    "Phone": "",
    "Website": "http://treehousepatiobar.berlindoener.info/",
    "hoursMonday": "Closed",
    "hoursTuesday": "4PM–2AM",
    "hoursWednesday": "4PM–2AM",
    "hoursThursday": "4PM–2AM",
    "hoursFriday": "4PM–2AM",
    "hoursSaturday": "2PM–2AM",
    "hoursSunday": "2PM–2AM",
    "specialMonday": "",
    "specialTuesday": "",
    "specialWednesday": "",
    "specialThursday": "",
    "specialFriday": "",
    "specialSaturday": "",
    "specialSunday": "",
    "Note": ""
  },
  {
    "ID": 18,
    "Bar": "Zula Restaurant & Wine Bar",
    "Description": "New American dishes, wine, craft beer & cocktails offered in a warm, industrial-style atmosphere",
    "Neighborhood": "Over-the-Rhine",
    "Address": "7010, 1400 Race St, Cincinnati, OH 45202",
    "Phone": "(513) 744-9852",
    "Website": "http://www.zulabistro.com/",
    "hoursMonday": "Closed",
    "hoursTuesday": "5PM–12AM",
    "hoursWednesday": "5PM–12AM",
    "hoursThursday": "5PM–12AM",
    "hoursFriday": "4PM–1AM",
    "hoursSaturday": "4PM–1AM",
    "hoursSunday": "Closed",
    "specialMonday": "",
    "specialTuesday": "",
    "specialWednesday": "",
    "specialThursday": "",
    "specialFriday": "",
    "specialSaturday": "",
    "specialSunday": "",
    "Note": ""
  },
  {
    "ID": 19,
    "Bar": "Anchor OTR",
    "Description": "Charming seafood eatery with a patio for seasonal outdoor dining & a bar with signature cocktails.",
    "Neighborhood": "Over-the-Rhine",
    "Address": "1401 Race St, Cincinnati, OH 45202",
    "Phone": "(513) 421-8111",
    "Website": "http://www.theanchor-otr.com/",
    "hoursMonday": "Closed",
    "hoursTuesday": "5–10PM",
    "hoursWednesday": "5–10PM",
    "hoursThursday": "5–10PM",
    "hoursFriday": "11:30AM–2:30PM,4:30–11PM",
    "hoursSaturday": "11:30AM–2:30PM,4:30–11PM",
    "hoursSunday": "Closed",
    "specialMonday": "5 – 7 p.m.\n$1.50 OYSTERS – SHUCKER’S CHOICE\n$1 OFF ALL BEERS + $7 RED, WHITE AND ROSÉ WINES",
    "specialTuesday": "5 – 7 p.m.\n$1.50 OYSTERS – SHUCKER’S CHOICE\n$1 OFF ALL BEERS + $7 RED, WHITE AND ROSÉ WINES",
    "specialWednesday": "5 – 7 p.m.\n$1.50 OYSTERS – SHUCKER’S CHOICE\n$1 OFF ALL BEERS + $7 RED, WHITE AND ROSÉ WINES",
    "specialThursday": "5 – 7 p.m.\n$1.50 OYSTERS – SHUCKER’S CHOICE\n$1 OFF ALL BEERS + $7 RED, WHITE AND ROSÉ WINES",
    "specialFriday": "5 – 7 p.m.\n$1.50 OYSTERS – SHUCKER’S CHOICE\n$1 OFF ALL BEERS + $7 RED, WHITE AND ROSÉ WINES\nFish Fry Fridays!! 4:30 -9:00\n2 for 1 Draft Beer\n$2 Oysters Raw or Oven Roasted\n$6  Rum Daiquiris\n$12 baskets of Fish & Chios",
    "specialSaturday": "",
    "specialSunday": "",
    "Note": ""
  },
  {
    "ID": 20,
    "Bar": "A Tavola Bar + Trattoria",
    "Description": "Neapolitan pies are wood-fired & served with antipasti & craft cocktails in an industrial-chic room.",
    "Neighborhood": "Over-the-Rhine",
    "Address": "1220 Vine St, Cincinnati, OH 45202",
    "Phone": "(513) 246-0192",
    "Website": "http://www.atavolapizza.com/",
    "hoursMonday": "11AM–10PM",
    "hoursTuesday": "11AM–10PM",
    "hoursWednesday": "11AM–10PM",
    "hoursThursday": "11AM–10PM",
    "hoursFriday": "11AM–12AM",
    "hoursSaturday": "11AM–12AM",
    "hoursSunday": "12–10PM",
    "specialMonday": "",
    "specialTuesday": "",
    "specialWednesday": "",
    "specialThursday": "",
    "specialFriday": "",
    "specialSaturday": "",
    "specialSunday": "",
    "Note": ""
  },
  {
    "ID": 21,
    "Bar": "Nation Kitchen and Bar",
    "Description": "Rustic-chic place with a large beer menu, craft cocktails, gourmet burgers & creative potato sides.",
    "Neighborhood": "Over-the-Rhine",
    "Address": "1200 Broadway St, Cincinnati, OH 45202",
    "Phone": "(513) 381-3794",
    "Website": "http://nationkitchenandbar.com/",
    "hoursMonday": "11AM–12AM",
    "hoursTuesday": "11AM–12AM",
    "hoursWednesday": "11AM–12AM",
    "hoursThursday": "11AM–12AM",
    "hoursFriday": "11AM–2AM",
    "hoursSaturday": "10AM–2AM",
    "hoursSunday": "10AM–12AM",
    "specialMonday": "",
    "specialTuesday": "",
    "specialWednesday": "",
    "specialThursday": "",
    "specialFriday": "",
    "specialSaturday": "",
    "specialSunday": "",
    "Note": ""
  },
  {
    "ID": 22,
    "Bar": "The Drinkery",
    "Description": "Unpretentious, brick-lined bar & club featuring a patio, local bands, DJs & craft beers.",
    "Neighborhood": "Over-the-Rhine",
    "Address": "1150 Main St, Cincinnati, OH 45202",
    "Phone": "(513) 509-2574",
    "Website": "http://www.drinkotr.com/",
    "hoursMonday": "4PM–2AM",
    "hoursTuesday": "4PM–2AM",
    "hoursWednesday": "4PM–2AM",
    "hoursThursday": "4PM–2AM",
    "hoursFriday": "4PM–2AM",
    "hoursSaturday": "12PM–2AM",
    "hoursSunday": "12PM–2AM",
    "specialMonday": "",
    "specialTuesday": "",
    "specialWednesday": "",
    "specialThursday": "",
    "specialFriday": "",
    "specialSaturday": "",
    "specialSunday": "",
    "Note": ""
  },
  {
    "ID": 23,
    "Bar": "Senate",
    "Description": "Trendy pub serving gourmet hot dogs with creative toppings, plus local brews & retro cocktails.",
    "Neighborhood": "Over-the-Rhine",
    "Address": "1212 Vine St, Cincinnati, OH 45202",
    "Phone": "(513) 421-2020",
    "Website": "http://www.senatepub.com/",
    "hoursMonday": "Closed",
    "hoursTuesday": "11:30AM–10PM",
    "hoursWednesday": "11:30AM–10PM",
    "hoursThursday": "11:30AM–10PM",
    "hoursFriday": "11:30AM–11PM",
    "hoursSaturday": "11:30AM–11PM",
    "hoursSunday": "Closed",
    "specialMonday": "",
    "specialTuesday": "",
    "specialWednesday": "",
    "specialThursday": "",
    "specialFriday": "",
    "specialSaturday": "",
    "specialSunday": "",
    "Note": ""
  },
  {
    "ID": 24,
    "Bar": "Mr Pitiful's",
    "Description": "Cozy neighborhood bar with diverse entertainment, including sports on TV, live music & DJs.",
    "Neighborhood": "Over-the-Rhine",
    "Address": "1323 Main St, Cincinnati, OH 45202",
    "Phone": "(513) 369-0202",
    "Website": "http://mrpitifulsotr.com/",
    "hoursMonday": "6PM–12AM",
    "hoursTuesday": "5PM–12AM",
    "hoursWednesday": "5PM–1AM",
    "hoursThursday": "5PM–2AM",
    "hoursFriday": "4PM–2AM",
    "hoursSaturday": "5PM–12AM",
    "hoursSunday": "12–8PM",
    "specialMonday": "",
    "specialTuesday": "",
    "specialWednesday": "",
    "specialThursday": "",
    "specialFriday": "",
    "specialSaturday": "",
    "specialSunday": "",
    "Note": ""
  },
  {
    "ID": 25,
    "Bar": "Vestry at the Transept",
    "Description": "",
    "Neighborhood": "Over-the-Rhine",
    "Address": "1205 Elm St, Cincinnati, OH 45202",
    "Phone": "(513) 841-9999",
    "Website": "http://vestryotr.com/",
    "hoursMonday": "Closed",
    "hoursTuesday": "Closed",
    "hoursWednesday": "4PM–12AM",
    "hoursThursday": "4PM–12AM",
    "hoursFriday": "4PM–2AM",
    "hoursSaturday": "4PM–2AM",
    "hoursSunday": "Closed",
    "specialMonday": "HAPPY HOUR 4P-8P\n$4 CALLS, $3 DOMESTICS, $2 OFF DRAFTS, $5 GLASSES OF SPANISH WINE\nMonday: “Manhattan Mondays”\n$5 Bulleit Manhattans*HAPPY HOUR 4P-8P\n$4 CALLS, $3 DOMESTICS, $2 OFF DRAFTS, $5 GLASSES OF SPANISH WINE\nMonday: “Manhattan Mondays”\n$5 Bulleit Manhattans*",
    "specialTuesday": "HAPPY HOUR 4P-8P\n$4 CALLS, $3 DOMESTICS, $2 OFF DRAFTS, $5 GLASSES OF SPANISH WINEHAPPY HOUR 4P-8P\n$4 CALLS, $3 DOMESTICS, $2 OFF DRAFTS, $5 GLASSES OF SPANISH WINE",
    "specialWednesday": "HAPPY HOUR 4P-8P\n$4 CALLS, $3 DOMESTICS, $2 OFF DRAFTS, $5 GLASSES OF SPANISH WINE\nWednesday: “Wine Down Wednesdays”\n$15 Polus & Maques De Reinosa BottlesHAPPY HOUR 4P-8P\n$4 CALLS, $3 DOMESTICS, $2 OFF DRAFTS, $5 GLASSES OF SPANISH WINE\nWednesday: “Wine Down Wednesdays”\n$15 Polus & Maques De Reinosa Bottles",
    "specialThursday": "HAPPY HOUR 4P-8P\n$4 CALLS, $3 DOMESTICS, $2 OFF DRAFTS, $5 GLASSES OF SPANISH WINE\nThursday: “Thirsty Thursdays”\n$4 Craft Cans\n$4 Jameson*HAPPY HOUR 4P-8P\n$4 CALLS, $3 DOMESTICS, $2 OFF DRAFTS, $5 GLASSES OF SPANISH WINE\nThursday: “Thirsty Thursdays”\n$4 Craft Cans\n$4 Jameson*",
    "specialFriday": "HAPPY HOUR 4P-8P\n$4 CALLS, $3 DOMESTICS, $2 OFF DRAFTS, $5 GLASSES OF SPANISH WINEHAPPY HOUR 4P-8P\n$4 CALLS, $3 DOMESTICS, $2 OFF DRAFTS, $5 GLASSES OF SPANISH WINE",
    "specialSaturday": "HAPPY HOUR 4P-8P\n$4 CALLS, $3 DOMESTICS, $2 OFF DRAFTS, $5 GLASSES OF SPANISH WINEHAPPY HOUR 4P-8P\n$4 CALLS, $3 DOMESTICS, $2 OFF DRAFTS, $5 GLASSES OF SPANISH WINE",
    "specialSunday": "",
    "Note": ""
  },
  {
    "ID": 26,
    "Bar": "Wiseguy Lounge ",
    "Description": "",
    "Neighborhood": "Over-the-Rhine",
    "Address": "1211 Main St, Cincinnati, OH 45202",
    "Phone": "(513) 381-3625",
    "Website": "http://www.goodfellaspizzeria.com/wiseguy-option-2/",
    "hoursMonday": "11AM–1AM",
    "hoursTuesday": "11AM–1AM",
    "hoursWednesday": "11AM–1AM",
    "hoursThursday": "11AM–2:30AM",
    "hoursFriday": "11AM–2:30AM",
    "hoursSaturday": "11AM–2:30AM",
    "hoursSunday": "11AM–1AM",
    "specialMonday": "",
    "specialTuesday": "",
    "specialWednesday": "",
    "specialThursday": "",
    "specialFriday": "",
    "specialSaturday": "",
    "specialSunday": "",
    "Note": ""
  },
  {
    "ID": 27,
    "Bar": "Revel OTR Urban Winery",
    "Description": "Cozy winery with live music, handcrafted wines & light snacks in rustic-chic digs with live music.",
    "Neighborhood": "Over-the-Rhine",
    "Address": "111 E 12th St, Cincinnati, OH 45202",
    "Phone": "(513) 579-9463",
    "Website": "http://www.revelotr.com/",
    "hoursMonday": "Closed",
    "hoursTuesday": "4PM–12AM",
    "hoursWednesday": "4PM–12AM",
    "hoursThursday": "4PM–12AM",
    "hoursFriday": "4PM–2AM",
    "hoursSaturday": "12PM–2AM",
    "hoursSunday": "Closed",
    "specialMonday": "",
    "specialTuesday": "",
    "specialWednesday": "Happy Hour 4-7 PM\n$5 - Wine, Beer, Wine Cocktails, Olives and Cheese, Bread & OilHappy Hour 4-7 PM\n$5 - Wine, Beer, Wine Cocktails, Olives and Cheese, Bread & Oil",
    "specialThursday": "Happy Hour 4-7 PM\n$5 - Wine, Beer, Wine Cocktails, Olives and Cheese, Bread & OilHappy Hour 4-7 PM\n$5 - Wine, Beer, Wine Cocktails, Olives and Cheese, Bread & Oil",
    "specialFriday": "Happy Hour 4-7 PM\n$5 - Wine, Beer, Wine Cocktails, Olives and Cheese, Bread & OilHappy Hour 4-7 PM\n$5 - Wine, Beer, Wine Cocktails, Olives and Cheese, Bread & Oil",
    "specialSaturday": "",
    "specialSunday": "Sangria Sunday 12-10PM\n$7 Red & White Wine Sangrias, Traditional Mimosas, Draft Beers, $5 Limoncello Crema, $4 Limoncello ClassicSangria Sunday 12-10PM\n$7 Red & White Wine Sangrias, Traditional Mimosas, Draft Beers, $5 Limoncello Crema, $4 Limoncello Classic",
    "Note": ""
  },
  {
    "ID": 28,
    "Bar": "Kaze",
    "Description": "Gastropub serving sushi & creative Japanese fare in a stylish space, with a lounge & beer garden.",
    "Neighborhood": "Over-the-Rhine",
    "Address": "1400 Vine St, Cincinnati, OH 45202",
    "Phone": "(513) 898-7991",
    "Website": "http://www.kazeotr.com/",
    "hoursMonday": "Closed",
    "hoursTuesday": "4–10PM",
    "hoursWednesday": "4–10PM",
    "hoursThursday": "4–10PM",
    "hoursFriday": "4–11PM",
    "hoursSaturday": "12–11PM",
    "hoursSunday": "12–9PM",
    "specialMonday": "HAPPY HOUR  DAILY - 4-7PM\n   • Specialty cocktails are $5\n   • Discounted select sushi rolls\n   • Ramen is only $4.5HAPPY HOUR  DAILY - 4-7PM\n   • Specialty cocktails are $5\n   • Discounted select sushi rolls\n   • Ramen is only $4.5",
    "specialTuesday": "HAPPY HOUR  DAILY - 4-7PM\n   • Specialty cocktails are $5\n   • Discounted select sushi rolls\n   • Ramen is only $4.5HAPPY HOUR  DAILY - 4-7PM\n   • Specialty cocktails are $5\n   • Discounted select sushi rolls\n   • Ramen is only $4.5",
    "specialWednesday": "HAPPY HOUR  DAILY - 4-7PM\n   • Specialty cocktails are $5\n   • Discounted select sushi rolls\n   • Ramen is only $4.5HAPPY HOUR  DAILY - 4-7PM\n   • Specialty cocktails are $5\n   • Discounted select sushi rolls\n   • Ramen is only $4.5",
    "specialThursday": "HAPPY HOUR  DAILY - 4-7PM\n   • Specialty cocktails are $5\n   • Discounted select sushi rolls\n   • Ramen is only $4.5HAPPY HOUR  DAILY - 4-7PM\n   • Specialty cocktails are $5\n   • Discounted select sushi rolls\n   • Ramen is only $4.5",
    "specialFriday": "HAPPY HOUR  DAILY - 4-7PM\n   • Specialty cocktails are $5\n   • Discounted select sushi rolls\n   • Ramen is only $4.5HAPPY HOUR  DAILY - 4-7PM\n   • Specialty cocktails are $5\n   • Discounted select sushi rolls\n   • Ramen is only $4.5",
    "specialSaturday": "HAPPY HOUR  DAILY - 4-6PM\n   • Specialty cocktails are $5\n   • Discounted select sushi rolls\n   • Ramen is only $4.5HAPPY HOUR  DAILY - 4-6PM\n   • Specialty cocktails are $5\n   • Discounted select sushi rolls\n   • Ramen is only $4.5",
    "specialSunday": "HAPPY HOUR  DAILY - 4-6PM\n   • Specialty cocktails are $5\n   • Discounted select sushi rolls\n   • Ramen is only $4.5HAPPY HOUR  DAILY - 4-6PM\n   • Specialty cocktails are $5\n   • Discounted select sushi rolls\n   • Ramen is only $4.5",
    "Note": ""
  },
  {
    "ID": 29,
    "Bar": "Ché",
    "Description": "Artisanal Argentine cuisine & empanadas, plus drinks, offered in a rustic, dimly lit dining room.",
    "Neighborhood": "Over-the-Rhine",
    "Address": "1342 Walnut St, Cincinnati, OH 45202",
    "Phone": "(513) 345-8838",
    "Website": "http://www.checincinnati.com/",
    "hoursMonday": "4PM–12AM",
    "hoursTuesday": "11AM–2:30AM",
    "hoursWednesday": "11AM–2:30AM",
    "hoursThursday": "11AM–2:30AM",
    "hoursFriday": "11AM–2:30AM",
    "hoursSaturday": "11AM–2:30AM",
    "hoursSunday": "11AM–12AM",
    "specialMonday": "Malbec Mondays\nCome enjoy any of our Malbecs by the glass for only $5 all day long.",
    "specialTuesday": "Service Industry Night\nOur friends in the Service Industry enjoy 30% off drinks all night long!\n$3 Jack Daniels\nWhen:\nEvery Tuesday from 7pm - Close.",
    "specialWednesday": "Whiskey Wednesday $3\nGet over Hump Day by joining us for $3 shots of Jameson all evening long.",
    "specialThursday": "Thirsty Thursday $4 Drafts\nBeer aficionados unite! Thursday at Ché means it's time for $4 drafts on any of our 20 beers on tap!",
    "specialFriday": "Fireball Friday\nReady to start your weekends with a bang? Pop by and join us for $3 shots of Fireball 'till the wheels fall off!",
    "specialSaturday": "Weekend Brunch\n Come check in OTR's best kept secret! 10 exclusive menu items,\n\n$4 Mimosas, and $5 Bloody Marys.\nWhen:\nSaturdays and Sundays from  11am to 3pm.",
    "specialSunday": "Weekend Brunch\n Come check in OTR's best kept secret! 10 exclusive menu items,\n\n$4 Mimosas, and $5 Bloody Marys.\nWhen:\nSaturdays and Sundays from  11am to 3pm.",
    "Note": ""
  },
  {
    "ID": 30,
    "Bar": "The Hub",
    "Description": "",
    "Neighborhood": "Over-the-Rhine",
    "Address": "1209 Main St, Cincinnati, OH 45202",
    "Phone": "(513) 746-6572",
    "Website": "http://thehubotr.com/",
    "hoursMonday": "4PM–2AM",
    "hoursTuesday": "2PM–2AM",
    "hoursWednesday": "2PM–2AM",
    "hoursThursday": "2PM–2AM",
    "hoursFriday": "2PM–2AM",
    "hoursSaturday": "2PM–2AM",
    "hoursSunday": "4PM–2AM",
    "specialMonday": "",
    "specialTuesday": "",
    "specialWednesday": "",
    "specialThursday": "",
    "specialFriday": "",
    "specialSaturday": "",
    "specialSunday": "",
    "Note": ""
  },
  {
    "ID": 31,
    "Bar": "Four Entertainment Group",
    "Description": "",
    "Neighborhood": "Over-the-Rhine",
    "Address": "1404 Vine St, Cincinnati, OH 45202",
    "Phone": "(513) 721-0083",
    "Website": "http://www.foureg.com/",
    "hoursMonday": "10AM–6PM",
    "hoursTuesday": "10AM–6PM",
    "hoursWednesday": "10AM–6PM",
    "hoursThursday": "10AM–6PM",
    "hoursFriday": "10AM–6PM",
    "hoursSaturday": "Closed",
    "hoursSunday": "Closed",
    "specialMonday": "",
    "specialTuesday": "",
    "specialWednesday": "",
    "specialThursday": "",
    "specialFriday": "",
    "specialSaturday": "",
    "specialSunday": "",
    "Note": ""
  },
  {
    "ID": 32,
    "Bar": "The Mercer OTR",
    "Description": "Varied European-influenced dishes are served in a stylish venue at this modern restaurant.",
    "Neighborhood": "Over-the-Rhine",
    "Address": "1324 Vine St, Cincinnati, OH 45202",
    "Phone": "(513) 421-5111",
    "Website": "http://www.themercerotr.com/",
    "hoursMonday": "Closed",
    "hoursTuesday": "5–10PM",
    "hoursWednesday": "5–10PM",
    "hoursThursday": "5–10PM",
    "hoursFriday": "5–11PM",
    "hoursSaturday": "5–11PM",
    "hoursSunday": "4:30–8:30PM",
    "specialMonday": "",
    "specialTuesday": "Tuesday-Half Price Wine\nBottles of wine up through $74 are 50% off. Wines $75 and up\nand wines in half bottles are 25% off.",
    "specialWednesday": "Tuesday-Half Price Wine\nBottles of wine up through $74 are 50% off. Wines $75 and up\nand wines in half bottles are 25% off.",
    "specialThursday": "Thursday Bar Burger Night\n$10 Burger & Fries, $2 High Life cans, and $2 Coors drafts.\n**This promotion is only available in the bar, lounge, and patio**",
    "specialFriday": "Friday-Half Price Wine\nBottles of wine up through $74 are 50% off. Wines $75 and up\nand wines in half bottles are 25% off.",
    "specialSaturday": "",
    "specialSunday": "Sunday Funday $5 All Night Happy Hour\nAll night in the bar, lounge, and patio you can enjoy $5 select\ncocktails, wines by the glass, and beer specials.",
    "Note": ""
  },
  {
    "ID": 33,
    "Bar": "Pontiac BBQ",
    "Description": "Rustic-chic spot with a vintage vibe offering eclectic BBQ & classic sides, plus creative cocktails.",
    "Neighborhood": "Over-the-Rhine",
    "Address": "1403 Vine St, Cincinnati, OH 45202",
    "Phone": "(513) 579-8500",
    "Website": "http://www.pontiacbbq.com/",
    "hoursMonday": "Closed",
    "hoursTuesday": "11AM–10PM",
    "hoursWednesday": "11AM–10PM",
    "hoursThursday": "11AM–10PM",
    "hoursFriday": "11AM–11PM",
    "hoursSaturday": "11AM–11PM",
    "hoursSunday": "11AM–9PM",
    "specialMonday": "",
    "specialTuesday": "",
    "specialWednesday": "",
    "specialThursday": "",
    "specialFriday": "",
    "specialSaturday": "",
    "specialSunday": "",
    "Note": ""
  },
  {
    "ID": 34,
    "Bar": "THE FUEL LOUNGE OTR",
    "Description": "",
    "Neighborhood": "Over-the-Rhine",
    "Address": "1424 Main St, Cincinnati, OH 45202",
    "Phone": "(513) 344-6274",
    "Website": "",
    "hoursMonday": "Closed",
    "hoursTuesday": "Closed",
    "hoursWednesday": "Closed",
    "hoursThursday": "9PM–1AM",
    "hoursFriday": "9PM–1AM",
    "hoursSaturday": "9PM–1AM",
    "hoursSunday": "Close",
    "specialMonday": "",
    "specialTuesday": "",
    "specialWednesday": "",
    "specialThursday": "",
    "specialFriday": "",
    "specialSaturday": "",
    "specialSunday": "",
    "Note": ""
  },
  {
    "ID": 35,
    "Bar": "Please",
    "Description": "Upscale New American kitchen with a rotating, inventive tasting menu, plus a few à la carte options.",
    "Neighborhood": "Over-the-Rhine",
    "Address": "1405 Clay St, Cincinnati, OH 45202",
    "Phone": "(513) 405-8859",
    "Website": "http://www.pleasecincinnati.com/",
    "hoursMonday": "Closed",
    "hoursTuesday": "5:30–10PM",
    "hoursWednesday": "5:30PM–12AM",
    "hoursThursday": "5:30PM–12AM",
    "hoursFriday": "5:30PM–12AM",
    "hoursSaturday": "5:30PM–12AM",
    "hoursSunday": "Closed",
    "specialMonday": "",
    "specialTuesday": "",
    "specialWednesday": "Happy Hour runs Wednesday through Friday 5:30-7:30 with cocktail, wine glass & bottle specials.",
    "specialThursday": "Happy Hour runs Wednesday through Friday 5:30-7:30 with cocktail, wine glass & bottle specials.",
    "specialFriday": "Happy Hour runs Wednesday through Friday 5:30-7:30 with cocktail, wine glass & bottle specials.",
    "specialSaturday": "",
    "specialSunday": "",
    "Note": ""
  },
  {
    "ID": 36,
    "Bar": "The Pony",
    "Description": "",
    "Neighborhood": "Over-the-Rhine",
    "Address": "1346 Main St, Cincinnati, OH 45202",
    "Phone": "(513) 954-8415",
    "Website": "",
    "hoursMonday": "4PM–2AM",
    "hoursTuesday": "4PM–2AM",
    "hoursWednesday": "4PM–2AM",
    "hoursThursday": "4PM–2AM",
    "hoursFriday": "4PM–2AM",
    "hoursSaturday": "12PM–2AM",
    "hoursSunday": "12PM–2AM",
    "specialMonday": "",
    "specialTuesday": "",
    "specialWednesday": "",
    "specialThursday": "",
    "specialFriday": "",
    "specialSaturday": "",
    "specialSunday": "",
    "Note": ""
  },
  {
    "ID": 37,
    "Bar": "The Righteous Room",
    "Description": "Arty nightspot offering beer, wine & cocktails, VIP tables & an open-air lounge with DJ music.",
    "Neighborhood": "Over-the-Rhine",
    "Address": "641 Walnut St, Cincinnati, OH 45202",
    "Phone": "(513) 381-4408",
    "Website": "http://www.therighteousroom.com/",
    "hoursMonday": "4PM–2:30AM",
    "hoursTuesday": "4PM–2:30AM",
    "hoursWednesday": "4PM–2:30AM",
    "hoursThursday": "4PM–2:30AM",
    "hoursFriday": "4PM–2:30AM",
    "hoursSaturday": "4PM–2:30AM",
    "hoursSunday": "8PM–2:30AM",
    "specialMonday": "Open – Close\n$5 Rosé (Apothic or Bellarouche)\n$5 Shots of our Infused Liquor of Month\n4-8pm\n1/2 Off All Drinks\n8pm – Close\n$5 Moscow Mules\n$5 Paris to Moscows",
    "specialTuesday": "Open – Close\n$5 Rosé (Apothic or Bellarouche)\n$5 Shots of our Infused Liquor of Month\n4-8pm\n1/2 Off All Drinks\n8pm – Close\n$3 Local Canned Beers\n$3 Shots of Jameson",
    "specialWednesday": "Open – Close\n$5 Rosé (Apothic or Bellarouche)\n$5 Shots of our Infused Liquor of Month\n4-8pm\n1/2 Off All Drinks\n8pm – Close\nHalf-price glasses of wine\nHalf-price bottles of wine",
    "specialThursday": "Open – Close\n$5 Rosé (Apothic or Bellarouche)\n$5 Shots of our Infused Liquor of Month\n4-8pm\n1/2 Off All Drinks\n8pm – Close\n$6 Don Julio Blanco\n$7 Don Julio Reposado\n$8 Don Julio Añejo\n$15 Don Julio 1942",
    "specialFriday": "Open – Close\n$5 Rosé (Apothic or Bellarouche)\n$5 Shots of our Infused Liquor of Month\n4-8pm\n1/2 Off All Drinks",
    "specialSaturday": "Open – Close\n$5 Rosé (Apothic or Bellarouche)\n$5 Shots of our Infused Liquor of Month\n4-8pm\n1/2 Off All Drinks",
    "specialSunday": "Open – Close\n$5 Rosé (Apothic or Bellarouche)\n$5 Shots of our Infused Liquor of Month\nSUNDAY\n8pm – Close\nReverse Happy Hour\nHalf-price drinks",
    "Note": ""
  },
  {
    "ID": 38,
    "Bar": "Rosedale",
    "Description": "",
    "Neighborhood": "Over-the-Rhine",
    "Address": "208 E 12th St, Cincinnati, OH 45202",
    "Phone": "(513) 864-5400",
    "Website": "http://www.rosedaleotr.com/",
    "hoursMonday": "4PM–12:30AM",
    "hoursTuesday": "4PM–2AM",
    "hoursWednesday": "4PM–2AM",
    "hoursThursday": "4PM–2AM",
    "hoursFriday": "4PM–2AM",
    "hoursSaturday": "4PM–2AM",
    "hoursSunday": "4PM–12:30AM",
    "specialMonday": "Monday – Friday: 4pm – 7pm\nHalf Price Drinks (excluding house cocktails and bottles of wine)",
    "specialTuesday": "Monday – Friday: 4pm – 7pm\nHalf Price Drinks (excluding house cocktails and bottles of wine)",
    "specialWednesday": "Monday – Friday: 4pm – 7pm\nHalf Price Drinks (excluding house cocktails and bottles of wine)",
    "specialThursday": "Monday – Friday: 4pm – 7pm\nHalf Price Drinks (excluding house cocktails and bottles of wine)",
    "specialFriday": "Monday – Friday: 4pm – 7pm\nHalf Price Drinks (excluding house cocktails and bottles of wine)",
    "specialSaturday": "",
    "specialSunday": "",
    "Note": ""
  },
  {
    "ID": 39,
    "Bar": "Miltons The Prospect Hill Tavern",
    "Description": "",
    "Neighborhood": "Over-the-Rhine",
    "Address": "301 Milton St, Cincinnati, OH 45202",
    "Phone": "(513) 784-9938",
    "Website": "",
    "hoursMonday": "4PM–2:30AM",
    "hoursTuesday": "4PM–2:30AM",
    "hoursWednesday": "4PM–2:30AM",
    "hoursThursday": "4PM–2:30AM",
    "hoursFriday": "4PM–2:30AM",
    "hoursSaturday": "4PM–2:30AM",
    "hoursSunday": "4PM–2:30AM",
    "specialMonday": "",
    "specialTuesday": "",
    "specialWednesday": "",
    "specialThursday": "",
    "specialFriday": "",
    "specialSaturday": "",
    "specialSunday": "",
    "Note": ""
  },
  {
    "ID": 40,
    "Bar": "Queen City Exchange",
    "Description": "",
    "Neighborhood": "Over-the-Rhine",
    "Address": "32 W Court St, Cincinnati, OH 45202",
    "Phone": "(513) 954-0395",
    "Website": "http://www.queencityexchange.com/",
    "hoursMonday": "4–10PM",
    "hoursTuesday": "4–11PM",
    "hoursWednesday": "4–11PM",
    "hoursThursday": "4PM–12AM",
    "hoursFriday": "3PM–2AM",
    "hoursSaturday": "12PM–2AM",
    "hoursSunday": "12–10PM",
    "specialMonday": "",
    "specialTuesday": "",
    "specialWednesday": "",
    "specialThursday": "",
    "specialFriday": "",
    "specialSaturday": "",
    "specialSunday": "",
    "Note": ""
  },
  {
    "ID": 41,
    "Bar": "Race Inn",
    "Description": "",
    "Neighborhood": "Over-the-Rhine",
    "Address": "1606 Race St, Cincinnati, OH 45202",
    "Phone": "(513) 421-2722",
    "Website": "",
    "hoursMonday": "1–8PM",
    "hoursTuesday": "1–8PM",
    "hoursWednesday": "1–8PM",
    "hoursThursday": "1–8PM",
    "hoursFriday": "1–8PM",
    "hoursSaturday": "1–8PM",
    "hoursSunday": "1–8PM",
    "specialMonday": "",
    "specialTuesday": "",
    "specialWednesday": "",
    "specialThursday": "",
    "specialFriday": "",
    "specialSaturday": "",
    "specialSunday": "",
    "Note": ""
  },
  {
    "ID": 42,
    "Bar": "Mt. Adams Pavilion",
    "Description": "Live bands & DJs perform at this hip dance club in a historic house with 4 decks & city views.",
    "Neighborhood": "Over-the-Rhine",
    "Address": "949 Pavilion St, Cincinnati, OH 45202",
    "Phone": "(513) 744-9200",
    "Website": "http://www.mountadamspavilion.com/",
    "hoursMonday": "Closed",
    "hoursTuesday": "Closed",
    "hoursWednesday": "6PM–2:30AM",
    "hoursThursday": "6PM–2:30AM",
    "hoursFriday": "6PM–2:30AM",
    "hoursSaturday": "6PM–2:30AM",
    "hoursSunday": "Closed",
    "specialMonday": "",
    "specialTuesday": "",
    "specialWednesday": "HAPPY HOUR\nWed – Fri, 6pm – 8pm\n$2.50 Domestics*\n$3 Imports*\n$5 Margaritas (frozen or rocks)\nWEDNESDAY\n6pm – 9pm\nExtended Happy Hour\n\n10pm – Close (Employee Discount Night)\n$2 off all drinks!",
    "specialThursday": "HAPPY HOUR\nWed – Fri, 6pm – 8pm\n$2.50 Domestics*\n$3 Imports*\n$5 Margaritas (frozen or rocks)\nTHURSDAY\nAfter 9pm\n$2 Bud Light Aluminum Bottles\n$3 Margaritas\n$4 Long Islands\n$4 Fireball Whisky",
    "specialFriday": "HAPPY HOUR\nWed – Fri, 6pm – 8pm\n$2.50 Domestics*\n$3 Imports*\n$5 Margaritas (frozen or rocks)",
    "specialSaturday": "",
    "specialSunday": "",
    "Note": ""
  },
  {
    "ID": 43,
    "Bar": "Symphony Hotel Jazz Lounge",
    "Description": "",
    "Neighborhood": "Over-the-Rhine",
    "Address": "210 W 14th St, Cincinnati, OH 45202",
    "Phone": "(513) 721-3353",
    "Website": "http://www.symphonyhotel.com/jazz-bar/",
    "hoursMonday": "Closed",
    "hoursTuesday": "Closed",
    "hoursWednesday": "Closed",
    "hoursThursday": "7–10PM",
    "hoursFriday": "8–11PM",
    "hoursSaturday": "8–11PM",
    "hoursSunday": "Closed",
    "specialMonday": "",
    "specialTuesday": "",
    "specialWednesday": "",
    "specialThursday": "",
    "specialFriday": "",
    "specialSaturday": "",
    "specialSunday": "",
    "Note": ""
  },
  {
    "ID": 44,
    "Bar": "Maplewood Kitchen and Bar",
    "Description": "Spacious cafe for Californian cuisine for breakfast through dinner amid wooden tables & greenery.",
    "Neighborhood": "Over-the-Rhine",
    "Address": "525 Race St, Cincinnati, OH 45202",
    "Phone": "(513) 421-2100",
    "Website": "http://www.maplewoodkitchenandbar.com/",
    "hoursMonday": "7AM–9PM",
    "hoursTuesday": "7AM–9PM",
    "hoursWednesday": "7AM–9PM",
    "hoursThursday": "7AM–9PM",
    "hoursFriday": "7AM–10PM",
    "hoursSaturday": "8AM–10PM",
    "hoursSunday": "8AM–9PM",
    "specialMonday": "",
    "specialTuesday": "",
    "specialWednesday": "",
    "specialThursday": "",
    "specialFriday": "",
    "specialSaturday": "",
    "specialSunday": "",
    "Note": ""
  },
  {
    "ID": 45,
    "Bar": "OTR LIVE",
    "Description": "",
    "Neighborhood": "Over-the-Rhine",
    "Address": "209 E 12th St, Cincinnati, OH 45202",
    "Phone": "(513) 421-5483",
    "Website": "http://otrlivemusic.com/",
    "hoursMonday": "9AM–4AM",
    "hoursTuesday": "9AM–4AM",
    "hoursWednesday": "9AM–4AM",
    "hoursThursday": "9AM–4AM",
    "hoursFriday": "9AM–4AM",
    "hoursSaturday": "9AM–4AM",
    "hoursSunday": "9AM–4AM",
    "specialMonday": "",
    "specialTuesday": "",
    "specialWednesday": "",
    "specialThursday": "",
    "specialFriday": "",
    "specialSaturday": "",
    "specialSunday": "",
    "Note": ""
  },
  {
    "ID": 46,
    "Bar": "Igby's",
    "Description": "Expansive, multifloor lounge with wood-planked walls, craft cocktails, small plates & a hip vibe.",
    "Neighborhood": "Over-the-Rhine",
    "Address": "122 E 6th St, Cincinnati, OH 45202",
    "Phone": "(513) 246-4396",
    "Website": "http://igbysbar.com/",
    "hoursMonday": "4PM–12AM",
    "hoursTuesday": "4PM–12AM",
    "hoursWednesday": "4PM–12AM",
    "hoursThursday": "4PM–12AM",
    "hoursFriday": "4PM–12AM",
    "hoursSaturday": "4PM–12AM",
    "hoursSunday": "Closed",
    "specialMonday": "$5 Drafts\n$5 Select Calls\n$5 Glasses of Dark Horse Wine 8pm – Close\nHalf-price all wine & $15 charcuterie board\n*Rare exclusions apply",
    "specialTuesday": "$5 Drafts\n$5 Select Calls\n$5 Glasses of Dark Horse Wine 8pm – Close\n$3 off all craft cocktails",
    "specialWednesday": "$5 Drafts\n$5 Select Calls\n$5 Glasses of Dark Horse Wine 8pm – Close\n$3 beers (drafts, bottles, & cans) & $3 wells\n*Rare exclusions apply",
    "specialThursday": "$5 Drafts\n$5 Select Calls\n$5 Glasses of Dark Horse Wine 8pm – Close\n$3 off all tequila & “Kill the Keg”\nFinish off the last of our designated keg and receive a $25 gift card!",
    "specialFriday": "$5 Drafts\n$5 Select Calls\n$5 Glasses of Dark Horse Wine 8pm – Close\n$100 bottle service bottles\n(Tito’s Handmade Vodka, El Jimador Tequila, Tanqueray Gin, Old Forester Whiskey, & Captain Morgan White Rum)",
    "specialSaturday": "",
    "specialSunday": "",
    "Note": ""
  },
  {
    "ID": 47,
    "Bar": "Shooks - Bar & Dance",
    "Description": "",
    "Neighborhood": "Over-the-Rhine",
    "Address": "920 Race St, Cincinnati, OH 45202",
    "Phone": "(513) 600-0990",
    "Website": "https://m.facebook.com/Shooks920/",
    "hoursMonday": "Closed",
    "hoursTuesday": "Closed",
    "hoursWednesday": "Closed",
    "hoursThursday": "8PM–2:30AM",
    "hoursFriday": "8PM–2:30AM",
    "hoursSaturday": "8PM–2:30AM",
    "hoursSunday": "Closed",
    "specialMonday": "",
    "specialTuesday": "",
    "specialWednesday": "",
    "specialThursday": "",
    "specialFriday": "",
    "specialSaturday": "",
    "specialSunday": "",
    "Note": ""
  },
  {
    "ID": 48,
    "Bar": "Knockback Nats",
    "Description": "Easygoing game-day hangout with a long bar, typical pub fare & shuffleboard, plus a small patio.",
    "Neighborhood": "Over-the-Rhine",
    "Address": "10 W 7th St, Cincinnati, OH 45202",
    "Phone": "(513) 621-1000",
    "Website": "https://www.facebook.com/Knockback-Nats-Neighborhood-Bar-146296676362/",
    "hoursMonday": "2PM–2AM",
    "hoursTuesday": "2PM–2AM",
    "hoursWednesday": "2PM–2AM",
    "hoursThursday": "2PM–2AM",
    "hoursFriday": "2PM–2AM",
    "hoursSaturday": "12PM–2AM",
    "hoursSunday": "12PM–2AM",
    "specialMonday": "",
    "specialTuesday": "",
    "specialWednesday": "",
    "specialThursday": "",
    "specialFriday": "",
    "specialSaturday": "",
    "specialSunday": "",
    "Note": ""
  },
  {
    "ID": 49,
    "Bar": "Nicholson's Tavern & Pub",
    "Description": "Men in kilts serve a Scottish-American gastropub menu with beer & brown spirits plus live music.",
    "Neighborhood": "Over-the-Rhine",
    "Address": "625 Walnut St, Cincinnati, OH 45202",
    "Phone": "(513) 564-9111",
    "Website": "http://www.nicholsonspub.com/",
    "hoursMonday": "11AM–11PM",
    "hoursTuesday": "11AM–11PM",
    "hoursWednesday": "11AM–11PM",
    "hoursThursday": "11AM–11PM",
    "hoursFriday": "11AM–1AM",
    "hoursSaturday": "11AM–1AM",
    "hoursSunday": "11AM–9PM",
    "specialMonday": "",
    "specialTuesday": "",
    "specialWednesday": "",
    "specialThursday": "",
    "specialFriday": "",
    "specialSaturday": "",
    "specialSunday": "",
    "Note": ""
  },
  {
    "ID": 50,
    "Bar": "Corkopolis",
    "Description": "",
    "Neighborhood": "Over-the-Rhine",
    "Address": "640 Main St, Cincinnati, OH 45202",
    "Phone": "(513) 381-3752",
    "Website": "http://www.corkopolis.com/",
    "hoursMonday": "11AM–10PM",
    "hoursTuesday": "11AM–10PM",
    "hoursWednesday": "11AM–10PM",
    "hoursThursday": "11AM–10PM",
    "hoursFriday": "11AM–11PM",
    "hoursSaturday": "11AM–11PM",
    "hoursSunday": "Closed",
    "specialMonday": "",
    "specialTuesday": "",
    "specialWednesday": "",
    "specialThursday": "",
    "specialFriday": "",
    "specialSaturday": "",
    "specialSunday": "",
    "Note": ""
  },
  {
    "ID": 51,
    "Bar": "Metropole",
    "Description": "Chic American outfit serving seasonal, fireplace-cooked cuisine & cocktails in the 21c Museum Hotel.",
    "Neighborhood": "Over-the-Rhine",
    "Address": "609 Walnut St, Cincinnati, OH 45202",
    "Phone": "(513) 578-6660",
    "Website": "http://metropoleonwalnut.com/",
    "hoursMonday": "7AM–10PM",
    "hoursTuesday": "7AM–10PM",
    "hoursWednesday": "7AM–10PM",
    "hoursThursday": "7AM–10PM",
    "hoursFriday": "7AM–11PM",
    "hoursSaturday": "7AM–11PM",
    "hoursSunday": "7AM–10PM",
    "specialMonday": "",
    "specialTuesday": "",
    "specialWednesday": "",
    "specialThursday": "",
    "specialFriday": "",
    "specialSaturday": "",
    "specialSunday": "",
    "Note": ""
  },
  {
    "ID": 52,
    "Bar": "The Blind Lemon",
    "Description": "Whimsical bar, named after bluesman Blind Lemon Jefferson, with live music & lots of cocktails.",
    "Neighborhood": "Over-the-Rhine",
    "Address": "936 Hatch St, Cincinnati, OH 45202",
    "Phone": "(513) 241-3885",
    "Website": "http://www.theblindlemon.com/",
    "hoursMonday": "5:30PM–2:30AM",
    "hoursTuesday": "5:30PM–2:30AM",
    "hoursWednesday": "5:30PM–2:30AM",
    "hoursThursday": "5:30PM–2:30AM",
    "hoursFriday": "5:30PM–2:30AM",
    "hoursSaturday": "3PM–2:30AM",
    "hoursSunday": "3PM–2:30AM",
    "specialMonday": "",
    "specialTuesday": "",
    "specialWednesday": "",
    "specialThursday": "",
    "specialFriday": "",
    "specialSaturday": "",
    "specialSunday": "",
    "Note": ""
  },
  {
    "ID": 53,
    "Bar": "Scene Ultra Lounge",
    "Description": "Boisterous nightspot with craft beers, cocktails, DJs, a dance floor & TVs for sports fans.",
    "Neighborhood": "Over-the-Rhine",
    "Address": "637 Walnut St, Cincinnati, OH 45202",
    "Phone": "(513) 381-4327",
    "Website": "http://www.scenecinci.com/",
    "hoursMonday": "Closed",
    "hoursTuesday": "4PM–2AM",
    "hoursWednesday": "4PM–2AM",
    "hoursThursday": "4PM–2AM",
    "hoursFriday": "4PM–2AM",
    "hoursSaturday": "4PM–2AM",
    "hoursSunday": "Closed",
    "specialMonday": "Half Price Happy Hour 4-8PM",
    "specialTuesday": "Half Price Happy Hour 4-8PM",
    "specialWednesday": "Half Price Happy Hour 4-8PM",
    "specialThursday": "Half Price Happy Hour 4-8PM",
    "specialFriday": "Half Price Happy Hour 4-8PM",
    "specialSaturday": "Half Price Happy Hour 4-8PM",
    "specialSunday": "Half Price Happy Hour 4-8PM",
    "Note": ""
  },
  {
    "ID": 54,
    "Bar": "Tokyo Kitty",
    "Description": "",
    "Neighborhood": "Over-the-Rhine",
    "Address": "575 Race St, Cincinnati, OH 45202",
    "Phone": "(513) 744-0909",
    "Website": "http://thattokyobar.com/",
    "hoursMonday": "5PM–2AM",
    "hoursTuesday": "5PM–2AM",
    "hoursWednesday": "5PM–2AM",
    "hoursThursday": "5PM–2AM",
    "hoursFriday": "5PM–2AM",
    "hoursSaturday": "5PM–2AM",
    "hoursSunday": "5PM–2AM",
    "specialMonday": "",
    "specialTuesday": "",
    "specialWednesday": "",
    "specialThursday": "",
    "specialFriday": "",
    "specialSaturday": "",
    "specialSunday": "",
    "Note": ""
  },
  {
    "ID": 55,
    "Bar": "The Cricket Lounge",
    "Description": "Cincinnatian Hotel lounge for American eats, cocktails & a daily happy hour in relaxed environs.",
    "Neighborhood": "Over-the-Rhine",
    "Address": "601 Vine St, Cincinnati, OH 45202",
    "Phone": "(513) 381-3000",
    "Website": "http://www.cincinnatianhotel.com/dining_cricketlounge.aspx",
    "hoursMonday": "11:30AM–1AM",
    "hoursTuesday": "11:30AM–1AM",
    "hoursWednesday": "11:30AM–1AM",
    "hoursThursday": "11:30AM–1AM",
    "hoursFriday": "11:30AM–1AM",
    "hoursSaturday": "11:30AM–1AM",
    "hoursSunday": "11:30AM–1AM",
    "specialMonday": "",
    "specialTuesday": "",
    "specialWednesday": "",
    "specialThursday": "",
    "specialFriday": "",
    "specialSaturday": "",
    "specialSunday": "",
    "Note": ""
  },
  {
    "ID": 56,
    "Bar": "Top of the Park at The Phelps",
    "Description": "Open-air lounge atop the Marriott Residence Inn, with cocktails, light bites & sweeping city views.",
    "Neighborhood": "Over-the-Rhine",
    "Address": "506 E 4th St, Cincinnati, OH 45202",
    "Phone": "(513) 651-1234",
    "Website": "http://www.topoftheparkcincinnati.com/",
    "hoursMonday": "5–10PM",
    "hoursTuesday": "5–10PM",
    "hoursWednesday": "5–10PM",
    "hoursThursday": "5–10PM",
    "hoursFriday": "4–11PM",
    "hoursSaturday": "4–11PM",
    "hoursSunday": "Closed",
    "specialMonday": "",
    "specialTuesday": "",
    "specialWednesday": "",
    "specialThursday": "",
    "specialFriday": "",
    "specialSaturday": "",
    "specialSunday": "",
    "Note": ""
  },
  {
    "ID": 57,
    "Bar": "Hightail",
    "Description": "",
    "Neighborhood": "Over-the-Rhine",
    "Address": "941 Pavilion St, Cincinnati, OH 45202",
    "Phone": "(513) 229-9980",
    "Website": "http://www.hightailmtadams.com/",
    "hoursMonday": "Closed",
    "hoursTuesday": "4PM–2:30AM",
    "hoursWednesday": "4PM–2:30AM",
    "hoursThursday": "4PM–2:30AM",
    "hoursFriday": "3PM–2:30AM",
    "hoursSaturday": "4PM–2:30AM",
    "hoursSunday": "4PM–12AM",
    "specialMonday": "",
    "specialTuesday": "Tues – Thurs\n4PM – 6PM\nFriday\n3PM – 6PM\nHalf-price drinks\n(excluding wine)",
    "specialWednesday": "Tues – Thurs\n4PM – 6PM\nFriday\n3PM – 6PM\nHalf-price drinks\n(excluding wine)",
    "specialThursday": "Tues – Thurs\n4PM – 6PM\nFriday\n3PM – 6PM\nHalf-price drinks\n(excluding wine)\nDecked Out\nEvery Thursday\n$2 off drafts\n$5 bombs\nCard games available",
    "specialFriday": "Every Sunday\n7PM – 9PM\nDog-friendly yappy hour. Half-price drinks and dog treats / swag available while supplies last.",
    "specialSaturday": "",
    "specialSunday": "",
    "Note": ""
  },
  {
    "ID": 58,
    "Bar": "Holy Grail Tavern & Grille",
    "Description": "Large sports bar by Great American Ball Park with 30+ TVs & a menu of burgers, pizza & sandwiches.",
    "Neighborhood": "Banks",
    "Address": "161 Joe Nuxhall Way, Cincinnati, OH 45202",
    "Phone": "(513) 621-2222",
    "Website": "http://www.holygrailcincy.com/html/banks/banks.php",
    "hoursMonday": "11AM–2:30AM",
    "hoursTuesday": "11AM–2:30AM",
    "hoursWednesday": "11AM–2:30AM",
    "hoursThursday": "11AM–2:30AM",
    "hoursFriday": "11AM–2:30AM",
    "hoursSaturday": "11AM–2:30AM",
    "hoursSunday": "11AM–2:30AM",
    "specialMonday": "",
    "specialTuesday": "",
    "specialWednesday": "",
    "specialThursday": "",
    "specialFriday": "",
    "specialSaturday": "",
    "specialSunday": "",
    "Note": " All UC and Xavier televised basketball games 5 for $10 domestic buckets"
  },
  {
    "ID": 59,
    "Bar": "The Stretch",
    "Description": "",
    "Neighborhood": "Banks",
    "Address": "191 E Freedom Way, Cincinnati, OH 45202",
    "Phone": "(513) 229-9065",
    "Website": "http://www.thestretchcincy.com/",
    "hoursMonday": "3PM–2:30AM",
    "hoursTuesday": "3PM–2:30AM",
    "hoursWednesday": "3PM–2:30AM",
    "hoursThursday": "3PM–2:30AM",
    "hoursFriday": "3PM–2:30AM",
    "hoursSaturday": "3PM–2:30AM",
    "hoursSunday": "3PM–2:30AM",
    "specialMonday": "Happy Hour\n(Monday – Friday from 3pm – 7pm)\n1/2 off all drafts (includes beer, wine, and cocktails) and $2 off select calls\nMondays\nHalf-price draft cocktails",
    "specialTuesday": "Happy Hour\n(Monday – Friday from 3pm – 7pm)\n1/2 off all drafts (includes beer, wine, and cocktails) and $2 off select calls",
    "specialWednesday": "Happy Hour\n(Monday – Friday from 3pm – 7pm)\n1/2 off all drafts (includes beer, wine, and cocktails) and $2 off select calls",
    "specialThursday": "Happy Hour\n(Monday – Friday from 3pm – 7pm)\n1/2 off all drafts (includes beer, wine, and cocktails) and $2 off select calls",
    "specialFriday": "Happy Hour\n(Monday – Friday from 3pm – 7pm)\n1/2 off all drafts (includes beer, wine, and cocktails) and $2 off select calls",
    "specialSaturday": "",
    "specialSunday": "Sunday Fundays\nAfter 6PM\n$4 drafts\n$4 bombs\n$4 Rumpleminze\n$4 Fireball",
    "Note": ""
  },
  {
    "ID": 60,
    "Bar": "Tin Roof",
    "Description": "Unpretentious shotgun shack bar & music venue with creative takes on American pub food.",
    "Neighborhood": "Banks",
    "Address": "160 E Freedom Way #150, Cincinnati, OH 45202",
    "Phone": "(513) 381-2176",
    "Website": "http://tinroofcincinnati.com/",
    "hoursMonday": "11AM–3AM",
    "hoursTuesday": "11AM–3AM",
    "hoursWednesday": "11AM–3AM",
    "hoursThursday": "11AM–3AM",
    "hoursFriday": "11AM–3AM",
    "hoursSaturday": "11AM–3AM",
    "hoursSunday": "11AM–3AM",
    "specialMonday": "Monday:  $1 Local Beers\nHAPPY HOUR\nMonday - Friday  2PM - 7PM\n$2 Domestic Drafts\n$3 Import Drafts\n$3.5 Locals Draft \n$3 Wells\n$2 off House Wines",
    "specialTuesday": "Tuesday:  50% off for Industry $3 DosXX 16oz Cans \nHAPPY HOUR\nMonday - Friday  2PM - 7PM\n$2 Domestic Drafts\n$3 Import Drafts\n$3.5 Locals Draft \n$3 Wells\n$2 off House Wines",
    "specialWednesday": "Wednesday: $5 Domestic 32 Oz Drafts\nHAPPY HOUR\nMonday - Friday  2PM - 7PM\n$2 Domestic Drafts\n$3 Import Drafts\n$3.5 Locals Draft \n$3 Wells\n$2 off House Wines",
    "specialThursday": "Thursday: $3 Wells, $3 Fireball all night \nHAPPY HOUR\nMonday - Friday  2PM - 7PM\n$2 Domestic Drafts\n$3 Import Drafts\n$3.5 Locals Draft \n$3 Wells\n$2 off House Wines",
    "specialFriday": "Friday:  $3 PBR Tall Boys, $4 House Shots \nHAPPY HOUR\nMonday - Friday  2PM - 7PM\n$2 Domestic Drafts\n$3 Import Drafts\n$3.5 Locals Draft \n$3 Wells\n$2 off House Wines",
    "specialSaturday": "Saturday:  5 for $15 Bud Light Buckets till 5pm, $3 PBR Tall Boys, $4 House Shots",
    "specialSunday": "Sunday:  $15 Bottomles Mimosas,  $5 Bloody Mary's",
    "Note": ""
  },
  {
    "ID": 61,
    "Bar": "O'Malleys In the Alley",
    "Description": "Long-standing Irish pub offering sports on TV & classic bar fare such as burgers & sandwiches.",
    "Neighborhood": "Banks",
    "Address": "25 W Ogden Pl, Cincinnati, OH 45202",
    "Phone": "(513) 381-3114",
    "Website": "http://www.omalleyscincy.com/",
    "hoursMonday": "11AM–2AM",
    "hoursTuesday": "11AM–2AM",
    "hoursWednesday": "11AM–2AM",
    "hoursThursday": "11AM–2AM",
    "hoursFriday": "11AM–2AM",
    "hoursSaturday": "11AM–2AM",
    "hoursSunday": "11AM–2AM",
    "specialMonday": "ABSOLUTELY MONDAY\nLooking for a way to bounce back from a long Monday at work? Come enjoy $4 Absolut drinks any way ya want ’em all day long. Service industry professionals enjoy 30% off drinks from 3 pm to close.",
    "specialTuesday": "TORCHED TUESDAYS\nLooking to light up your night? We’ve got the “hot” ticket right here, with $2 shots of Fireball all night long.",
    "specialWednesday": "WHISKEY WEDNESDAY\nGet over the hump with specials like $2 Jameson shots or $3 Guinness pints, or put that pinky out and enjoy a glass of any house vino for only $3!",
    "specialThursday": "CRAFT CAN THURSDAY\nCome get Crafty with us on Thursdays, when all craft cans are only $3 all day long. Snag a shot of Jagermeister for $3 or make it a Bomb for only $5.",
    "specialFriday": "BOMBS AWAY! FRIDAY\nWhat better way to tackle the weekend head-on than slamming down $3 Vegas Bombs from 3 pm to close? Nothing coming to mind? We didn’t think so. Get in here, already!",
    "specialSaturday": "CAR BOMB CHAOS SATURDAY\nThe weekend is in full swing, so let’s blow it up with $5 Car Bombs all day long.",
    "specialSunday": "SERVICE INDUSTRY SUNDAY\nService Industry friends enjoy 30% off drinks all day. We also feature Clark’s Famous Furknocker Bloody Marys for $4. Snag a pitcher of draft beer for only $10.50 All. Day. Long.",
    "Note": ""
  },
  {
    "ID": 62,
    "Bar": "Moerlein Lager House",
    "Description": "Artifact-adorned beer bar with New American fare & river views from a wraparound patio.",
    "Neighborhood": "Banks",
    "Address": "115 Joe Nuxhall Way, Cincinnati, OH 45202",
    "Phone": "(513) 421-2337",
    "Website": "http://www.moerleinlagerhouse.com/",
    "hoursMonday": "11AM–12AM",
    "hoursTuesday": "11AM–12AM",
    "hoursWednesday": "11AM–12AM",
    "hoursThursday": "11AM–12AM",
    "hoursFriday": "11AM–1AM",
    "hoursSaturday": "11AM–1AM",
    "hoursSunday": "11AM–11PM",
    "specialMonday": "",
    "specialTuesday": "",
    "specialWednesday": "",
    "specialThursday": "",
    "specialFriday": "",
    "specialSaturday": "",
    "specialSunday": "",
    "Note": ""
  },
  {
    "ID": 63,
    "Bar": "JerZees Pub & Grub",
    "Description": "Hangout serving bar fare & drinks in a space with several TVs, patio seating & frequent live music.",
    "Neighborhood": "Oakley",
    "Address": "708 Monmouth St, Newport, KY 41071",
    "Phone": "(859) 491-3500",
    "Website": "http://jerzeespub.com/",
    "hoursMonday": "11AM–2AM",
    "hoursTuesday": "11AM–2AM",
    "hoursWednesday": "11AM–2AM",
    "hoursThursday": "11AM–2AM",
    "hoursFriday": "11AM–2AM",
    "hoursSaturday": "11AM–2AM",
    "hoursSunday": "11AM–2AM",
    "specialMonday": "",
    "specialTuesday": "",
    "specialWednesday": "",
    "specialThursday": "",
    "specialFriday": "",
    "specialSaturday": "",
    "specialSunday": "",
    "Note": ""
  },
  {
    "ID": 64,
    "Bar": "Oakley Pub & Grill",
    "Description": "This cozy, casual pub with a heated patio serves American food with creative twists.",
    "Neighborhood": "Oakley",
    "Address": "3924 Isabella Ave, Cincinnati, OH 45209",
    "Phone": "(513) 531-2500",
    "Website": "http://oakleypubandgrill.com/",
    "hoursMonday": "11AM–12AM",
    "hoursTuesday": "11AM–12AM",
    "hoursWednesday": "11AM–12AM",
    "hoursThursday": "11AM–2:30AM",
    "hoursFriday": "11AM–2:30AM",
    "hoursSaturday": "11:30AM–2:30AM",
    "hoursSunday": "11:30AM–12AM",
    "specialMonday": "69 cent wings Dine-In Only\nHappy Hour Food & Drink Specials 3-6PM & 9PM - Close",
    "specialTuesday": "7.95 Buffalo Chicken Wrap\nHappy Hour Food & Drink Specials 3-6PM & 9PM - Close",
    "specialWednesday": "7.95 Burger Mania\nHappy Hour Food & Drink Specials 3-6PM & 9PM - Close",
    "specialThursday": "8.95 Pulled Pork BBQ\nHappy Hour Food & Drink Specials 3-6PM & 9PM - Close",
    "specialFriday": "7.95 Fish Fillet & Fish Tacos\nHappy Hour Food & Drink Specials 3-6PM & 9PM - Close",
    "specialSaturday": "Chef's Special\nHappy Hour Food & Drink Specials 3-6PM & 9PM - Close",
    "specialSunday": "Chef's Special\nHappy Hour Food & Drink Specials 3-6PM & 9PM - Close",
    "Note": ""
  },
  {
    "ID": 65,
    "Bar": "Oak Tavern",
    "Description": "Unpretentious sports bar with patio seating & multiple TVs, plus a menu of wings & other pub fare.",
    "Neighborhood": "Oakley",
    "Address": "3089 Madison Rd, Cincinnati, OH 45209",
    "Phone": "(513) 321-6258",
    "Website": "http://www.oaktavernoakley.com/",
    "hoursMonday": "11AM–11PM",
    "hoursTuesday": "11AM–11PM",
    "hoursWednesday": "11AM–11PM",
    "hoursThursday": "11AM–11PM",
    "hoursFriday": "11AM–12AM",
    "hoursSaturday": "11AM–12AM",
    "hoursSunday": "11AM–11PM",
    "specialMonday": "",
    "specialTuesday": "",
    "specialWednesday": "",
    "specialThursday": "",
    "specialFriday": "",
    "specialSaturday": "",
    "specialSunday": "",
    "Note": ""
  },
  {
    "ID": 66,
    "Bar": "Slammer's Lounge",
    "Description": "",
    "Neighborhood": "Oakley",
    "Address": "3239 Brotherton Rd, Cincinnati, OH 45209",
    "Phone": "(513) 871-6847",
    "Website": "",
    "hoursMonday": "11AM–2:30AM",
    "hoursTuesday": "11AM–2:30AM",
    "hoursWednesday": "11AM–2:30AM",
    "hoursThursday": "11AM–2:30AM",
    "hoursFriday": "11AM–2:30AM",
    "hoursSaturday": "11AM–2:30AM",
    "hoursSunday": "12PM–2:30AM",
    "specialMonday": "",
    "specialTuesday": "",
    "specialWednesday": "",
    "specialThursday": "",
    "specialFriday": "",
    "specialSaturday": "",
    "specialSunday": "",
    "Note": ""
  },
  {
    "ID": 67,
    "Bar": "Habits Café",
    "Description": "Hangout for American eats, craft brews & wine with seasonal outdoor seating & weekly live music.",
    "Neighborhood": "Oakley",
    "Address": "3036 Madison Rd, Cincinnati, OH 45209",
    "Phone": "(513) 631-8367",
    "Website": "http://www.habitscafe.com/",
    "hoursMonday": "11AM–2:30AM",
    "hoursTuesday": "11AM–2:30AM",
    "hoursWednesday": "11AM–2:30AM",
    "hoursThursday": "11AM–2:30AM",
    "hoursFriday": "11AM–2:30AM",
    "hoursSaturday": "9AM–2:30AM",
    "hoursSunday": "9AM–2:30AM",
    "specialMonday": "",
    "specialTuesday": "",
    "specialWednesday": "",
    "specialThursday": "",
    "specialFriday": "",
    "specialSaturday": "",
    "specialSunday": "",
    "Note": ""
  },
  {
    "ID": 68,
    "Bar": "Bar Louie",
    "Description": "Upbeat grill chain with American grub, martinis & microbrews, plus happy-hour deals.",
    "Neighborhood": "Oakley",
    "Address": "3100 Vandercar Way, Cincinnati, OH 45209",
    "Phone": "(513) 351-1453",
    "Website": "http://barlouie.com/locations/states/ohio/oakley-station?utm_source=google&utm_medium=listings",
    "hoursMonday": "11AM–2AM",
    "hoursTuesday": "11AM–2AM",
    "hoursWednesday": "11AM–2AM",
    "hoursThursday": "11AM–2AM",
    "hoursFriday": "11AM–2AM",
    "hoursSaturday": "11AM–2AM",
    "hoursSunday": "11AM–2AM",
    "specialMonday": "HAPPY HOUR\nMonday-Friday\n4pm-7pm\n$3.50 Drafts\n$4.50 Wines\n$5.50 Signature Martinis\nHalf Price Select Apps\nand Flatbreads",
    "specialTuesday": "HAPPY HOUR\nMonday-Friday\n4pm-7pm\n$3.50 Drafts\n$4.50 Wines\n$5.50 Signature Martinis\nHalf Price Select Apps\nand Flatbreads",
    "specialWednesday": "HAPPY HOUR\nMonday-Friday\n4pm-7pm\n$3.50 Drafts\n$4.50 Wines\n$5.50 Signature Martinis\nHalf Price Select Apps\nand Flatbreads",
    "specialThursday": "HAPPY HOUR\nMonday-Friday\n4pm-7pm\n$3.50 Drafts\n$4.50 Wines\n$5.50 Signature Martinis\nHalf Price Select Apps\nand Flatbreads",
    "specialFriday": "HAPPY HOUR\nMonday-Friday\n4pm-7pm\n$3.50 Drafts\n$4.50 Wines\n$5.50 Signature Martinis\nHalf Price Select Apps\nand Flatbreads",
    "specialSaturday": "",
    "specialSunday": "",
    "Note": ""
  },
  {
    "ID": 69,
    "Bar": "R P Mc Murphy's Irish Pub",
    "Description": "Upbeat bar featuring a range of draft beers, frequent live music & a patio area with fire pits.",
    "Neighborhood": "Oakley",
    "Address": "2910 Wasson Rd, Cincinnati, OH 45209",
    "Phone": "(513) 531-3300",
    "Website": "http://www.rpmcmurphyspub.com/",
    "hoursMonday": "3PM–2:30AM",
    "hoursTuesday": "3PM–2:30AM",
    "hoursWednesday": "3PM–2:30AM",
    "hoursThursday": "3PM–2:30AM",
    "hoursFriday": "3PM–2:30AM",
    "hoursSaturday": "12PM–2:30AM",
    "hoursSunday": "12PM–2:30AM",
    "specialMonday": "",
    "specialTuesday": "",
    "specialWednesday": "",
    "specialThursday": "",
    "specialFriday": "",
    "specialSaturday": "",
    "specialSunday": "",
    "Note": ""
  },
  {
    "ID": 70,
    "Bar": "The Casual Pint Oakley Station",
    "Description": "",
    "Neighborhood": "Oakley",
    "Address": "3200 Vandercar Way, Cincinnati, OH 45209",
    "Phone": "(513) 351-2264",
    "Website": "http://oakleystation.thecasualpint.com/",
    "hoursMonday": "4–10PM",
    "hoursTuesday": "12–11PM",
    "hoursWednesday": "12–11PM",
    "hoursThursday": "12–11PM",
    "hoursFriday": "12PM–12AM",
    "hoursSaturday": "12PM–12AM",
    "hoursSunday": "1–9PM",
    "specialMonday": "",
    "specialTuesday": "",
    "specialWednesday": "",
    "specialThursday": "",
    "specialFriday": "",
    "specialSaturday": "",
    "specialSunday": "",
    "Note": ""
  },
  {
    "ID": 71,
    "Bar": "Oakley Wines",
    "Description": "",
    "Neighborhood": "Oakley",
    "Address": "4011 Allston St, Cincinnati, OH 45209",
    "Phone": "(513) 531-1400",
    "Website": "http://www.oakleywines.com/",
    "hoursMonday": "3PM–12AM",
    "hoursTuesday": "3PM–12AM",
    "hoursWednesday": "3PM–12AM",
    "hoursThursday": "3PM–12AM",
    "hoursFriday": "3PM–1AM",
    "hoursSaturday": "3PM–1AM",
    "hoursSunday": "Closed",
    "specialMonday": "Happy Hour prices from 4-6 pm.",
    "specialTuesday": "Happy Hour prices from 4-6 pm.",
    "specialWednesday": "Happy Hour prices from 4-6 pm.",
    "specialThursday": "Happy Hour prices from 4-6 pm.",
    "specialFriday": "Happy Hour prices from 4-6 pm.\nFriday Night Tasting\nEVERY FRIDAY NIGHT\n5 - 8 pm, $10\n​Enjoy 5 glass pours. Tasting takes places upstairs in The Tasting Room, but you're welcome to enjoy your wine downstairs in The Cellar.",
    "specialSaturday": "Happy Hour prices from 4-6 pm.",
    "specialSunday": "",
    "Note": ""
  },
  {
    "ID": 72,
    "Bar": "Maribelle's eat + drink",
    "Description": "Casual bistro serving area-sourced American eats including vegan options, plus beer & cocktails.",
    "Neighborhood": "Oakley",
    "Address": "3235 Madison Rd, Cincinnati, OH 45209",
    "Phone": "(513) 321-9111",
    "Website": "http://www.maribelleseatdrink.com/",
    "hoursMonday": "Closed",
    "hoursTuesday": "5–9PM",
    "hoursWednesday": "5–9PM",
    "hoursThursday": "5–9PM",
    "hoursFriday": "11AM–10PM",
    "hoursSaturday": "11AM–10PM",
    "hoursSunday": "11AM–9PM",
    "specialMonday": "",
    "specialTuesday": "",
    "specialWednesday": "",
    "specialThursday": "",
    "specialFriday": "",
    "specialSaturday": "",
    "specialSunday": "",
    "Note": ""
  },
  {
    "ID": 73,
    "Bar": "Hap's Irish Pub",
    "Description": "",
    "Neighborhood": "Oakley",
    "Address": "3510 Erie Ave, Cincinnati, OH 45208",
    "Phone": "(513) 871-6477",
    "Website": "https://www.facebook.com/Haps-Irish-Pub-125057637545502/",
    "hoursMonday": "12PM–2:30AM",
    "hoursTuesday": "12PM–2:30AM",
    "hoursWednesday": "12PM–2:30AM",
    "hoursThursday": "12PM–2:30AM",
    "hoursFriday": "12PM–2:30AM",
    "hoursSaturday": "9AM–2:30AM",
    "hoursSunday": "12PM–2:30AM",
    "specialMonday": "",
    "specialTuesday": "",
    "specialWednesday": "",
    "specialThursday": "",
    "specialFriday": "",
    "specialSaturday": "",
    "specialSunday": "",
    "Note": ""
  },
  {
    "ID": 74,
    "Bar": "Animations",
    "Description": "",
    "Neighborhood": "Oakley",
    "Address": "3059 Madison Rd, Cincinnati, OH 45209",
    "Phone": "(513) 871-7606",
    "Website": "",
    "hoursMonday": "12PM–2:30AM",
    "hoursTuesday": "12PM–2:30AM",
    "hoursWednesday": "12PM–2:30AM",
    "hoursThursday": "12PM–2:30AM",
    "hoursFriday": "12PM–2:30AM",
    "hoursSaturday": "12PM–2:30AM",
    "hoursSunday": "12PM–2:30AM",
    "specialMonday": "",
    "specialTuesday": "",
    "specialWednesday": "",
    "specialThursday": "",
    "specialFriday": "",
    "specialSaturday": "",
    "specialSunday": "",
    "Note": ""
  },
  {
    "ID": 75,
    "Bar": "Keystone Bar & Grill",
    "Description": "A lively spot for gourmet bar food (available family-style), cocktails, wine & a lengthy beer menu.",
    "Neighborhood": "Oakley",
    "Address": "1626, 3384 Erie Ave, Cincinnati, OH 45208",
    "Phone": "(513) 321-2150",
    "Website": "http://www.keystonebar.com/",
    "hoursMonday": "11:30AM–12AM",
    "hoursTuesday": "11:30AM–12AM",
    "hoursWednesday": "11:30AM–12AM",
    "hoursThursday": "11:30AM–12AM",
    "hoursFriday": "11:30AM–2:30AM",
    "hoursSaturday": "10AM–2:30AM",
    "hoursSunday": "10AM–12AM",
    "specialMonday": "Half-Price Mac & Cheese\nw/ beverage purchase until 11pm and $4 Moscow Mules from 6pm – Close\nMonday – Friday 3-6pm\n1/2 price appetizers, 1/2 price bottles of wine, 1/2 price signature cocktails, $2 off select drafts, and $2 domestics",
    "specialTuesday": "Half-Price Quesadillas\nw/ beverage purchase until 11pm and $2 Tall Boys all day\nMonday – Friday 3-6pm\n1/2 price appetizers, 1/2 price bottles of wine, 1/2 price signature cocktails, $2 off select drafts, and $2 domestics",
    "specialWednesday": "BYOB (Build Your Own Burger Night)\nLocal beer of the month for $3 beginning at 6pm\nMonday – Friday 3-6pm\n1/2 price appetizers, 1/2 price bottles of wine, 1/2 price signature cocktails, $2 off select drafts, and $2 domestics",
    "specialThursday": "Half-Price Pints\nall day *rare exclusions apply\nMonday – Friday 3-6pm\n1/2 price appetizers, 1/2 price bottles of wine, 1/2 price signature cocktails, $2 off select drafts, and $2 domestics",
    "specialFriday": "Double-Down Happy Hour\nHappy hour pricing from 3-6pm and 9pm-close\nMonday – Friday 3-6pm\n1/2 price appetizers, 1/2 price bottles of wine, 1/2 price signature cocktails, $2 off select drafts, and $2 domestics",
    "specialSaturday": "$14 Mimosa Pitchers (10am – 2pm)\n$3 Green Tea, Jameson, Fireball, Big Blue shots with the purchase of any beer from 9pm-close",
    "specialSunday": "$14 Mimosa Pitchers (11am – 2pm)\n$2 domestic bottles and half-price signature cocktails from 2pm-close",
    "Note": ""
  },
  {
    "ID": 76,
    "Bar": "Edge Inn Tavern",
    "Description": "",
    "Neighborhood": "Oakley",
    "Address": "3935 Edwards Rd, Cincinnati, OH 45209",
    "Phone": "(513) 841-9030",
    "Website": "",
    "hoursMonday": "1PM–2:30AM",
    "hoursTuesday": "1PM–2:30AM",
    "hoursWednesday": "1PM–2:30AM",
    "hoursThursday": "1PM–2:30AM",
    "hoursFriday": "1PM–2:30AM",
    "hoursSaturday": "12PM–2:30AM",
    "hoursSunday": "12PM–2:30AM",
    "specialMonday": "",
    "specialTuesday": "",
    "specialWednesday": "",
    "specialThursday": "",
    "specialFriday": "",
    "specialSaturday": "",
    "specialSunday": "",
    "Note": ""
  },
  {
    "ID": 77,
    "Bar": "Establishment",
    "Description": "",
    "Neighborhood": "Oakley",
    "Address": "2900 Wasson Rd, Cincinnati, OH 45209",
    "Phone": "(513) 631-9000",
    "Website": "http://theeoakley.com/",
    "hoursMonday": "3:30PM–2:30AM",
    "hoursTuesday": "3:30PM–2:30AM",
    "hoursWednesday": "3:30PM–2:30AM",
    "hoursThursday": "3:30PM–2:30AM",
    "hoursFriday": "3:30PM–2:30AM",
    "hoursSaturday": "3:30PM–2:30AM",
    "hoursSunday": "12PM–2:30AM",
    "specialMonday": "Happy Hour:\nMonday – Thursday 3:30pm – 9pm\n$2.00 Domestic Bottles and drafts\n$3.00 Well Liquor Drinks",
    "specialTuesday": "Happy Hour:\nMonday – Thursday 3:30pm – 9pm\n$2.00 Domestic Bottles and drafts\n$3.00 Well Liquor Drinks",
    "specialWednesday": "Happy Hour:\nMonday – Thursday 3:30pm – 9pm\n$2.00 Domestic Bottles and drafts\n$3.00 Well Liquor Drinks",
    "specialThursday": "Happy Hour:\nMonday – Thursday 3:30pm – 9pm\n$2.00 Domestic Bottles and drafts\n$3.00 Well Liquor Drinks",
    "specialFriday": "Happy Hour:\nFriday 3:30pm – 7:30pm\n$2.00 Domestic Bottles and drafts\n$3.00 Well Liquor Drinks",
    "specialSaturday": "Happy Hour:\nSaturday – Sunday 12pm – 7:30pm\n$2.00 Domestic Bottles and drafts\n$3.00 Well Liquor Drinks",
    "specialSunday": "Happy Hour:\nSaturday – Sunday 12pm – 7:30pm\n$2.00 Domestic Bottles and drafts\n$3.00 Well Liquor Drinks",
    "Note": ""
  },
  {
    "ID": 78,
    "Bar": "Unwind Wine Bar & Light Fare",
    "Description": "Modern-yet-rustic bar offering wine, spirits & small plates in a relaxed setting with patio seating.",
    "Neighborhood": "Oakley",
    "Address": "3435 Michigan Ave, Cincinnati, OH 45208",
    "Phone": "(513) 321-9463",
    "Website": "http://www.unwindhydepark.com/",
    "hoursMonday": "4–11PM",
    "hoursTuesday": "4–11PM",
    "hoursWednesday": "4–11PM",
    "hoursThursday": "4PM–12AM",
    "hoursFriday": "4PM–1:15AM",
    "hoursSaturday": "4PM–12AM",
    "hoursSunday": "Closed",
    "specialMonday": "",
    "specialTuesday": "",
    "specialWednesday": "",
    "specialThursday": "",
    "specialFriday": "",
    "specialSaturday": "",
    "specialSunday": "",
    "Note": ""
  },
  {
    "ID": 79,
    "Bar": "MadTree Brewing",
    "Description": "Bustling taproom offering craft beers, wood-fired pizzas, growler fills & keg sales, plus a patio.",
    "Neighborhood": "Oakley",
    "Address": "3301 Madison Rd, Cincinnati, OH 45209",
    "Phone": "(513) 836-8733",
    "Website": "http://www.madtreebrewing.com/",
    "hoursMonday": "11AM–11PM",
    "hoursTuesday": "11AM–11PM",
    "hoursWednesday": "11AM–11PM",
    "hoursThursday": "11AM–11PM",
    "hoursFriday": "11AM–1AM",
    "hoursSaturday": "10AM–1AM",
    "hoursSunday": "10AM–11PM",
    "specialMonday": "",
    "specialTuesday": "",
    "specialWednesday": "",
    "specialThursday": "",
    "specialFriday": "",
    "specialSaturday": "",
    "specialSunday": "",
    "Note": ""
  },
  {
    "ID": 80,
    "Bar": "The Pub at Rookwood Mews",
    "Description": "British-inspired pub with a wraparound bar serves comfort eats & pints in charming, old-world digs.",
    "Neighborhood": "Oakley",
    "Address": "2692 Edmondson Rd, Cincinnati, OH 45208",
    "Phone": "(513) 841-2748",
    "Website": "http://experiencethepub.com/rookwood",
    "hoursMonday": "11AM–12AM",
    "hoursTuesday": "11AM–12AM",
    "hoursWednesday": "11AM–12AM",
    "hoursThursday": "11AM–12AM",
    "hoursFriday": "11AM–1AM",
    "hoursSaturday": "10AM–1AM",
    "hoursSunday": "10AM–11PM",
    "specialMonday": "Happy Hour\nMonday – Friday | 3pm – 7pm\n$5.00 Appetizers\nDrink Specials\nMonday\nPub Quiz 7:30pm",
    "specialTuesday": "Happy Hour\nMonday – Friday | 3pm – 7pm\n$5.00 Appetizers\nDrink Specials",
    "specialWednesday": "Happy Hour\nMonday – Friday | 3pm – 7pm\n$5.00 Appetizers\nDrink Specials\nWednesday\n1/2 priced bottles of select wines",
    "specialThursday": "Happy Hour\nMonday – Friday | 3pm – 7pm\n$5.00 Appetizers\nDrink Specials",
    "specialFriday": "Happy Hour\nMonday – Friday | 3pm – 7pm\n$5.00 Appetizers\nDrink Specials",
    "specialSaturday": "",
    "specialSunday": "",
    "Note": "Military Discount\nAll members of the military receive a 25% discount on food purchases when they present a military ID."
  },
  {
    "ID": 81,
    "Bar": "Dutch's",
    "Description": "A massive collection of handcrafted beer & wine (to drink or buy), plus artisanal meats & cheeses.",
    "Neighborhood": "Oakley",
    "Address": "3378 Erie Ave, Cincinnati, OH 45208",
    "Phone": "(513) 871-1446",
    "Website": "http://www.dutchscincinnati.com/",
    "hoursMonday": "Closed",
    "hoursTuesday": "11AM–9PM",
    "hoursWednesday": "11AM–9PM",
    "hoursThursday": "11AM–9PM",
    "hoursFriday": "11AM–10PM",
    "hoursSaturday": "11AM–10PM",
    "hoursSunday": "11AM–9PM",
    "specialMonday": "",
    "specialTuesday": "",
    "specialWednesday": "",
    "specialThursday": "",
    "specialFriday": "",
    "specialSaturday": "",
    "specialSunday": "",
    "Note": ""
  },
  {
    "ID": 82,
    "Bar": "MILLIONS CAFÉ",
    "Description": "",
    "Neighborhood": "Oakley",
    "Address": "3210 Linwood Ave, Cincinnati, OH 45208",
    "Phone": "(513) 815-4500",
    "Website": "http://www.millions-cafe.com/",
    "hoursMonday": "4PM–2:30AM",
    "hoursTuesday": "4PM–2:30AM",
    "hoursWednesday": "4PM–2:30AM",
    "hoursThursday": "4PM–2:30AM",
    "hoursFriday": "4PM–2:30AM",
    "hoursSaturday": "11:30AM–2:30AM",
    "hoursSunday": "11:30AM–2:30AM",
    "specialMonday": "",
    "specialTuesday": "",
    "specialWednesday": "",
    "specialThursday": "",
    "specialFriday": "",
    "specialSaturday": "",
    "specialSunday": "",
    "Note": ""
  },
  {
    "ID": 83,
    "Bar": "Hooligan's Pub & Eatery",
    "Description": "Longtime family-owned joint with American eats, an outdoor patio & a seasonal sand volleyball court.",
    "Neighborhood": "Oakley",
    "Address": "3340 Highland Ave, Cincinnati, OH 45213",
    "Phone": "(513) 841-9994",
    "Website": "http://www.hooligans-pub.com/",
    "hoursMonday": "11AM–2:30AM",
    "hoursTuesday": "11AM–2:30AM",
    "hoursWednesday": "11AM–2:30AM",
    "hoursThursday": "11AM–2:30AM",
    "hoursFriday": "11AM–2:30AM",
    "hoursSaturday": "11AM–2:30AM",
    "hoursSunday": "11AM–2:30AM",
    "specialMonday": "",
    "specialTuesday": "",
    "specialWednesday": "",
    "specialThursday": "",
    "specialFriday": "",
    "specialSaturday": "",
    "specialSunday": "",
    "Note": ""
  },
  {
    "ID": 84,
    "Bar": "BrewRiver GastroPub",
    "Description": "Riverside tavern with a big patio, serving N’Awlins-style American classics & oodles of local brews.",
    "Neighborhood": "Oakley",
    "Address": "2062 Riverside Dr, Cincinnati, OH 45202",
    "Phone": "(513) 861-2484",
    "Website": "http://brewrivergastropub.com/",
    "hoursMonday": "Closed",
    "hoursTuesday": "11AM–9PM",
    "hoursWednesday": "11AM–9PM",
    "hoursThursday": "11AM–9PM",
    "hoursFriday": "11AM–10PM",
    "hoursSaturday": "10AM–10PM",
    "hoursSunday": "10AM–9PM",
    "specialMonday": "",
    "specialTuesday": "",
    "specialWednesday": "",
    "specialThursday": "",
    "specialFriday": "",
    "specialSaturday": "",
    "specialSunday": "",
    "Note": ""
  },
  {
    "ID": 85,
    "Bar": "Mt. Lookout Tavern",
    "Description": "",
    "Neighborhood": "Oakley",
    "Address": "3209 Linwood Ave, Cincinnati, OH 45226",
    "Phone": "(513) 871-9633",
    "Website": "http://www.mtlookouttavern.com/",
    "hoursMonday": "11AM–2:30AM",
    "hoursTuesday": "11AM–2:30AM",
    "hoursWednesday": "11AM–2:30AM",
    "hoursThursday": "11AM–2:30AM",
    "hoursFriday": "11AM–2:30AM",
    "hoursSaturday": "11AM–2:30AM",
    "hoursSunday": "11AM–2:30AM",
    "specialMonday": "",
    "specialTuesday": "",
    "specialWednesday": "",
    "specialThursday": "",
    "specialFriday": "",
    "specialSaturday": "",
    "specialSunday": "",
    "Note": ""
  },
  {
    "ID": 86,
    "Bar": "Zip's Café",
    "Description": "Burgers, fried fish sandwiches & other pub-grub classics go alongside beer at this longtime hangout.",
    "Neighborhood": "Oakley",
    "Address": "1036 Delta Ave, Cincinnati, OH 45208",
    "Phone": "(513) 871-9876",
    "Website": "http://www.zipscafe.com/",
    "hoursMonday": "10:30AM–11PM",
    "hoursTuesday": "10:30AM–11PM",
    "hoursWednesday": "10:30AM–11PM",
    "hoursThursday": "10:30AM–11PM",
    "hoursFriday": "10:30AM–11:30PM",
    "hoursSaturday": "10:30AM–11:30PM",
    "hoursSunday": "11AM–11PM",
    "specialMonday": "",
    "specialTuesday": "",
    "specialWednesday": "",
    "specialThursday": "",
    "specialFriday": "",
    "specialSaturday": "",
    "specialSunday": "",
    "Note": ""
  },
  {
    "ID": 87,
    "Bar": "Proof Bar",
    "Description": "",
    "Neighborhood": "Oakley",
    "Address": "3195 Linwood Ave, Cincinnati, OH 45208",
    "Phone": "",
    "Website": "",
    "hoursMonday": "5PM–2:30AM",
    "hoursTuesday": "5PM–2:30AM",
    "hoursWednesday": "5PM–2:30AM",
    "hoursThursday": "5PM–2:30AM",
    "hoursFriday": "5PM–2:30AM",
    "hoursSaturday": "5PM–2:30AM",
    "hoursSunday": "5PM–2:30AM",
    "specialMonday": "",
    "specialTuesday": "",
    "specialWednesday": "",
    "specialThursday": "",
    "specialFriday": "",
    "specialSaturday": "",
    "specialSunday": "",
    "Note": ""
  },
  {
    "ID": 88,
    "Bar": "Pearl's Bar",
    "Description": "Neighborhood pub serving beer & spirits in a 100-year-old distressed building with an outdoor patio.",
    "Neighborhood": "Oakley",
    "Address": "3520 Eastern Ave, Cincinnati, OH 45226",
    "Phone": "(513) 832-0485",
    "Website": "http://www.pearls-cincy.com/",
    "hoursMonday": "4PM–2AM",
    "hoursTuesday": "4PM–2AM",
    "hoursWednesday": "4PM–2AM",
    "hoursThursday": "4PM–2AM",
    "hoursFriday": "3PM–2AM",
    "hoursSaturday": "12PM–2AM",
    "hoursSunday": "12PM–12AM",
    "specialMonday": "",
    "specialTuesday": "",
    "specialWednesday": "",
    "specialThursday": "",
    "specialFriday": "",
    "specialSaturday": "",
    "specialSunday": "",
    "Note": ""
  },
  {
    "ID": 89,
    "Bar": "The Hi-Mark",
    "Description": "Easygoing, industrial cocktail & craft beer bar inside an 1866 house with a spacious patio.",
    "Neighborhood": "Oakley",
    "Address": "3229 Riverside Dr, Cincinnati, OH 45226",
    "Phone": "(513) 492-7119",
    "Website": "http://www.thehimark.com/",
    "hoursMonday": "4PM–12AM",
    "hoursTuesday": "4PM–12AM",
    "hoursWednesday": "4PM–12AMM–12AM",
    "hoursThursday": "4PM–12AM",
    "hoursFriday": "4PM–2AM",
    "hoursSaturday": "12PM–2AM",
    "hoursSunday": "12PM–12AM",
    "specialMonday": "",
    "specialTuesday": "",
    "specialWednesday": "",
    "specialThursday": "",
    "specialFriday": "",
    "specialSaturday": "",
    "specialSunday": "",
    "Note": ""
  },
  {
    "ID": 90,
    "Bar": "Spittoon Saloon",
    "Description": "",
    "Neighborhood": "Oakley",
    "Address": "4835 Eastern Ave, Cincinnati, OH 45208",
    "Phone": "",
    "Website": "",
    "hoursMonday": "Closed",
    "hoursTuesday": "Closed",
    "hoursWednesday": "Closed",
    "hoursThursday": "5PM–3AM",
    "hoursFriday": "5PM–3AM",
    "hoursSaturday": "5PM–3AM",
    "hoursSunday": "5PM–3AM",
    "specialMonday": "",
    "specialTuesday": "",
    "specialWednesday": "",
    "specialThursday": "",
    "specialFriday": "",
    "specialSaturday": "",
    "specialSunday": "",
    "Note": ""
  },
  {
    "ID": 91,
    "Bar": "Cock & Bull Public House Hyde Park Square",
    "Description": "",
    "Neighborhood": "Oakley",
    "Address": "2645 Erie Ave, Cincinnati, OH 45208",
    "Phone": "(513) 533-4253",
    "Website": "http://www.cockandbullcincinnati.com/",
    "hoursMonday": "11AM–11PM",
    "hoursTuesday": "11AM–11PM",
    "hoursWednesday": "11AM–11PM",
    "hoursThursday": "11AM–12AM",
    "hoursFriday": "11AM–2AM",
    "hoursSaturday": "11AM–2AM",
    "hoursSunday": "11AM–10PM",
    "specialMonday": "",
    "specialTuesday": "",
    "specialWednesday": "",
    "specialThursday": "Pint Night - 6PM Keep the Glass",
    "specialFriday": "",
    "specialSaturday": "",
    "specialSunday": "",
    "Note": ""
  }
]
